### ISSUE TITLE
Please describe difference between LinkTypes

### ISSUE THREAD

**Issue by Exzakto** [MicrosoftDocs/office-docs-powershell#10182]
Please describe difference between LinkTypes on this page. What is an aggregator? What is a subscriber? This info doesn't seem to be readily available in any documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1061fe5-43fc-5677-49fe-1cee4163659a
* Version Independent ID: 08387a45-1c88-9803-8168-fb9079130b9d
* Content: [Add-UnifiedGroupLinks (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/add-unifiedgrouplinks?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Exzakto, I removed the value Aggregators, because when I tried to add someone as an Aggregator to an M365 Group, I received this weird error:

> Aggregators aren't allowed in a non-data-center environment.

That was likely your biggest question (and mine, too). I found no references to that value anywhere on the internet (other than [this 2018 civilian blog post](https://www.michev.info/Blog/Post/2101/reporting-on-membership-of-office-365-groups) stating that the value isn't used and can be ignored). I added some words for Members, Owners, and Subscribers, but those concepts should be fairly well covered in existing O365/M365 Group documentation and UI from the last several years.

Updates should be visible ~4:00PM Tu 11/29 PST (GMT-8).

OK?
