### ISSUE TITLE
Adding Users Not Working

### ISSUE THREAD

**Issue by VAsHachiRoku** [MicrosoftDocs/office-docs-powershell#1018]
Using the Add-TeamUser cmdlet executes no errors
Running Get-Team | Get-TeamUser return a list of users who were added

When looking at the Team using a web browser and clicking Manage Team, the users are not listed there. Able to Add a user who is showing in PowerShell as being there.

Logging in as user who in PowerShell has been added, does not see the Team.

Seems this cmdlet is not working

![addcmdletnotworking](https://user-images.githubusercontent.com/5819564/40044744-e9f7732c-585a-11e8-97f0-f89d76301b28.png)

**Comment by nsshommo** [comment]
@VAsHachiRoku Thanks for letting us know. We will look into this and will let you know.

**Comment by kenwith** [comment]
@VAsHachiRoku - once we figure this out @nsshommo and I will get this into the reference for the [Get-Team](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md) and [Get-TeamUser](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamUser.md) so others can benefit from your effort. Note these cmdlets are in Beta too so it is greatly appreciated your feedback. Here is a link to all Teams cmdlets: https://github.com/MicrosoftDocs/office-docs-powershell/tree/master/teams/teams-ps/teams

**Comment by kenwith** [comment]
@VAsHachiRoku - I am not sure on this and want to make sure it is taken care of properly. Would you please open a support ticket through your tenant so that this can be escalated through the right group? Here is a short video on how to open a ticket: https://channel9.msdn.com/Series/Welcome-to-the-Office-365-Support-Corner/Short-Video-How-to-open-an-Office-365-Modern-Support-Ticket

I am going to close this out but if you have other questions please re-open as necessary.
