### ISSUE TITLE
ExchangeOnlineManagement Powershell with new Access Token parameter

### ISSUE THREAD

**Issue by CDSFounder** [MicrosoftDocs/office-docs-powershell#10378]
I believe there is a problem with the latest preview and also latest GA release of ExchangeOnlineManagement PowerShell module (3.1.0) when using the new -AccessToken feature.

When we generate an Access Token and pass it to the command like this: `Connect-Exchangeonline -AccessToken $Token -DelegatedOrganization someOrg.onmicrosoft.com`

The end result will be that the connection is authenticated, but it does not connect to the delegated organization. Instead, it connects to the partner tenant. If you run Get-Mailbox it will show you a list of mailboxes of the partner tenant, not the delegated organization. No errors are displayed or shown.
 
If you run the command `Get-ConnectionInfomration` it will show you that you are in fact connected to the delegated organization, even though none of the other commands will return the delegated organization details:
 
Can you let us know what the problem may be? Perhaps we are doing something wrong? The expected behavior is that when we authenticate with an access token and a delegated organization parameter, we should see the delegated organization mailboxes and exchange environment.

**Comment by chrisda** [comment]
@CDSFounder, none of the official partner/delegate organization connection instructions use the AccessToken parameter. Instructions are available in the following topics:

- [Connect to Exchange Online PowerShell in customer organizations](https://learn.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell#connect-to-exchange-online-powershell-in-customer-organizations)
- [CBA/app only authentication](https://learn.microsoft.com/powershell/exchange/app-only-auth-powershell-v2) (delegated information is scattered throughout the instructions)
- [Use Azure managed identities to connect to Exchange Online PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/connect-exo-powershell-managed-identity)

Otherwise, you should open a support ticket for your issues with the AccessToken parameter. Report back here with any findings that can help improve the documentation.

**Comment by chrisda** [comment]
And, there's also this: [Use the Exchange Online PowerShell v3 Module with GDAP and App Consent](https://learn.microsoft.com/powershell/partnercenter/exchange-online-gdap-app).

**Comment by yogkumgit** [comment]
@CDSFounder Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
