### ISSUE TITLE
Description of FromAddressMatchesPatterns in New/Set-TransportRule

### ISSUE THREAD

**Issue by takayukiishimoto** [MicrosoftDocs/office-docs-powershell#10611]
There was a difference in behavior between registering with Null and registering with an empty character ("") for the parameter variable of FromAddressMatchesPatterns.
In the case of Null, an error was returned, but in the case of an empty character (""), the parameter variable was judged to be missing and all cases were targeted. Since the customer was confused by this specification, could you please post it in the documentation?

Translated with www.DeepL.com/Translator (free version)

**Comment by chrisda** [comment]
@takayukiishimoto, which cmdlets are we talking about?

- New/Set-AutoSensitivityLabelRule
- New/Set-DlpComplianceRule
- New/Set-TransportRule

**Comment by takayukiishimoto** [comment]
> @takayukiishimoto, which cmdlets are we talking about?
> 
> * New/Set-AutoSensitivityLabelRule
> * New/Set-DlpComplianceRule
> * New/Set-TransportRule

@chrisda, Reply to question. 
* New/Set-TransportRule

**Comment by chrisda** [comment]
@yogkumgit ], I added the following text to the descriptions of [ExceptIf]FromAddressMatchesPatterns:

> **Note**: Trying to search for empty From addresses using the value `""` for this parameter doesn't work.

If you want to modify the statement yourself, instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md). You only need to update one of the descriptions (I'll make the same changes to the other three).

After some research, I've found that it's difficult to use RegEx to search for empty strings, since by definition, it looks for text values. And the definition of 'empty' is difficult to define (what about weird spaces and whitespace characters?).

A guy has an [interesting topic](https://www.regular-expressions.info/email.html) about matching valid email addresses using RegEx. Perhaps you could use `!` (not) with that RegEx string?

Are you also looking for a good way to use transport rules to detect blank From addresses using [ExceptIf]FromAddressMatchesPatters and/or [ExceptIf]FromAddressContainsWords parameters?

**Comment by takayukiishimoto** [comment]
@chrisda Hello, chris. 
My first comment was the opposite. My apologies.

There was a difference in behavior between registering using Null and registering using an empty character ("") in the FromAddressMatchesPatterns parameter variable.
An error was returned for an **empty character (""),** but for **Null,** the parameter variable was considered missing and all cases were covered. Our customers were confused by this specification, could you please post this in the documentation?

**Comment by yogkumgit** [comment]
@takayukiishimoto Hope this comment is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by takayukiishimoto** [comment]
@chrisda @yogkumgit 
Sorry for the late reply.
It seems to be null if a text file is specified as the argument to the command and there is nothing in the file.
Please refer to the reference. Thank you.

**Comment by chrisda** [comment]
@takayukiishimoto, I'm still not sure of what your final ask is, but I changed the note to say:

> **Note**: Trying to search for empty From addresses using this parameter doesn't work.

Is this accurate?

**Comment by takayukiishimoto** [comment]
@chrisda 
There was a difference in behavior when registering FromAddressMatchesPatterns with an empty ("") or null parameter variable.
In the case of an empty character (""), an error was returned, but in the case of null, the parameter variable was considered to be missing, and all cases were covered.
Specifying Null was judged as Null as a result of specifying a text file as an argument and specifying the file with no description in the text file.
I may not have explained it well. If so, please reply.

**Comment by chrisda** [comment]
@takayukiishimoto, OK, but in the end, neither method works, right? That seems to be the important thing to say.

**Comment by takayukiishimoto** [comment]
@chrisda I think it is inevitable if it is a specification that it did not work, but the most important request is that an explanation of this specification be made available to the public.

**Comment by yogkumgit** [comment]
@chrisda

**Comment by yogkumgit** [comment]
@takayukiishimoto Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
