### ISSUE TITLE
List possible values for Parameters -ModuleId and -FeatureID

### ISSUE THREAD

**Issue by BohrenAn** [MicrosoftDocs/office-docs-powershell#10642]
Hi All,

I suggest to add the possible values for the Parameters -ModuleId and -FeatureID.

The command examples show these values:
-ModuleId [VivaInsights]
-FeatureId [Reflection]

On the Parameter Explanation it shows only that's a String

Regards
Andres Bohren

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9206bb91-7e94-a6c2-f9c3-fa1f8dad1162
* Version Independent ID: 3a3a2332-6c5e-ea04-17a3-b0d2c154dd39
* Content: [Add-VivaModuleFeaturePolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/add-vivamodulefeaturepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Add-VivaModuleFeaturePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@BohrenAn, I think the reason that the actual values for those parameters aren't mentioned is because they're in flux.

The technical details of the parameters and the examples are accurate as written. Plus, those cmdlets are in a closed Private Preview.

So, I would claim there's nothing to do at the moment (at least until the cmdlets hit Public Preview or GA).

**Comment by BohrenAn** [comment]
Fair enough
