### ISSUE TITLE
Using Update Module for SPO Management Shell

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1070]
We should be able to update the SPO Management shell module using the same technique as we do for the SP PnP modules, i.e., update-module. The SPO Management Shell installation is not consistent with other POSH Modules from MS and should be revised so that it can be deployed from the PowerShell Gallery like so many other modules

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
