### ISSUE TITLE
Devices List

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#1083]
Please add details on why this cmdlet returns devices that are not shown in the OWA -> Options -> Phone list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ade56cc-22bf-0a4b-5d17-b34c8f4cac91
* Version Independent ID: 28eaa44b-2fed-aa95-bd12-07924ef6c164
* Content: [Get-ActiveSyncDevice (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/get-activesyncdevice?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/devices/Get-ActiveSyncDevice.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/Get-ActiveSyncDevice.md)
* Service: **exchange-powershell**
* Product: **unspecified**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@danmyhre does the Get-MobileDevice cmdlet return the same results (I assume it does)? The *-ActiveSyncDevice cmdlets have been 'replaced' by corresponding *-MobileDevice cmdlets. I say 'replaced' because you get a warning when you run them, but they've never been removed.

Interestingly, I found some [old chatter on the web](https://social.technet.microsoft.com/Forums/office/en-US/a144c8aa-c69f-49b4-ac48-abb92292d4a4/getactivesyncdevicestatistics-shows-more-devices-than-getactivesyncdevice-for-mailboxes) describing the opposite effect: more partnerships were being shown in OWA than were shown using Get-ActiveSyncDevice.

Thanks for the feedback.

**Comment by manasrrp** [comment]
**Scenario**: In a organization there is a generic email ID used by **Employee_1** who has ActiveSync enabled on his mobile. After he left from that organization ActiveSync to be enabled to new employee **Employee_2**. Now how to **block** previous employee **Employee_1** and allow to new employee **Employee_2** only.
