### ISSUE TITLE
Clicking on the module link takes to 404

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/office-docs-powershell#1085]
Please fix link and help provide more information on how to install this module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d063d71b-c1d5-e995-9e0d-a3daf646c712
* Version Independent ID: 7cff679f-a994-e371-a227-b8c5635f1aa2
* Content: [Get-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/Get-UnifiedGroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroup.md)
* Service: **exchange-powershell**
* Product: **unspecified**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mganeshphani there's really no module to install. Exchange Server 2010/2013/2016, Exchange Online, Office 365 Security & Compliance Center, and Exchange Online Protection use remote PowerShell to connect. That link is simply an affect of the docs.microsoft.com/GitHub publishing environment, and is exacerbated by the fact that in Exchange many of the cmdlets are shared between the various environments, yet in order to keep the topics single source, we need to group them all under one 'exchange' module.

We are working on a mechanism that filters the cmdlets based on the Exchange version selection.

I'll see what I can do about removing that link. The link seems to point to a topic based on whatever folder the cmdlet is in, but none of the Exchange cmdlet folders have corresponding topics (they would be silly 'link farm' topics that would require manual maintenance, anyway) so the link 404s.

Thanks for the feedback.

**Comment by dariomws** [comment]
The Exchange module link issue was fixed this week. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
