### ISSUE TITLE
Connect to ExO PowerShell via MI requires New-ServicePrincipal

### ISSUE THREAD

**Issue by mabster** [MicrosoftDocs/office-docs-powershell#10942]
This page seems to be missing a step. We followed the instructions to the letter, but until we used the `New-ServicePrincipal` cmdlet to create a service principal in Exchange Online with the same object ID/app ID as our Azure AD service principal, the `Connect-ExchangeOnline` call would fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba626583-a2d3-00ba-6b8e-69e89e7af74c
* Version Independent ID: 4da53073-acc6-c813-8a2d-c0200f9494bf
* Content: [Use Azure managed identities to connect to Exchange Online PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/connect-exo-powershell-managed-identity?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-exo-powershell-managed-identity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/connect-exo-powershell-managed-identity.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mabster, were you doing system-assigned or user-assigned managed identity? Not that it matters, but last year when I tested and wrote up the procedures, they worked. Who knows what happened since then.

Not sure if it matters, but there was a recent update based on [customer feedback](https://github.com/MicrosoftDocs/office-docs-powershell/issues/10923) that slightly changed the procedures (use the ClientId value instead of the PrincipalId value for the ManagedIdentityAccountId parameter in the Connect-ExchangeOnline command).

**Comment by mabster** [comment]
Hi @chrisda!

Definitely a system-assigned managed identity. So I am not passing `-ManagedIdentityAccountId`. 

I was continually getting the "role specified is not supported in this scenario" error message when calling `Conncet-ExchangeOnline -ManagedIdentity -Org <myorg>.onmicrosoft.com` and as soon as we created a service principal in Exchange with the same details as our Azure AD enterprise app (and gave it a management role in Exchange), it started working.

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@mabster , the managed identity procedures have recently received a lot of scrutiny, and they should work as written.

But, the [step to grant the Exchange.ManageAsApp API permission for the managed identity to call Exchange Online](https://learn.microsoft.com/powershell/exchange/connect-exo-powershell-managed-identity#step-4-grant-the-exchangemanageasapp-api-permission-for-the-managed-identity-to-call-exchange-online) (Step 5 in user-assigned managed identity) now contains troubleshooting steps.

It seems that some organizations for as yet unknown reasons lack the Office 365 Exchange Online resource in Azure AD, so the commands in that step will fail.

We added a check to confirm that the Office 365 Exchange Online resource is available:

```powershell
Get-MgServicePrincipal -Filter "AppId eq '00000002-0000-0ff1-ce00-000000000000'"
```

And what to do if that check returns no results:

1. [Register an application in Azure AD](https://learn.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#step-1-register-the-application-in-azure-ad).
2. [use the "modify the app manifest method to assign API permissions to the application](https://learn.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#step-2-assign-api-permissions-to-the-application).

After that, rerun the **Get-MgServicePrincipal** command to verify a result.

Now the steps in [Grant the Exchange.ManageAsApp API permission for the managed identity to call Exchange Online](https://learn.microsoft.com/powershell/exchange/connect-exo-powershell-managed-identity#step-4-grant-the-exchangemanageasapp-api-permission-for-the-managed-identity-to-call-exchange-online) should work.

Otherwise, the entire procedure should work as written.

If it still doesn't work for you, you should open a support ticket about it. Report back here if they tell you anything that can help improve the documentation.

**Comment by mabster** [comment]
I dunno what to tell you, @chrisda! That service principal definitely exists in our Azure AD, but I definitely could not connect to Exchange Online with a system-assigned managed identity until we added a SP to Exchange Online with the same details as the managed identity.

I'll close this case 'coz for whatever reason this seems to be unique to our tenant, and honestly I've moved on because it's working now. Thanks for looking into it.
