### ISSUE TITLE
Get-CaseHoldPolicy: IncludeBindings and IncludeBindingsOnly parameters not explained

### ISSUE THREAD

**Issue by whatdoitype** [MicrosoftDocs/office-docs-powershell#11059]
The IncludeBindings and IncludeBindingsOnly parameters are not explained on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d47056a-b74b-3647-f6e4-e05d4743188b
* Version Independent ID: 0a4b4644-42f1-8cde-09c7-a2cde5fe0501
* Content: [Get-CaseHoldPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-caseholdpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-CaseHoldPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-CaseHoldPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@whatdoitype, empty parameter descriptions are a known commodity. Availability of a parameter vs. functionality of a parameter are two different things. You can read more about it [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).

Are you being directed to use these parameters in other content? Or are you just pointing out that they're empty?

I can tell by that "PARAMVALUE" text in the IncludeBindings parameter description that the parameter has been in that undocumented state since *before* the migration of content from TechNet to docs/learn.microsoft.com in March 2018.

**Comment by yogkumgit** [comment]
@whatdoitype Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
