### ISSUE TITLE
Add property index

### ISSUE THREAD

**Issue by danielniccoli** [MicrosoftDocs/office-docs-powershell#11148]
This page needs a property-index, to get an overview of the filterable properties at a glance. Currently it takes minutes to understand what can be filtered, because you have to read the entire page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://learn.microsoft.com/en-us/powershell/exchange/filter-properties?view=exchange-ps#filterable-properties)
* Content Source: [exchange/docs-conceptual/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/filter-properties.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@danielniccoli, that page used to contain one big table, which consolidated the information, but horizontal scrolling was required, and people complained bitterly.

I modified the article to use H2s for each property section instead of H3s. That change should force the properties to appear in the "In this article" section at the top of the article, which basically serves as an index.

Let me know if the end result is satisfactory.

**Comment by chrisda** [comment]
@danielniccoli, my changes that will publish ~11:00AM PDT (GMT-7) will definitely do that. It appears that all Office-related repos have changed recently to have the table of contents (TOC) at the top rather than the right like it did previously.

**Comment by danielniccoli** [comment]
> my changes that will publish ~11:00AM PDT (GMT-7) will definitely do that

Pardon, I didn't catch the other half of that sentence. Alright, looking forward to the index! Will report back 👍

**Comment by danielniccoli** [comment]
Result is beautiful, thanks!
