### ISSUE TITLE
New-GlobalAddressList missing

### ISSUE THREAD

**Issue by figeluren** [MicrosoftDocs/office-docs-powershell#11401]
The New-GlobalAddressList cmdlet is no longer available in the exchangePowerShell module.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 802f63aa-9fc7-087a-9b81-b604e1de3968
* Version Independent ID: 7ce3633b-e9c4-2753-2aed-c3ab2a075a2e
* Content: [New-GlobalAddressList (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-globaladdresslist?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-GlobalAddressList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-GlobalAddressList.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking. \*-AddressList and \*-GlobalAddressList cmdlets are available in one of my Microsoft 365 E5 tenants, but not in another.

**Comment by chrisda** [comment]
@figeluren, the first big hurdle is having the Address Lists role assigned: 

> In Exchange Online, this cmdlet is available only in the Address Lists role, and by default, the role isn't assigned to any role groups. To use this cmdlet, you need to add the Address Lists role to a role group (for example, to the Organization Management role group).

- I tried testing ExO RBAC permissions at <https://aka.ms/PillarEXORBACTest>, and that said my account had the required permissions (no help; I already knew that).

- I then tried adding a different admin account to the custom role group I created that has the Address Lists role assigned, and that account had access to all \*-AddressList and \*-GlobalAddressList cmdlets.

- I then logged in again using my original admin account, and that suddenly worked.

So, the cmdlets are definitely available, it just might take a while after you assign the required permissions. You can also try running the command `Enable-OrganizationCustomization -Verbose` to see if that helps (if you get the error `This operation is not required. Organization is already enabled for customization.`, then that wasn't part of the issue.

The following commands should return only the role group (existing or custom) that you added the Address Lists role to:

```powershell
$Perms = Get-ManagementRole -Cmdlet Get-GlobalAddressList

$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}
```

OK?

**Comment by figeluren** [comment]
Hi Chris,

I’m in deep waters here and way out of my comfort zone. So, I can hardly understand half of what you are trying to explain. 😝
I’m used to powershell, but not all the curves and bends of exchange. 😝

All I’m trying to do is to create an address list for all our ‘Equipment’. And after some googling, binging, bing chatting, all I can find is to run this command:
New-GlobalAddressList -Name "All equipment" -RecipientFilter "(ResourceType -eq 'Equipment')"

The New-GlobalAddressList is, as far as I can find, supposed to be in the ExchangePowerShell module. But the command is no longer available in that module as far as I can tell:
@{
RootModule = 'ExchangePowerShell.psm1'
Description ='The EP (ExchangePowerShell) Powershell module is a collection of commandlets that can be used to assist an Exchange Server 2016 administrator to perform common tasks.'
ModuleVersion = '0.11.0'
Author = 'Pietro Ciaccio | LinkedIn: https://www.linkedin.com/in/pietrociaccio | Twitter: @PietroCiac'
FunctionsToExport = @(
'Clear-EPAutoMapping'
'Clear-EPExchangeLogs'
'Convert-EPIMCEAEXtoX500'
'Get-EPMaintenanceMode'
'Disable-EPMaintenanceMode'
'Enable-EPMaintenanceMode'
'Get-EPAntimalwareStatus'
'Import-EPPSTs'
'Remove-EPProxyAddress'
'ConvertTo-EPMailUser'
'ConvertTo-EPMailContact'
'Start-EPRequiredServices'

Even according to Microsoft’s documentation it’s supposed to be in the ExchangePowerShell module:
https://learn.microsoft.com/en-us/powershell/module/exchange/new-globaladdresslist?view=exchange-ps

Thanks for trying to help, I really appreciate it.


Best regards
Patrik Westlin

**Comment by DMoenks** [comment]
Given the additional information, the **ExchangePowerShell** module available in PowerShell gallery wasn't published by Microsoft, has nothing to do with the "**ExchangePowerShell**" mentioned in the documentation and therefore shouldn't be required in this case. Instead, the ways to manage an Exchange server via PowerShell are described in the article [Exchange Server PowerShell (Exchange Management Shell)](https://learn.microsoft.com/en-us/powershell/exchange/exchange-management-shell?view=exchange-ps), especially the first _Note_ section of the article.

**Comment by figeluren** [comment]
When I said I was way out of my comfort zone with this I think you misunderstood what that meant. It meant I needed a simplified answer not a Messerschmidt response with a lot more complicated explanations of nothing. This was quite a pointless endeavor. Thanks to Chris for trying and actually get somewhere here. But responses like dominiks, just trying to prove their superiority makes me not enjoying learning powershell and server management. So, yeah, giving this up. No point in trying.

**Comment by chrisda** [comment]
@figeluren, it looks like a lot happened while I was away...

Let's take it one step at a time, incorporating many of the facts by DMoenks (who was sincere in his desire to help).

I presumed you were attempting to work in [Exchange Online PowerShell](https://learn.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell), because default lack of access to \*-GobalAddressList cmdlets is exclusively an Exchange Online problem, not an on-premises Exchange Server problem in the [Exchange Management Shell](https://learn.microsoft.com/en-us/powershell/exchange/connect-to-exchange-servers-using-remote-powershell).

The module that you use to connect to Exchange Online PowerShell is named [ExchangeOnlineManagement](https://www.powershellgallery.com/packages/ExchangeOnlineManagement/3.4.0) and is produced by Microsoft. More about the module and our installation instructions are available [here](https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-the-exchange-online-powershell-module).

FWIW, very few cmdlets are baked into the ExchangeOnlineManagement module itself (the list is [here](https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#cmdlets-in-the-exchange-online-powershell-module) if you're interested). Virtually all Exchange-related cmdlets are imported into the Windows PowerShell session during the connection process. The cmdlets that are available or not available to you are controlled by role-based access control (RBAC) in Exchange Online. I won't go too deep, but cmdlets are assigned to _roles_, roles are assigned to _role groups_, and people are added to role groups to get access to the cmdlets/features/ that allow you to do stuff.

As I explained in my first post (and is called out early in the [New-GlobalAddressList cmdlet article](https://learn.microsoft.com/powershell/module/exchange/new-globaladdresslist), the role that gives access to *\-GlobalAddressList cmdlets **isn't assigned to any role groups (including Organization Management, which includes Global Administrators) by default**.

To verify this issue, [connect to Exchange Online PowerShell using the ExchangeOnlineManagement module](https://learn.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell) and run those two commands I listed in my first response:

``powershell
$Perms = Get-ManagementRole -Cmdlet Get-GlobalAddressList

$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}
```

Unless you've done some customization, you'll get no results, because the required role (Address Lists) isn't assigned to any role groups by default, so you won't have access to the cmdlet.

To fix this issue, you have two choices:

- Add the Address Lists role to the Organization Management role group in Exchange Online. You can use the Exchange admin center (EAC) or Exchange Online PowerShell to do this. Instructions are [here](https://learn.microsoft.com/exchange/permissions-exo/role-groups#modify-role-groups).
- Create a new, custom role group and add the Address Lists role to it. You can [copy](https://learn.microsoft.com/en-exchange/permissions-exo/role-groups#copy-existing-role-groups) the Organization Management role group, give the new role group a distinctive name, and add the Address Lists role to it. This method helps preserve the default role assignments, if that interests you.

Disconnect and reconnect to Exchange Online PowerShell, and re-run those two commands again, and now you should see the role group that you added the Address Lists role to.

OK?

**Comment by yogkumgit** [comment]
@figeluren Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
