### ISSUE TITLE
Documentation doesn't match reality

### ISSUE THREAD

**Issue by billrichards14** [MicrosoftDocs/office-docs-powershell#11414]
The documentation says that the format for adding a user using -TargetedUsersToProtect is..
@{Add="OldDisplayName1;OldEmailAddress1"}
What actually works...
@{Add=OldDisplayName1;OldEmailAddress1}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15695a77-5d00-89d9-fba9-74de36ffd4cf
* Version Independent ID: 0e0863e8-82e8-0709-4204-bb406266b2f9
* Content: [Set-AntiPhishPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-antiphishpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@billrichards14, the quotes shouldn't matter.

A DisplayName value without spaces doesn't require quotes around the whole string as you described; it works fine with or without quotes.

But, if the DisplayName contains a space, the whole string must be enclosed in quotes as described; otherwise, the command doesn't work; you get the '>>' prompt on a new line asking for more input.

I also tried spaces just around the DisplayName value itself, and that doesn't work either (you get the email address in the `>>` prompt.).

OK?

**Comment by yogkumgit** [comment]
@billrichards14 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
