### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/office-docs-powershell#11418]
The **EnableAutoRelease** variable is still missing a description. 

When I run get-calendarprocessing, there's a variable called **AutoRSVPConfiguration** and there is no information about this variable on this page. I suspect this is a bit more complex based on the vaue in the get- command. So, please document accordingly. I don't see any documentation about this at all on learn.microsoft.com. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d95eb528-ab96-b415-981c-35d50c90dba0
* Version Independent ID: 0433f43b-538d-8000-a11d-69b4a5c97e0e
* Content: [Set-CalendarProcessing (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-calendarprocessing?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DontNeedNoGit, empty parameter descriptions are a known commodity. Availability vs. functionality are two different issues.

Are you being directed to you those parameters by other documentation (including blog posts?)

**Comment by yogkumgit** [comment]
@DontNeedNoGit Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DontNeedNoGit** [comment]
I don't understand the response. When you run that command, it's one of the available parameters that can be configured, but there is no documentation to explain exactly what it does. 

No, this is not coming from blog posts. We are configuring our conference rooms with Teams Rooms devices, and going over configuration options with our internal teams. The Get command shows all of the possible variables and I wanted to know what they do. So, I went to your documentation and the explanations are missing. So, I was requesting that explanations be added; or be noted as no longer relevant/supported/functional if something like that is the case.

**Comment by chrisda** [comment]
@DontNeedNoGit, I understand that the parameter is available. It wouldn't be in the article if it wasn't available. To repeat: parameter availability vs. functionality are two different issues. There are 1400+ Exchange-related cmdlets and 14,000+ parameters (not all are unique). You can read more about empty parameter descriptions [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486), if you're interested.

The reason I was asking about other sources mentioning that parameter is because that would be a clear indication that the parameter is supposed to be available and is useful, and which point I would make sure to get it documented.

As far as the output of a Get- cmdlets vs. what's available in New-/Set-, a Get- cmdlet will often have more output properties than what's actually available in configurable parameters in the corresponding New-/Set- cmdlets. There's no AutoRSVPConfiguration parameter in Set-CalendarProcessing, so we're really talking about the EnableAutoRelease parameter. We typically don't document the output of Get- cmdlets because they change frequently, and many of them are unconfigurable.

Nature abhors a vacuum, water runs downhill, etc. Which is to say, if the missing parameter fulfilled an important (presumably newer) scenario, then it would be talked about in blog posts, community content, or in other calendar processing content, including possibly in a similar UI option (if there is one).

Fundamentally, there are three basic options for available but unknown parameters like this:

- Don't mention it at all. Bad, because someone will run `Get-Command <Cmdlet>` and complain that it's not documented in the article.
- Document it with a useless description ("The EnableAutoRelease parameter enables auto-release"). Bad because it isn't helpful, and it would get lost in the sea of 14,000+ other parameters. And, we still wouldn't know if that parameter actually works (yet).
- Add the parameter with an empty description.

After careful consideration, I've found the third option to be the best out of these non-ideal options: It acknowledges the availability of the parameter (heads off \#1) and gets it out there so if it's functional, someone somewhere at some point will bring it up, and it will get documented.

In this case for this cmdlet, it appears I actually have a product team content, so I'll follow up with them to see what's up with the EnableAutoRelease parameter.

**Comment by chrisda** [comment]
@DontNeedNoGit, per authority feedback, I added the descriptions for EnableAutoRelease and PostReservationMaxClaimTimeInMinutes to:

> This parameter is reserved for internal Microsoft use.

Thanks for the feedback.

Closing
