### ISSUE TITLE
Please add a wait parameter

### ISSUE THREAD

**Issue by monsterapp** [MicrosoftDocs/office-docs-powershell#1145]
As the Apply-PnPProvisioningTemplate command may be used in the script reading from a CSV file it would be helpful to add a wait parameter in order to allow the application of the template to one site before moving on to the next site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8b1360-5133-03ea-c4de-97d7280ef82c
* Version Independent ID: f7354bf2-01b5-c097-3590-326761cc7f20
* Content: [Apply-PnPProvisioningTemplate (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/apply-pnpprovisioningtemplate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Apply-PnPProvisioningTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Apply-PnPProvisioningTemplate.md)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen for your review

**Comment by bernthulsker** [comment]
I need this, and I need it now... Is there any possible workaround other than telling the function to just wait?

**Comment by AndreaBarr** [comment]
@monsterapp Thank you for this feedback

We want to make sure your PnP issue is handled appropriatly. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
