### ISSUE TITLE
ATP cmdlets not working i.e. get-atppolicyforo365

### ISSUE THREAD

**Issue by Shadoxity** [MicrosoftDocs/office-docs-powershell#11491]
Just about none of the security and compliance cmdlets are working with exov3.
Using version 3.4.0 and have also tried with version 3.2.0 and both do not work.

After connecting with global admin with connect-ippssession it connects correctly but nothing works!

get-atppolicyforo365
Get-safelinksPolicy
Get-safelinksrule
Get-safeattachmentPolicy

etc

I cannot configure any of the ATP policies. Need to get this working asap

get-atppolicyforo365 : The term 'get-atppolicyforo365' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.

Get-dlpcompliancepolicy : The term 'Get-dlpcompliancepolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.

**Comment by chrisda** [comment]
@Shadoxity, the following cmdlets that you mentioned are available only in Exchange Online PowerShell (Connect-ExchangeOnline):

- Get-AtpPolicyForO365
- Get-SafeLinksPolicy
- Get-SafeLinksRule
- Get-SafeAttachmentPolicy

Get-DlpComplianceRule is available only in Security & Compliance PowerShell (Connect-IPPSSession).

Confusing, because the protection cmdlets are available in the Microsoft Defender Portal, not the Exchange admin center (EAC) yet the backend cmdlets are in Exchange Online PowerShell.

Also, you need to [connect to Exchange Online PowerShell](https://learn.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell) or [connect to Security & Compliance PowerShell](https://learn.microsoft.com/powershell/exchange/connect-to-scc-powershell) to see/run cmdlets. The module itself does nothing until you connect. As long as you connect using a Global Admin account, those cmdlets should be available.

**Comment by Shadoxity** [comment]
@chrisda I could have sworn I had both of those connected, I think I am going crazy. It seems to be working now. Maybe it was a delay in the services getting provisioned to the tenant as it was new licenses.
