### ISSUE TITLE
Set-PnPListItem Values & Content Types

### ISSUE THREAD

**Issue by Reddzman** [MicrosoftDocs/office-docs-powershell#1186]
When I use the PnP commands to update the document column values it changes the content type back to the out of the box (OotB) Document Content Type.  Here is my scenario...

Site content Type added to list
List columns added to Site content type on list
Check out document
Update Content type to site content type
Check in Document
Check out document
Update column values
Check in document

This process switches the content type back to the OotB Document content type.  Here is the PS I am running from a larger script.

Set-PnPFileCheckedOut -Url $Items[5]["FileRef"]
Set-PnPListItem -List $List.ID -Identity $Items[5].ID -ContentType $CT
Set-PnPFileCheckedIn -Url $Items[5]["FileRef"] -CheckinType MajorCheckIn -Comment "PowerShell Content Type Updated 2"
Set-PnPFileCheckedOut -Url $Items[5]["FileRef"]
Set-PnPListItem -List $List.ID -Identity $Items[5].ID -ContentType $CT -Values $ItemDefaults
Set-PnPFileCheckedIn -Url $Items[5]["FileRef"] -CheckinType MajorCheckIn -Comment "PowerShell Default Values Set 2"

**Comment by AndreaBarr** [comment]
@Reddzman Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
