### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/office-docs-powershell#1187]
Hi folks, small typo in the FolderContact description: "move the move the folder and create subfolders"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64d723a2-5239-a5d5-f53e-ae72f4daadd2
* Version Independent ID: 50dceacf-6417-5d59-41af-38532bb058d2
* Content: [Add-MailboxFolderPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/add-mailboxfolderpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Add-MailboxFolderPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Add-MailboxFolderPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@michevnew, I fixed it (the "move the move the" typo was actually in FolderOwner).

In the future, don't be so shy! **You** can click Edit (the pencil) in the topic and update the topic yourself. Once your change is approved, it will go live.

The "instructions" (if you can call them that since they're so simple) are here:

[https://help.github.com/articles/editing-files-in-another-user-s-repository/](https://help.github.com/articles/editing-files-in-another-user-s-repository/)

Thanks for the feedback.
