### ISSUE TITLE
Set-PnPWebTheme on subsites

### ISSUE THREAD

**Issue by webk1** [MicrosoftDocs/office-docs-powershell#1204]
I have this issue: 

The root site `https://tenant.sharepoint.com/sites/sitecollection/` is set with its own modern (  or classic ) theme. 

I am using 
`Set-PnPWebTheme -Theme "customTheme" -WebUrl "https://tenant.sharepoint.com/sites/sitecollection/subsite"`
 to apply a modern theme to a subsite , successfully .

The command initially succeeds and my subsite modern theme is applied. However as soon as I visit ( just navigate in the browser )  to another site such as the root site collection site which one is set to its own modern theme, then my subsite's modern theme is reverted back to the theme of the root site collection site... ?!? 

Not sure if browsing the site reverts the theme, but it gets reverted soon after it is applied to a subsite.

**Comment by webk1** [comment]
@VesaJuvonen Hi Vesa, would you have heard of such issue , or is it a new thing ?

**Comment by AndreaBarr** [comment]
@webk1 Thank you for your feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
