### ISSUE TITLE
New-PnPList tasks template

### ISSUE THREAD

**Issue by stevedare** [MicrosoftDocs/office-docs-powershell#1221]
Hello,

I want to add a task list to a sp site using this command:

New-PnPList -Title Taken -Template Tasks

It works, but I don't have the tasks timeline in the view?

![image](https://user-images.githubusercontent.com/40163843/41220344-641711ce-6d61-11e8-99f5-cde53f8f27fe.png)

Also when I go to the view setting, in the 'design' tab, I don't have the option to activate the timeline

When I create the taskslist manually I do have the timeline
![image](https://user-images.githubusercontent.com/40163843/41220367-74993a5e-6d61-11e8-89e1-0f7dac752222.png)

Is there a way to activate it? or a parameter to add so it's activated at creation?

Kind regards

Steve

**Comment by silvapf** [comment]
Try:

New-PnPList -Title Taken -Template **TasksWithTimelineAndHierarchy**

**Comment by AndreaBarr** [comment]
@stevedare Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
