### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1236]
Can you please provide some examples of how this should be used with other cmdlets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa98588-07ef-34d7-c358-d2e4cc163b75
* Version Independent ID: 56124b45-0cec-6c38-227f-6b344909ce5a
* Content: [Get-PnPAccessToken (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpaccesstoken?view=sharepoint-ps#related-links)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPAccessToken.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPAccessToken.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.

**Comment by DeanGross** [comment]
That repro has a documentation section that points to doc.microsoft.com. You are sending me in circles. My comments are in regards to the documentation not in regards to the code

**Comment by kenwith** [comment]
@VesaJuvonen - can you please address since this is PnP? I was under the impression the examples and reference content for PnP came from the code itself in the repo @AndreaBarr referenced. This repo does nothing other than surface PnP cmdlet references to doc.microsoft.com is how I understand it.

@DeanGross - If you are requesting more content for the PnP cmdlets I would recommend what Andrea said which is to open an issue/request in the PnP repo. The community for PnP is in the repo Andrea recommended and is an open source and community driven is how I understand it.

@VesaJuvonen - I wonder if we should look into moving the PnP cmdlet references to the https://github.com/SharePoint/PnP-PowerShell repo yet still surfacing them in the same place on docs.microsoft.com so it avoids the confusion?

**Comment by kenwith** [comment]
@DeanGross - I know this is frustrating and I apologize. I see your name very active in the docs and appreciate your feedback and perspective (and I enjoy following you on Twitter too :) ). 

Kirk and I discussed this yesterday and we will raise this with Vesa since the PnP content is confusing in this location since there is a repo dedicated to it in the github.com/sharepoint area. Closing this out but will raise it with Vesa now that he is back from Ignite.
