### ISSUE TITLE
Adding user without replacing

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1241]
How can we add new member or owner without replacing the existing members/owners?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7c0144-3d70-5812-617f-3ab914aca3eb
* Version Independent ID: f188ada0-7d29-0c95-fa51-c0a62a71a8d0
* Content: [Set-PnPUnifiedGroup (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpunifiedgroup?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPUnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPUnifiedGroup.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
