### ISSUE TITLE
Incorrect parameter documentation

### ISSUE THREAD

**Issue by grtaylor806** [MicrosoftDocs/office-docs-powershell#1242]
The document states to use an HTML colour code for -backgroundcolor, however this doesn't work, it actually wants the colour. For example black. What's even more hilarious is that if you want light blue, it will do that but you have to put lightblue and not 'light blue' as you might expect. There appears to be an undocumented number of colours you could have; for example it likes royalblue but not navyblue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aabcc26e-242d-1342-24af-a419a129e91d
* Version Independent ID: 110aa234-6fb0-ff5c-fe5c-10b86147b9ce
* Content: [Set-OMEConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/set-omeconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@grtaylor806, I've determined after testing that the BackgroundColor parameter does accept hex color code values (in 0x00xxxxxx notation, not #xxxxxx like the topic says), but only from a list of 140 _specific_ values. Or you can specific the corresponding text value (e.g., 0x0000FA9A or mediumspringgreen). Because there are so many values, I wrote a separate topic and linked to it from the parameter description. That topic is [here](https://support.office.com/article/1508cb35-c5ff-4523-b579-947b21d5515f).

Thanks for the feedback.
