### ISSUE TITLE
Incorrect Sample Parameter

### ISSUE THREAD

**Issue by obilogic** [MicrosoftDocs/office-docs-powershell#1250]
Cmdlet states use of -Subscription parameter:

Start-PnPWorkflowInstance
     -Subscription &lt;WorkflowSubscriptionPipeBind&gt;
                              -ListItem &lt;ListItemPipeBind&gt;
                              [-Web &lt;WebPipeBind&gt;]
                              [-Connection &lt;SPOnlineConnection&gt;]

However, samples use (invalid) -Name parameter

     Start-PnPWorkflowInstance -Name 'WorkflowName' -ListItem $item

     Start-PnPWorkflowInstance -Name 'WorkflowName' -ListItem 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8137a60-b5ea-297e-61d2-2271da424dba
* Version Independent ID: b3d0d338-bce4-4204-84cf-100e318621c8
* Content: [Start-PnPWorkflowInstance (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/start-pnpworkflowinstance?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Start-PnPWorkflowInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Start-PnPWorkflowInstance.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@obilogic Thank you for your feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
