### ISSUE TITLE
Date Time stamp

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/office-docs-powershell#1258]
Could these pages please have a date time stamp? It would be nice to know the last time they were updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5e3530-a63e-71ce-97c8-c904619aafa8
* Version Independent ID: 2c961b64-5c27-6331-b704-716ccfb8c5a7
* Content: [New-PnPSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen

**Comment by AndreaBarr** [comment]
@robertcaretta Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
