### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/office-docs-powershell#1274]
I could use some additional info here on dependencies. When I attempt to run this command I receive a message that I am not connected to Azure AD. Have unsuccessfully attempted to use each of these:  Connect-PnPOnline -Graph; Connect-AzureAD; Connect-MsolService;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7bf8d0b-39a5-eda0-d899-dc41d7d5eb69
* Version Independent ID: 8853ffd8-3858-9dbe-f85e-f2218f50db09
* Content: [Get-PnPUnifiedGroup (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpunifiedgroup?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPUnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPUnifiedGroup.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen for your review

**Comment by AndreaBarr** [comment]
@robertcaretta Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
