### ISSUE TITLE
Related Links not working

### ISSUE THREAD

**Issue by thomyg** [MicrosoftDocs/office-docs-powershell#1306]
Hi!
The link to PnP seems broken for me. The link looks like http://aka.ms/sppnp)[UserCustomAction](https://msdn.microsoft.com/en-us/library/office/microsoft.sharepoint.client.usercustomaction.aspx)[BasePermissions](https://msdn.microsoft.com/en-us/library/office/microsoft.sharepoint.client.basepermissions.aspx when I copy the target URL from "SharePoint Developer Patterns and Practices" but when I follow this link it redirects me to microsoft.com. Looking at the link, my best guess would be something with opening/closing brackets. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3351c6-d699-d519-cf03-e6e5bd0eac70
* Version Independent ID: 84b1728c-a818-b4b9-b63f-1630a1eb056d
* Content: [Add-PnPCustomAction (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpcustomaction?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPCustomAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPCustomAction.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@thomyg Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
