### ISSUE TITLE
Reorg Content

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1329]
I think that this overview should focus on explaining the relationship of the cmdlets between SPS, SPO and PnP. The SPS specfic content should be moved to the SPS cmdlet page and the general powershell info should be broken out onto a separate page. These changes would make this page easier to read. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d426f1f-d15b-4ba5-d980-fea5fa044188
* Version Independent ID: f10f10c6-974a-a748-732d-d7a7a4d9a5c7
* Content: [Overview](https://docs.microsoft.com/en-us/powershell/sharepoint/overview?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/overview.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/overview.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
