### ISSUE TITLE
Ensure-PnPFolder does not exist - should be Resolve-pnpFolder

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/office-docs-powershell#1333]
Hi
Description
Retrieves a folder if it exists. Use Ensure-PnPFolder to create the folder if it does not exist.

I cannot find Ensure-PnPFolder - but I can find Resolve-PnPFolder (https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/resolve-pnpfolder?view=sharepoint-ps) which appears to do the same thing.

Regards

Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b385a5-4bb6-e858-d114-df8b6b41114f
* Version Independent ID: e9821d8f-8e0b-5939-9f3e-43bffb6a0e7b
* Content: [Get-PnPFolder (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpfolder?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFolder.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@NPrice99 Thank you for your feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
