### ISSUE TITLE
Add-TeamUser doesn't affect the application at all!

### ISSUE THREAD

**Issue by Katli95** [MicrosoftDocs/office-docs-powershell#1342]
The [cmdlet](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamuser?view=teams-ps) is admittedly still in **Beta** and is reported to take up to an hour to display changes. I've created a script that runs in an Azure runbook, creates a team and adds some members and me as an owner. I've waited since last week and still no results on my tests in the Teams UI. Running the Get-TeamUser cmdlet clearly displays me as an owner even though the UI displays nothing. 

If I add myself as a member using powershell on my local machine, I finally see the project and a couple of minutes later I get upgraded to Owner and my other team members are added as well.

Am I doing something wrong or is some part of what I'm doing unsupported?

**Comment by islubin** [comment]
@Katli95, can you please confirm that you're using the latest PowerShell Module - 0.9.3 - for your automation?

**Comment by Katli95** [comment]
To the very best of my knowledge, yes :) 
![image](https://user-images.githubusercontent.com/11443825/41920568-876a0668-7950-11e8-8cba-80c89ab09c21.png)

**Comment by kenwith** [comment]
@Katli95 - I am not a SME on this but something that jumped out is that you are working with Azure Runbook. There is another Issue that mentions Azure Runbooks, https://github.com/MicrosoftDocs/office-docs-powershell/issues/1206 that support is currently working too. 

It might not be related at all but if you can please open a service request in your tenant admin this can get escalated appropriately and get to the root cause. Here is a quick video: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs. Let's keep this open until resolved.

**Comment by islubin** [comment]
We don't officially support Azure Runbooks today - so that's important to note.  That said, if you're successfully creating a group and the sync to Teams is taking >1 hour, that is not expected and Ken is spot on to direct you to support so they can help you debug.  Would be good to confirm for your case that with 0.9.3 installed in Windows PowerShell whether or not you have the same issues with sync.

**Comment by RobertIreland** [comment]
We are running into a fairly similar problem, not sure when this started however when using add-teamuser -groupid -user -role the users are shown in PowerShell but not added to the Team Members. We are using PowerShell to provision our Teams and are running 0.9.3

**Comment by kenwith** [comment]
@RobertIreland - thank you for submitting feedback. And sorry for the delay.

Sorry for the delay on responding. I am not sure and not sure what documentation that can be added. I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs

**Comment by Katli95** [comment]
Will definitely keep you posted. I have submitted a ticket and am awaiting a response. 

_Sidenote: I also realized that the process wasn't creating a Planner plan for the team when running in the runbook. Submitted that in the ticket as well._
