### ISSUE TITLE
6 sections listing the powershell syntax

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/office-docs-powershell#1347]
is this normal? the list of parameters are listed in 6 blocks of code titled "powershell"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6fd9b17-5a2f-6e0a-f25b-a78aa5530b55
* Version Independent ID: 7f729071-f372-8270-a03a-e2d025fba93f
* Content: [New-MoveRequest (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/new-moverequest?view=exchange-ps#syntax)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/New-MoveRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/New-MoveRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Mike-Crowley, multiple syntax blocks (also known as parameter sets) indicates mutually exclusive parameters, which is more likely for cmdlets like this that are shared between on-premises Exchange (3 versions) and Exchange Online. And, if a parameter is required in some cases and optional in others, that can also spawn multiple syntax blocks.

But, the process certainly isn't foolproof; I'm all for eliminating redundant blocks (blocks that are identical in every way, or that are caused by dubious parameters).

**Comment by Mike-Crowley** [comment]
Thanks – please pardon my ignorance on that topic. It just wasn’t clear and there was a lot of scrolling to do to find the next section of the article.


-Mike Crowley
