### ISSUE TITLE
Should The Documentation Show how to get the last List Item ina List ?

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/office-docs-powershell#1348]
Hi
It would be useful if the documentation showed how to get the last Item in a List.
Regards

Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51027f4b-155d-58c3-a020-3e80629567ce
* Version Independent ID: 12045879-94af-fd90-66a0-8f3db00a579f
* Content: [Get-PnPListItem (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPListItem.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@NPrice99 Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
