### ISSUE TITLE
ExpirationDate default

### ISSUE THREAD

**Issue by AngryVirginian** [MicrosoftDocs/office-docs-powershell#1403]
The default-ExpirationDate of 6 months from now can sometimes exceed the 180 days limit on SPO and result in the error

The specified expiration date is invalid. Should be greater than today and within 6 months

I needed to supply the expiration date with (GetDate).AddDays(180).ToString("yyyy-MM-ddTHH:mm:ssZ") to avoid getting the error.       

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 746cfa49-4283-ca23-368b-ad2b85b655bb
* Version Independent ID: f52226dd-12c8-b2d1-d5e1-2c44eb9f6c09
* Content: [Add-PnPWebhookSubscription (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpwebhooksubscription?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPWebhookSubscription.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPWebhookSubscription.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@AngryVirginian Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.

**Comment by fowl2** [comment]
Looks the default Expiration on the cmdlet was updated to [6 months minus 72 hours ](https://github.com/SharePoint/PnP-PowerShell/commit/aa3e8ab7f33c9a3c519532a25789edd6bf740b53)without updating the docs.
