### ISSUE TITLE
get-pnpfield -choices

### ISSUE THREAD

**Issue by ianbruckner** [MicrosoftDocs/office-docs-powershell#1434]
You can use Add-PnPField -choices to set choices, but you cannot for some reason retrieve them using Get-, nor set using Set- using those commandlets. Seems like a gap that'd be great to fill.

**Comment by AndreaBarr** [comment]
@ianbruckner Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
