### ISSUE TITLE
How to disable comments?

### ISSUE THREAD

**Issue by XabiBeltza** [MicrosoftDocs/office-docs-powershell#1438]
If I don't use the switch, it doesn't do anything. If I put the switch, it enables them!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9cbd838-1888-5be7-348b-c8862d7caedb
* Version Independent ID: 80961074-993c-c395-64d2-2b18bd048e31
* Content: [Set-PnPClientSidePage (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpclientsidepage?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPClientSidePage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPClientSidePage.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@XabiBeltza Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
