### ISSUE TITLE
Information Management Information incorrect

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/office-docs-powershell#1442]
The first three items in the Information Management Section have the same description :-
"Get the site closure status of the site which has a site policy applied"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3240d3-6a7d-fc4b-62fd-d3a5375d8a4a
* Version Independent ID: 561212df-4dab-92b7-b634-57d53d313c6f
* Content: [PnP PowerShell overview](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by NPrice99** [comment]
![capture-of-information-management](https://user-images.githubusercontent.com/8484048/42727870-03e49164-87a6-11e8-86cd-e4a28ccc59e9.PNG)

**Comment by AndreaBarr** [comment]
@NPrice99 Thank you for your feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
