### ISSUE TITLE
Copy using copy-pnpfile between Onedrive and Sharepoint site

### ISSUE THREAD

**Issue by XabiBeltza** [MicrosoftDocs/office-docs-powershell#1474]
Hello.

We are able to use Copy-PnPFile to copy from document libraries from different site collections. 
`Copy-PnPFile -SourceUrl '/sites/TEST_A_1/Entregas/airboat.obj' -TargetUrl '/sites/TEST_A_2/Entregas/' -OverwriteIfAlreadyExists`

This works because both sites start with https://_tenantid_.sharepoint.com. However, Onedrive sites are stored in the URI https://_tenantid_ _my.sharepoint.com

How can we copy a file from a user's Onedrive to a Sharepoint site directly, withouth having to download and reupload the file?

**Comment by AndreaBarr** [comment]
@XabiBeltza Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
