### ISSUE TITLE
Provide a return value

### ISSUE THREAD

**Issue by jjinatlanta** [MicrosoftDocs/office-docs-powershell#1479]
It would be helpful if this returned the ID for the newly created items  Also it would be nice to be able to set additional field values at the time of creation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e04804a-e20a-8984-b343-f1fff24e2140
* Version Independent ID: 2fa972ea-1f3d-a69f-39a1-bda0ed874e3a
* Content: [Add-PnPPublishingPage (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnppublishingpage?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPPublishingPage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPPublishingPage.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@jjinatlanta Thank you for your feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
