### ISSUE TITLE
Why is there no Sharepoint Online version of this command-let

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/office-docs-powershell#1480]
Is there an alternative PnP version for this for online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7709132-eaba-7ae9-8f3d-76fe40cc4420
* Version Independent ID: 7f5b5c75-601b-02d2-fd14-a4092aec52e8
* Content: [Backup-SPSite (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/backup-spsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Backup-SPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Backup-SPSite.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@mganeshphani Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
