### ISSUE TITLE
Can I add a list item to a Contacts list with Add-PnPListItem?

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#1488]
I tried in several ways already. I do not get any error message. However, it does not add the item.

Add-PnPListItem -List "ListName" -Values @{
        "FirstName" = $FirstName; 
        "Title"=$LastName;
        "OrganizationalIDNumber"=$OrganizationalIDNumber;
        "Email"=$Email;
        "Company"=$Company;
        "WorkCountry"=$WorkCountry;
        "UserField1"=$UserField1;
        "UserField2"=$UserField2;
        "UserField3"=$UserField3;
        "UserField4"=$UserField4
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c4c313-d931-b106-36e7-ae44cfb2e238
* Version Independent ID: a1969a78-7325-8946-c27f-8320b7bbed75
* Content: [Add-PnPListItem (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnplistitem?view=sharepoint-ps#examples)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPListItem.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@Markus-Hanisch Thank you for your feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
