### ISSUE TITLE
Poor example of the use of pipe

### ISSUE THREAD

**Issue by after8b49** [MicrosoftDocs/office-docs-powershell#1496]
In what sense does this illustrate the usage of the pipe, given that there is no pipe present in the example?

| 	Pipe symbols in parameter values indicate a choice between values. For example, `-Enabled &lt;$true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbe6e195-f640-0f1b-dae0-1d5ed62da207
* Version Independent ID: fa3de13d-0fab-7a99-3346-1f7764686781
* Content: [Exchange cmdlet syntax](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/exchange-cmdlet-syntax?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/exchange-cmdlet-syntax.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/exchange-cmdlet-syntax.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@after8b49, the issue was a content drop caused by the example in the table. Apparently, docs.microsoft.com/GitHub/markdown doesn't like the pipe character ( | ) in a table (even in `codeinline`, which is supposed to ignore all special markdown characters) because the pipe character also defines the cells in the table. If the pipe character isn't escaped out ( \| ) in a table cell, it's treated like the end of the row, and everything to the right is dropped. I fixed it by removing the codeinline formatting on the example, and escaping the pipe character.

Thanks for the feedback.
