### ISSUE TITLE
update for Example 3 !

### ISSUE THREAD

**Issue by K1eyvan** [MicrosoftDocs/office-docs-powershell#1510]
WARNING: Parameter 'FromRecycleBin' is obsolete. Use Clear-PnPTenantRecycleBinItem instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4ae9b4-8a3d-9808-74d6-51b954ee44f1
* Version Independent ID: b28c262d-dc7f-e7bf-5d6c-3bea6f2aa473
* Content: [Remove-PnPTenantSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnptenantsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPTenantSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPTenantSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@K1eyvan Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
