### ISSUE TITLE
New-PnPTerm & Sub Terms

### ISSUE THREAD

**Issue by Reddzman** [MicrosoftDocs/office-docs-powershell#1511]
It would be great to be able to add sub terms with PnP-NewTerm.  I am often creating hundreds of new terms for clients and have the powershell to automate this but I have to create sub terms manually or through custom CSOM.  Many of the existing PnP commands related to managed metadata handle the selection of sub terms using "|" to denote the structure.  IE. Term Group|Term Set|Term1|SubTerm1.  If we could do something similar with New-PnPTerm that would be extremely helpful!

**Comment by AndreaBarr** [comment]
@Reddzman Thank you for this feedback. 

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
