### ISSUE TITLE
Get-PnPNavigationNode -TopNavigationBar (Example 3) doesn't work

### ISSUE THREAD

**Issue by SarwarRana** [MicrosoftDocs/office-docs-powershell#1519]
it should be as below rather.
Get-PnPNavigationNode -Location TopNavigationBar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6633c99f-3565-84cf-f11a-cd055df5885e
* Version Independent ID: 40ba47f1-40f3-b4c4-cc93-fa29841595c2
* Content: [Get-PnPNavigationNode (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpnavigationnode?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPNavigationNode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPNavigationNode.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@SarwarRana Thank you for this feedback

We want to make sure your PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
