### ISSUE TITLE
Set-PnPHubSite not making immediate changes

### ISSUE THREAD

**Issue by nikolayyordanov** [MicrosoftDocs/office-docs-powershell#1536]
I am using the cmdlet to set the logo and the title. But the navigation is not showing the logo and the new title.
I have to click "Hub Site Settings" and change something (i.e. one letter in the title) than this is applied.

**Comment by AndreaBarr** [comment]
@nikolayyordanov Thank you for this feedback

We want to make sure you PnP issue is handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
