### ISSUE TITLE
SPO Site Designs with -IsDefault are not available for selection

### ISSUE THREAD

**Issue by patrickabel** [MicrosoftDocs/office-docs-powershell#1549]
The **-IsDefault** parameter for **Add-SPOSiteDesign** and **Set-SPOSiteDesign** appears to not be working properly for SPO Site Designs. When this parameter is provided, the site design is added successfully to the tenant, but remains hidden and un-selectable from the UI both from the SharePoint home page and the new admin center. 

The following Site Design work perfectly and is available for selection in the UI:
<img width="612" alt="screenshot at aug 06 22-05-50" src="https://user-images.githubusercontent.com/1153976/43752166-8dfa9926-99c5-11e8-8c93-44e07e3a87c6.png">

The same exact Site Design after toggling the -IsDefault property is no longer selectable from the UI despite being added/updated successfully.
<img width="605" alt="screenshot at aug 06 22-05-14" src="https://user-images.githubusercontent.com/1153976/43752202-b8cb29e0-99c5-11e8-98ce-30359367c235.png">

**Comment by kenwith** [comment]
@patrickabel - thank you for the catch and for taking the time to open an issue. I will get this on the backlog to get checked out. Appreciated!

@tseward just for FYI.

**Comment by AndreaBarr** [comment]
@patrickabel Thank you for this feedback

I am making sure this got into the backlog for the PowerShell team. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @patrickabel thanks for sharing feedback! we really appreciate it

As this repo is for documentation issues, to verify if we needed to add some clarification to Add-SPOSiteDesign and Set-SPOSiteDisegn docs, I had set up a lab to test this that you commented and I did not experience the same, I had set the **IsDefault** Property to True and I was still able to select that design from the available choices.

Some time has passed since you opened this issue, Is there a chance that it's working for you now? if you still have problems we can direct you to product support with no problem. @yogkumgit 

Thank you again.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @patrickabel  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
