### ISSUE TITLE
Example 2 syntax is not correct.

### ISSUE THREAD

**Issue by TomFranciosi** [MicrosoftDocs/office-docs-powershell#1569]
Should be 

$AllUsers = Get-Mailbox -ResultSize unlimited -Filter {RecipientTypeDetails -eq 'UserMailbox'}; $AllUsers | foreach {Get-MailboxJunkEmailConfiguration -Identity $_.Identity} | Where {$_.Enabled -eq $false} | Format-Table -Auto Identity,Enabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64eec30c-8fee-b6ee-de2b-dd2cb1b339c0
* Version Independent ID: 678ecad3-b2e1-ceb5-d02f-9807b6a2dedc
* Content: [Get-MailboxJunkEmailConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/get-mailboxjunkemailconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Get-MailboxJunkEmailConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Get-MailboxJunkEmailConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@TomFranciosi, Example 2 definitely had a problem. The main issue seems to be the `$AllUsers = Get-Mailbox -ResultSize unlimited RecipientTypeDetails UserMailbox` command. RecipientTypeDetails is missing a leading "-" to indicate a parameter. When I added that, the entire code block worked correctly.

Your alternate command also worked, but this page treated the underscores as markdown italic formatting indicators and hid them so your command looked like `...-Identity $.Identity} | Where {$.Enabled...` instead of `-Identity $_.Identity} | Where {$_.Enabled...`.

Thanks for the feedback
