### ISSUE TITLE
Is Connect-PnPOnline still using TLS 1.0?

### ISSUE THREAD

**Issue by Koning53** [MicrosoftDocs/office-docs-powershell#1581]
I'm analyzing the impact of the TLS 1.2 requirement for O365 that will be effective from October 18.
It seems in all of my Fiddler tests that Connect-PnPOnline uses TLS 1.0 when connecting to O365. 

Is anyone seeing the same behaviour, and will this be an issue in October? I'm testing on both Win7 and Win10.

**Comment by AndreaBarr** [comment]
@Koning53 Thank you for this feedback

We want to make sure your PnP issue gets addressed properly. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
