### ISSUE TITLE
(Un-)Install-PnPAppInstance deprecated but no alternatives available for (un-)install in subwebs

### ISSUE THREAD

**Issue by wpo365** [MicrosoftDocs/office-docs-powershell#1598]
When using (Un-)Install-PnPAppInstance I get the message that this is a deprecated CmdLet. However, (Un-)Install-PnPApp cannot handle the (un-)install use case of app instances in sub webs. To me it seems that (Un-)Install-PnPApp only handles apps installed in the (root of the) site collection. The same seems true for Update-PnPApp. It seems not possible to update an app installed in a sub web.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd137512-0465-68a6-dbda-9cd9a6e855d3
* Version Independent ID: 3579fcd9-a8a4-9e92-7479-2b664ae3a7d5
* Content: [Uninstall-PnPAppInstance (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/uninstall-pnpappinstance?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Uninstall-PnPAppInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Uninstall-PnPAppInstance.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@wpo365 Thank you for this feedback

We want to make sure your (un-)install issue gets handled appropriately. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
