### ISSUE TITLE
more info 

### ISSUE THREAD

**Issue by umaknow-alain** [MicrosoftDocs/office-docs-powershell#1608]
No offense but, maybe more info like, what it does. Does it remove the office group, the sharepoint site and the channel ?? What about the document attach to the teams site... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3a7ba1b-df84-fe2d-eabb-48c9d25bf7f0
* Version Independent ID: 3bea8b08-ff9a-a7c3-bfbf-1e482982b09e
* Content: [Remove-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/Remove-Team?view=teams-ps#examples)
* Content Source: [teams/teams-ps/teams/Remove-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Remove-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@umaknow-alain Thank you for this feedback

I will get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @umaknow-alain thanks for your feedback and suggestion.
I can confirm both Sharepoint Site and Office 365 Group will be deleted as part of running this cmdlet
Will update the documentation to reflect this. 
Thank you

**Comment by MBeukers** [comment]
How long will it take for the Team Sharepoint Site to be removed?
Is this a couple of hours or days?

**Comment by get-itips** [comment]
Hi @MBeukers in my tests it took a couple of minutes. Hope this info is useful to you.

**Comment by MBeukers** [comment]
Hi, After 2 hours the site was gone.

**Comment by get-itips** [comment]
Hi @MBeukers thanks for sharing what it took in your case, so we can say is that it will take a couple of hour max.
Thank you again.

**Comment by ajingar** [comment]
Been testing the Remove-Team command on our tenant, and have been getting mixed results every time.
- On my first run, it deleted the team from MS Teams and also the Office 365 Group, but not the associated SharePoint team site. 
- On the 2nd run, the Office 365 Group was deleted and the SharePoint site, but not the team in MS Teams.
- On the 3rd and 4th run, it has deleted just the Office 365 Group, but not the team nor the SharePoint site.
So to summarise, it seems to delete the Office 365 Group very well, but doesn't always complete the rest of the tasks. 
I also read the comments above, whereby after 2 hours the SharePoint site was removed. Well in my case, I checked the next day and the SharePoint site and team in MS Teams is still there. The only difference is that when I try to access the SharePoint site, I get the 'You need permission to access this site.' page. This, I assume is because the Office 365 Group has been removed.  Does it rely on some sort of  background 'Job' to finish the tasks?
