### ISSUE TITLE
Get-CsOnlineUser  cmdlet not redirecting properly from TechNet to docs.microsoft.com. Also, question about content.

### ISSUE THREAD

**Issue by kenwith** [MicrosoftDocs/office-docs-powershell#161]
The reference documentation for the SfB Get-CsOnlineUser cmdlet (article https://technet.microsoft.com/en-us/library/jj994026.aspx) states the following:
 
“If you have a hybrid or "split domain" deployment (that is, a deployment in which some users have accounts homed on Lync Online while other users have accounts homed on an on-premises version of Lync Server) keep in mind that the Get-CsOnlineUser cmdlet only returns information for Lync Online users. However, the Get-CsUser cmdlet will return information for both Lync Online users and on-premises Lync Server users. If you want to exclude Lync Online users from the data returned by the Get-CsUser cmdlet, use the following command:
 
Get-CsUser -Filter {TenantId -eq "00000000-0000-0000-0000-000000000000"}
By definition, users homed on the on-premises version of Lync Server will always have a TenantId equal to 00000000-0000-0000-0000-000000000000.“

This does not appear to be the case though. I have run the 2 cmdlets below in our own environment and also in different client environments with and without the TenantID switch and they cmdlets always return the same number of users:

Customer 1 (Hybrid Environment)
(Get-CsUser -Filter {Enabled -eq $true} –WarningAction silentlyContinue).count
9021
(Get-CsUser -Filter {(Enabled -eq $true) -and (TenantId  -eq "00000000-0000-0000-0000-000000000000")} -WarningAction silentlyContinue).count
9021

Production (Hybrid Environment)

(Get-CsUser -Filter {Enabled -eq $true} -WarningAction silentlyContinue).count
3327
(Get-CsUser -Filter {(Enabled -eq $true) -and (TenantId  -eq "00000000-0000-0000-0000-000000000000")} -WarningAction silentlyContinue).count
3327

Is there an error in the documentation or in the Get-CsUser cmdlet?

**Comment by kenwith** [comment]
I am still working to figure out how things work and how to update the documentation. I did get this back from a developer...  

"One thing they could query on is the HostingProvider. Online hosted users will always have a value of “sipfed.online.lync.com” in both OnPrem and Online AD. On-Prem hosted users will have either “SRV:” or a different FQDN. Would need to find a Hybrid topo to verify for sure though."

I will keep updating as I find more info.

**Comment by W1ll1amz** [comment]
Thanks for the help with this Ken. I have tried using HostingProvider as an alternative way to distinguish between SfB users hosted online and those hosted on-prem. The problem is the figures returned using Get-CsUser with the HostingProvider switch is not consistent with the number of cloud users returned using the Get-CsOnlineUser cmdlet and I need to know why. We are going to use the figures returned by the cmdlet(s) that we use to bill our clients so we need to be spot on - we cannot charge twice for the same user. These are the results I get:

(Get-CsUser -Filter {(HostingProvider -eq "sipfed.online.lync.com") -and (EnterpriseVoiceEnabled -eq $true) -and (Enabled -eq $true)} -WarningAction silentlyContinue).count
579

(Get-CsOnlineUser -Filter {(EnterpriseVoiceEnabled -eq $true) -and (Enabled -eq $true)} -WarningAction silentlyContinue).count
1,794

As you can see there is quite a difference in the user figures returned. I didn't want to have to start using ExportCsv to dump the contents and examine the differences manually but it's looking like that might be the next step.

Thanks again for your help.

Garry

**Comment by kenwith** [comment]
I am going to keep digging and see what I can find. I think it would also be worth it to open a support ticket on why the differences you are seeing are so great. You can open a ticket in your Admin page for your Online. I will keep you posted what I can find too.

**Comment by kenwith** [comment]
Quick update, the link is now forwarding correctly from TechNet to docs.microsoft.com. If you go to https://technet.microsoft.com/library/jj994026.aspx you should be redirected to the article on docs.microsoft.com.

I am still working on the behavior you are experiencing and have a number of emails out. If you make progress with support please let us know so we can add information into the cmdlet reference itself. Or you can also add and submit a Pull Request since it is open source now. But I don't mind doing it if you find information that you want to put in article.

**Comment by kenwith** [comment]
@W1ll1amz  - I got some more info from one of the developers on this team. Here it is below. I am not sure how helpful this will be but let us know if you find anything else out too from support.

It is important to note that if some are blank, that they could have the Tenant level policy applied.

We had to handle making Hybrid, Online, OnPrem users available and did so in the following manner:

- For SfB Online, in MSOnlineSession.GetHybridTenantUsers we call SkypeOnlineSession.GetHybridCsOnlineUsers using Get-CsOnlineUsers to get the following properties 
   - HostingProvider (MSOnlineSession.usersHomedDict below)

```
{ string.Empty, "SfBOnline" },
{ "sipfed.online.lync.com", "SfBHybOnline" },
{ "srv:", "SfBOnprem" },
```
   - VoicePolicy (MSOnlineSession.voicePolicyDict below, and we assume ‘Default VoicePolicy’ if null)
```
{ string.Empty, "NoVoice" },
{ "businessvoice", "VoiceOnline" },
{ "hybridvoice", "VoiceOnprem" },
```

- For Exch Online, in MSOnlineSession.GetHybridTenantUsers we call ExchangeSession.GetRecipientInfoForTUMS using Get-Recipient to get the following properties
   - PrimarySmtpAddress
   - RecipientType (MSOnline.exchangeHomedDict below, and if we don’t find the UserPrincipalName, we assign ‘NoMailbox’)

```
{ string.Empty, string.Empty },
{ "nomailbox", "NoExch" },
{ "mailuser", "ExchOnprem" },
{ "usermailbox", "ExchOnline" }, 
```
- To determine the Hybrid User Type, we then get the above values from (3) separate Dictionary calling MSOnlineSession.DetermineUserType which in turn calls MSOnlineSession.GetValueFromDict to look in the (3) dictionaries listed above.

**Comment by W1ll1amz** [comment]
Thanks for this Ken and for sticking with it. I've been working on this also and think I'm very close to cracking the problem. I dumped the contents returned by the Get-CsOnlineUser and Get-CsUser cmdlets so I can see the other types of objects returned (not all are users - Rigel/room systems, hunt groups and auto attendants will also get returned). I'm working out the switches need to exclude these non-user objects so that we get a true on-prem/online user count. Seems like hard work but once we have those cmdlets it will be smooth sailing as an ongoing monthly task. I'll post the full cmdlets here once I'm done.

Thanks again.

**Comment by W1ll1amz** [comment]
Hi Ken,

I can filter out things like AutoAttendants, Hunt Groups and Rigel (Lync Room Systems) by using $_.ownerUrn –eq $null. There are other interesting online user attributes as well that might be even more useful to allow me to ID 'real' users but I cannot find any documentation on them.  "OptionFlags" looks decent.

There is [OCS documentation](https://technet.microsoft.com/en-us/library/bb663647(v=office.12).aspx#msRTCSIP-OptionFlags) but the flags have evolved a long way since then. I see values 384, 131456, 131457, 164224, 164225 and those are not documented for OCS.

"NonPrimaryResource" looks interesting. About two thirds of our users are set to TRUE and a third FALSE.

Any info on those might help crack the case.

Thanks,
Garry

**Comment by kenwith** [comment]
This thread is producing great information. I will try to track this down and once we crack this one we can work together to get this into the docs in this repository. Thanks for all your work on this. I will post back as I get more info.

**Comment by kenwith** [comment]
@W1ll1amz - I haven't made any progress on this one. What are your thoughts? Should we keep searching or do you have a solution?

**Comment by W1ll1amz** [comment]
Hi Ken,

I hope you're ready for this, as I've been busy! (*draws breath*):

Results for Client #1
---------------------
1. EV Users Homed in SfBO

I use:

(Get-CsOnlineUser -Resultsize Unlimited -WarningAction silentlyContinue | Where-Object {($_.EnterpriseVoiceEnabled  -eq $true –or $_.OnPremEnterpriseVoiceEnabled -eq $true) -and ($_.HostingProvider -match “sipfed.online.lync.com” -or $_.OnPremHostingProvider -match “sipfed.online.lync.com”) -and $_.Enabled -eq $true}).count

I then compared the figure that this returned with the output from the following on-premises cmdlet...

(Get-CsUser -Resultsize Unlimited -WarningAction silentlyContinue | Where-Object {$_.EnterpriseVoiceEnabled -eq $true -and $_.HostingProvider -match “sipfed.online.lync.com” -and $_.Enabled -eq $true}).count

... there are two discrepencies between the two figures (A includes accounts that B does not have and vice-versa). The good news is, they can be explained:

The Get-CsOnlineUser cmdlet includes Hunt Group and Auto Attendant objects and these don't exist on-prem. You can optionally exclude these by using the following additional filter in the first cmdlet above:

-and $_.OnPremOptionFlags -ne "384"

The second discrepancy occurs if the client disables user AD accounts without disabling the account in SfB first. Because the cmdlets above only operate on *SfB* enablement (not AD enablement) we can't avoid picking up AD-disabled accounts with Get-CsUser. It's bad administrative practice really on behalf of the client but it is what it is. I guess DirSync must be configured not to replicate AD-disabled accounts to the cloud because they do not appear in the Get-CsOnlineUser results.

Bottom line: we can use the Get-CsOnlineUser cmdlet above to report on EV-enabled users hosted in 365 for this client.

2. EV Users Homed On-Prem

For this we just change the HostingProvider value that we look for from "sipfed" to "SRV:":

(Get-CsOnlineUser -Resultsize Unlimited -WarningAction silentlyContinue | Where-Object {($_.EnterpriseVoiceEnabled  -eq $true –or $_.OnPremEnterpriseVoiceEnabled -eq $true) -and ($_.HostingProvider -match “SRV:” -or $_.OnPremHostingProvider -match "SRV:") -and $_.Enabled -eq $true}).count

And on-premises:

(Get-CsUser -Resultsize Unlimited -WarningAction silentlyContinue | Where-Object {$_.EnterpriseVoiceEnabled -eq $true -and $_.HostingProvider -match “SRV:” -and $_.Enabled -eq $true}).count

This client has a discrepancy in the results returned by the two cmdlets and again it is caused by some accounts being AD-disabled on-premises. Once again though we can just use Get-CsOnlineuser with confidence as we don't want to include AD-disabled users in our results.

3. Non-EV Users homed in SfBO

We flip EnterpriseVoiceEnabled and OnPremEnterpriseVoiceEnabled to $false:

(Get-CsOnlineUser -Resultsize Unlimited -WarningAction silentlyContinue | Where-Object {($_.EnterpriseVoiceEnabled  -eq $false –and $_.OnPremEnterpriseVoiceEnabled -eq $false) -and ($_.HostingProvider -match “sipfed.online.lync.com” -or $_.OnPremHostingProvider -match “sipfed.online.lync.com”) -and $_.Enabled -eq $true}).count

On-premises:

(Get-CsUser -Resultsize Unlimited -WarningAction silentlyContinue | Where-Object {$_.EnterpriseVoiceEnabled -eq $false -and $_.HostingProvider -match “sipfed.online.lync.com” -and $_.Enabled -eq $true}).count

There are 2 discrepancies in the results returned: Get-CsUser cannot see cloud-only objects (those created in the cloud that do not get replicate to the on-prem environment by DirSync), so these can only be counted using Get-CsOnlineUser. Makes sense.

The second discrepancy comes about because Get-CsUser cannot filter out users that have a (cloud) EV-enabled value set to $true but an (on-prem) EV-enabled value of $false. This comes about because on-premises there is only one parameter for "EV-Enabled" (whereas cloud distinguishes has between "EVEnabled" and "OnPremEvEnabled"). Because of this, 524 additional accounts are returned by the Get-CsUser cmdlet for this client: these are (cloud) EV-enabled and we do not want these in this set of results. For this reason only Get-CsOnlineUser returns the desired results, but that is OK so long as we know to only use that cmdlet.

4. Non-EV Users homed On-Prem

(Get-CsOnlineUser -Resultsize Unlimited -WarningAction silentlyContinue | Where-Object {($_.EnterpriseVoiceEnabled  -eq $false –and $_.OnPremEnterpriseVoiceEnabled -eq $false) -and ($_.HostingProvider -match “SRV:” -or $_.OnPremHostingProvider -match “SRV:”) -and $_.Enabled -eq $true}).count

(Get-CsUser -Resultsize Unlimited -WarningAction silentlyContinue | Where-Object {$_.EnterpriseVoiceEnabled -eq $false -and $_.HostingProvider -match “SRV:” -and $_.Enabled -eq $true}).count

For this client, these cmdlets return the same results - there are no discrepancies.

When I got to this point I was happy as I'd examined the data in detail to understand why discrepancies were occurring so had confidence in the user counts returned. However, the fun started when I tried to apply these findings to a different client environment. The problems I encountered were that client #2 also had discrepancies in their user figures returned (between get-CsOnlineUser and Get-CsUser). However, the causes for the discrepancies were different.

Client #2

For this client, Get-CsOnlineUser returned hundreds of accounts that were not counted by Get-CsUser. The reason is because this client administers their accounts differently to Client #1: Most of the time, Client #1 disables accounts in SfB when a user leaves the company (they occassionally make a mistake and only AD-disable the user). However, Client #2 seems to just remove the user's O365 license when the user leaves. This somewhat invalidates the way in which I have been counting users using the cmdlets above. The reason for this is that when you remove a user's SfB Online license, the user's SfB Online "Enabled" state will be switched to $false. That's great, but if this is a hybrid user account (subject to DirSync) then on-premises their account will still show be flagged as "Enabled" in SfB (because the license change does not replicate back to the on-premises environment). These discrepancies are in the hundreds. It's OK in that Get-CsOnlineUser still returns the desired user count. However, I found some smaller discrepancies e.g. Get-CsOnlineUser excluding accounts that were included by Get-CsUser because the accounts had a "soft deletion" flag that had been set.

So what to conclude from all of this?

a) it seems to be way more complicated than it should be to report user figures for on-prem/hybrid/online users with full confidence (i.e. no overlap).
b) the cmdlets that I've come up with are "OK" but I don't have 100% confidence in them because going forward because it required a detailed data analysis/validation exercise that I cannot afford to do each time I report (just in case somethign has changed).
c) if the client changes their administrative practices it might influence the returned results.

Any comment on the above would be appreciated.

One user account property that I have not been leveraging (and perhaps should) is "InterpretedUserType". I have come across the following values for this attribute:

PureOnline
DirSyncedPureOnline
HybridOnPrem
HybridOnline
NoService
PureOnlineUnlicensed
HybridOnlineUnlicensed

... there may well be others. This field seems to be an aggregated value that reports the user state to stop you having to consider the permutations of other attributes. Are you able to find the full list of values for "InterpretedUserType" and a description of each? In the olden days we'd have documentation for these fields...

Many thanks,
Garry

**Comment by kenwith** [comment]
@W1ll1amz - One of the devs was super helpful as I was talking through this. 

Here is what the dev said:

The code looks good and the only thing missing was ‘_’ between the ‘$’ and ‘.’.  I have corrected ‘$_.<Property>’ and reformatted below (PowerShell file also available, just need to rename as .ps1 file):

                # 1) EV Users Homed in SfBO

# SfB Online
(Get-CsOnlineUser -Resultsize Unlimited -WarningAction silentlyContinue `
    | Where-Object {
        ($_.EnterpriseVoiceEnabled  -eq $true –or $_.OnPremEnterpriseVoiceEnabled -eq $true) `
        -and ($_.HostingProvider -match “sipfed.online.lync.com” -or $_.OnPremHostingProvider -match “sipfed.online.lync.com”) `
        -and $_.Enabled -eq $true
    }).count

# SfB OnPrem
(Get-CsUser -Resultsize Unlimited -WarningAction silentlyContinue `
    | Where-Object {
        $_.EnterpriseVoiceEnabled -eq $true -and $_.HostingProvider -match “sipfed.online.lync.com” -and $_.Enabled -eq $true
    }).count

# 2) EV Users Homed On-Prem

# SfB Online
(Get-CsOnlineUser -Resultsize Unlimited -WarningAction silentlyContinue `
    | Where-Object {
        ($_.EnterpriseVoiceEnabled  -eq $true –or $_.OnPremEnterpriseVoiceEnabled -eq $true) `
        -and ($_.HostingProvider -match “SRV:” -or $_.OnPremHostingProvider -match "SRV:") `
        -and $_.Enabled -eq $true
    }).count

# SfB OnPrem
(Get-CsUser -Resultsize Unlimited -WarningAction silentlyContinue `
    | Where-Object {
        $_.EnterpriseVoiceEnabled -eq $true `
        -and $_.HostingProvider -match “SRV:” `
        -and $_.Enabled -eq $true
    }).count

# 3) Non-EV Users homed in SfBO

# SfB Online
(Get-CsOnlineUser -Resultsize Unlimited -WarningAction silentlyContinue `
    | Where-Object {($_.EnterpriseVoiceEnabled  -eq $false –and $_.OnPremEnterpriseVoiceEnabled -eq $false) `
        -and ($_.HostingProvider -match “sipfed.online.lync.com” -or $_.OnPremHostingProvider -match “sipfed.online.lync.com”) `
        -and $_.Enabled -eq $true
    }).count

# SfB OnPrem
(Get-CsUser -Resultsize Unlimited -WarningAction silentlyContinue `
    | Where-Object {$_.EnterpriseVoiceEnabled -eq $false `
        -and $_.HostingProvider -match “sipfed.online.lync.com” `
        -and $_.Enabled -eq $true
    }).count


# 4) Non-EV Users homed On-Prem

(Get-CsOnlineUser -Resultsize Unlimited -WarningAction silentlyContinue `
    | Where-Object {
        ($_.EnterpriseVoiceEnabled  -eq $false –and $_.OnPremEnterpriseVoiceEnabled -eq $false) `
        -and ($_.HostingProvider -match “SRV:” -or $_.OnPremHostingProvider -match “SRV:”) `
        -and $_.Enabled -eq $true
    }).count


(Get-CsUser -Resultsize Unlimited -WarningAction silentlyContinue `
    | Where-Object {
        $.EnterpriseVoiceEnabled -eq $false `
        -and $_.HostingProvider -match “SRV:” `
        -and $_.Enabled -eq $true
    }).count

**Comment by kenwith** [comment]
I am going to close this one out and work on how I can incorporate this super valuable information into the docs. You deserve an award for your knowledge of this product @W1ll1amz !
