### ISSUE TITLE
Duplicate block of parameter

### ISSUE THREAD

**Issue by aavdberg** [MicrosoftDocs/office-docs-powershell#1628]
There is 3 times a parameter block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 316bada1-dbc7-f07a-4afa-d67330edef50
* Version Independent ID: d9380f67-a05a-ddd0-425c-af7023222c69
* Content: [New-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/new-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/New-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/New-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@aavdberg I realize it's a lot like playing "Where's Waldo?", but if you look closely, there _should_ be at least one parameter difference between the blocks. For example, in your PR #1630, Set3 contains the SubscriptionEnabled parameter that isn't in Set2. And Set1 contains the MailboxRegion parameter that isn't available in the other two. Really, the presence or absence of multiple Syntax blocks (parameter sets) is determined by code, and shouldn't be manually modified unless multiple sets are absolutely identical in every way.

I took the liberty of running the updated version of [platyPS](https://github.com/PowerShell/platyPS) in Exchange Online to re-dump the New-UnifiedGroup cmdlet, which gave meaningful names to the parameter sets, which I used to update the topic. And, I closed your pull request #1630, which was sitting in limbo because you need to sign the Contributor License Agreement.

Thanks for the feedback.
