### ISSUE TITLE
-AllowConflicts minor edit

### ISSUE THREAD

**Issue by SCS-sysadmin** [MicrosoftDocs/office-docs-powershell#1654]
-AllowConflicts states the default value as none, when it should be "false"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a9c45b-34dd-c1c8-89f0-84f3d968eac4
* Version Independent ID: ec9c910c-25f2-f36a-8f75-ce052f0e8be6
* Content: [Set-CalendarProcessing (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-calendarprocessing?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SCS-sysadmin, I hear what you're saying. The "Default value" property says None, but the actual description says: "The AllowConflicts parameter specifies whether to allow conflicting meeting requests. Valid input for this parameter is $true or $false. The default value is $false."

Apparently, that "Default value" property is never _automatically_ populated correctly; it's a Windows PowerShell thing that affects any tool (like platyPS or our old internal reflection system) that generates cmdlet reference topics from product code or the current PS session. Any accurate "Default value" values in Exchange, SharePoint, or Skype cmdlet reference topics were manually configured in the topic by a human. But since you brought it up, I'll fix it.

Thanks for the feedback.

**Comment by SCS-sysadmin** [comment]
Great, thanks!
