### ISSUE TITLE
Certificate error after installing through Install-Module -Name Microsoft.Online.SharePoint.PowerShell

### ISSUE THREAD

**Issue by echetto** [MicrosoftDocs/office-docs-powershell#1685]
When trying to load the module, it gives a certificate error:

PS C:\Windows\system32> import-module Microsoft.Online.SharePoint.PowerShell
import-module : Errors occurred while loading the format data file:
C:\Program Files\WindowsPowerShell\Modules\Microsoft.Online.SharePoint.PowerShell\16.0.8029.0\Microsoft.Online.SharePoi
nt.PowerShell.ps1xml, , C:\Program Files\WindowsPowerShell\Modules\Microsoft.Online.SharePoint.PowerShell\16.0.8029.0\M
icrosoft.Online.SharePoint.PowerShell.ps1xml: The file was skipped because of the following validation exception: File
C:\Program Files\WindowsPowerShell\Modules\Microsoft.Online.SharePoint.PowerShell\16.0.8029.0\Microsoft.Online.SharePoi
nt.PowerShell.ps1xml cannot be loaded. A certificate chain processed, but terminated in a root certificate which is
not trusted by the trust provider..
At line:1 char:1
+ import-module Microsoft.Online.SharePoint.PowerShell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

Attaching is the certificate path
![certificate-info](https://user-images.githubusercontent.com/2735127/44990574-cbc55680-af67-11e8-9a20-3f534a587427.png)

**Comment by echetto** [comment]
I've installed in a Win10 computer after reading this announcement https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/Announcing-availability-of-SharePoint-Online-Management-Shell/ba-p/241370

**Comment by AndreaBarr** [comment]
@echetto Thank you for this feedback

I want to make sure this issue is addressed properly. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
