### ISSUE TITLE
Add PowerShell solution to manage Out-of-office Rules for Exchange

### ISSUE THREAD

**Issue by bingoglossy** [MicrosoftDocs/office-docs-powershell#1708]
There needs to be a way, via PowerShell, to get all recipients that have a forward (among other things...) set via the Out of Office/automatic reply route. Currently there is no known way to view this and it's a security concern as an admin needs to be able to quickly identify ALL forwards set in a tenant, and this is a MAJOR blind spot. Solutions exist to find Inbox Rules and others, but none for Out of Office.

If you know of a way, please correct me. I've already asked on the Microsoft Online Services TechCenter:

https://social.technet.microsoft.com/Forums/msonline/en-US/642d571f-2f1a-4fc4-bb84-5dd86df7dee6/outlook-automatic-replies-forwarding-rule-where-does-it-live-and-how-do-i-find-it-with-powershell?forum=onlineservicesexchange

which includes a link to a UserVoice feature request.

Thanks much!

**Comment by AndreaBarr** [comment]
@bingoglossy Thank you for this feedback

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by bingoglossy** [comment]
AndreaBarr, what's the status of this please? Thank you!

**Comment by AndreaBarr** [comment]
@chrisda Could you give us an update?

**Comment by kenwith** [comment]
@bingoglossy - thanks for taking the time to bring this issue up with the docs team. Sorry for the confusion. The 'backlog' referred above is the writing teams backlog. What we were doing is creating the 'issue' in an internal backlog and closing it here. However, this was leading to a lot of confusion as you have experienced. So now we are keeping the issues open in GitHub until we figure out a resolution. This will avoid confusion in the future.

Regarding this particular issue, the thread was referring to the 'backlog' of the writing team, not the product team. When I look at the issue in the backlog of the writing team it has been closed already since, as you already discovered and put in the issue, it doesn't seem to be possible with the current product.

When you opened a support ticket a service engineer will escalate the information to the product team so that your request is something they are aware of. My understanding is they would need to add a feature or capability to the Exchange PowerShell modules. To get an update on the status of if they will be able to add that functionality to the Exchange PowerShell module the best method is to query against the service ticket you have open with support.

I know this is confusing and I ask for your patience. This system of having the content as open source is brand new and unfortunately you got caught in a gap when we used the term 'backlog'. Again, I was referring the writing teams backlog for things to address in the content and I realize now it was really confusing.

I hope that helps and I do agree with you on the need for admins to be able to query on all forwards, IE out of office. You can include my Microsoft email (on my profile in GitHub) and I can help explain the need as well as you are working with support as they escalate to the product team.

**Comment by bingoglossy** [comment]
Is there anybody OUT THERE?

**Comment by yogkumgit** [comment]
@bingoglossy I hope detailed explanation given by @kenwith is helpful for you.  as you know this Tenant specifically is to improve the documentation. For new fatures and support I request you to follow speperately as per the previous comments.
