### ISSUE TITLE
Set-PnPSearchConfiguration is not working with tenant scope

### ISSUE THREAD

**Issue by SemionKovaliov** [MicrosoftDocs/office-docs-powershell#1757]
When i'm trying to apply search schema with:
    Set-PnPSearchConfiguration -Path $searchSchemaPath -Scope Subscription
it fails with "Unknown error". I've checked my current context and URL of current context contains "-admin", so it should run provisioning but it just fails no matter what xml schema contains even it without any settings.

**Comment by AndreaBarr** [comment]
@SemionKovaliov Thank you for this feedback

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  
 
Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
