### ISSUE TITLE
Error: Cannot process argument transformation on parameter 'Mailbox'.

### ISSUE THREAD

**Issue by uz-it** [MicrosoftDocs/office-docs-powershell#1763]
Regarding the 
Manu Meng
TechNet Community Support
in this tread: 
https://social.technet.microsoft.com/Forums/office/en-US/bcb0d3ee-645e-4094-b8cf-f5e53263c6d7/exchange-2016-cu7-mailbox-export-broken?forum=Exch2016PS

The Command returns an error if you provide not a Mailbox.Alias in the -Mailbox parameter

For example:
$mbx = Get-Mailbox -Identity blabla@domain.com
New-MailboxExportRequest -Mailbox $mbx.GUID etc...
Cannot process argument transformation on parameter 'Mailbox'. Cannot convert the "3be24c07-6f3d-4f90-b506-c69508776ade" value of type "System.Guid" to type "Microsoft.Exchange.Configuration.Tasks.MailboxLocationIdParameter".
    + CategoryInfo          : InvalidData: (:) [New-MailboxExportRequest], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-MailboxExportRequest
    + PSComputerName        : servername01.intern.domain.local

Exchange server 2016 CU9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fab79912-3075-a8be-fc9f-01d0c28c6423
* Version Independent ID: 5bd0b2f9-c51c-74cd-6ac1-3134fde6bf59
* Content: [New-MailboxExportRequest (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/new-mailboxexportrequest?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/New-MailboxExportRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/New-MailboxExportRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@uz-it, this turned out to be a rather complex issue to document.

In Exchange 2010, Exchange 2013, and (according to the support thread) CU6 and earlier, the Type value for the Mailbox parameter is MailboxOrMailUserIdParameter (I confirmed this in 2010 and 2013). But currently in Exchange 2016 and Exchange 2019, the Mailbox parameter is now of Type MailboxLocationIdParameter (I confirmed this).

Get-MailboxLocation is a strange cmdlet. It's currently tagged as Exchange Online only, yet it's available to me in Exchange 2016 CU10 and Exchange 2019. Its Identity parameter is also of Type MailboxLocationIdParameter, but it isn't positional, so you have to include -Identity or it will error. In looking at its output, it would seem to only take the following values:

- ExchangeGuid value of the mailbox (not the GUID value of the mailbox; appears as MailboxGuid in the output).

- \<TenantGuid\>\\\<MailboxGuid\> (values appear separately in the output or unified in the Id property).

- CanonicalDN (contoso.com/Users/Administrator; appears as OwnerId in the output).

But, it would seem any mailbox unique identifier value works as long as you also use -Identity. So, why the Mailbox parameter with the same MailboxLocationIdParameter type would prefer Alias over other identity values is rather mystifying.

Furthermore, the Mailbox parameter is also used in the these other \*-Mailbox\*Request cmdlets:

- Get-MailboxImportRequest

- Get-MailboxExportRequest

- New-MailboxImportRequest

In all cmdlet topics, I updated the Syntax blocks and the parameter descriptions to indicate the different parameter Type values, and I modified the text in the Mailbox parameter description (E16 CU6 and earlier, use any unique mailbox identifier; E16 CU7 and later, use Alias).

Thanks for the feedback.
