### ISSUE TITLE
Remove a digit?

### ISSUE THREAD

**Issue by dbetlow** [MicrosoftDocs/office-docs-powershell#1765]
The missed calls and voicemail emails from Office 365 have an extra 1 for international calls.  We've submitted a ticket with Support to try and get the email changed, but in the meantime, is there a way to detect numbers based on the +1011 pattern and replace with +011?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 940f3a9e-f4cb-4c60-c57a-3d064e79677a
* Version Independent ID: 52842215-3cd7-c8c8-6556-d166a92a7b48
* Content: [New-CsVoiceNormalizationRule (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csvoicenormalizationrule?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsVoiceNormalizationRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsVoiceNormalizationRule.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@dbetlow Thank you for this feedback

I am not sure on the answer for this. The best place to get this answered would be Support. I apologize for sending you back to them since it sounds like you were already there but I want to make sure you get a solution and support will be able to handle any solution. 


Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
