### ISSUE TITLE
Output links to Exchange powershell cmdlets

### ISSUE THREAD

**Issue by Angel-Alva** [MicrosoftDocs/office-docs-powershell#1766]
Output links to Exchange Powershell cmdlets not Security and Compliance PS cmdlets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cda1a8f-7939-0a8e-ec4b-c9e3e0b50cb2
* Version Independent ID: d96a3170-b04a-ebc4-844e-a0aee5b6ccf3
* Content: [Get-DlpCompliancePolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/get-dlpcompliancepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Angel-Alva currently, all Exchange-related cmdlet topics are grouped together under 'Exchange PowerShell'. We're working on the ability to select and filter topics based on version: Exchange 2010, Exchange 2013, Exchange 2016, Exchange 2019, Exchange Online, Office 365  Security & Compliance Center and Exchange Online Protection. Because of the hundreds of shared cmdlets between the environments, we need to implement these filters in a new way, so it's taking longer than we expected. But it is coming; it's just a question of when.

Thanks for the feedback.
