### ISSUE TITLE
The moniker for exchange powershell does not work and could not be indexed in module browser

### ISSUE THREAD

**Issue by EdisonDa** [MicrosoftDocs/office-docs-powershell#1777]
This was copied from https://github.com/MicrosoftDocs/feedback/issues/708#issuecomment-424768144

Please add the following PowerShell modules to the PowerShell Module browser:
https://docs.microsoft.com/en-us/powershell/module/
Exchange Server PowerShell
Exchange Online PowerShell
Office 365 Security & Compliance Center PowerShell
Exchange Online Protection PowerShell

@dstrome , I know you are working on this, do you suggest me to deactivate the moniker at this moment?

**Comment by kenwith** [comment]
@AndreaBarr - please create a backlog item for this one and we will get this on the backlog.

**Comment by kenwith** [comment]
@EdisonDa - just a back story info for you too. The reason Exchange is not listed in the browser right now is that Chris and David are trying to add a rich functionality where you can select the Exchange version from articles. That is what the term 'moniker' is in regards to. It is not clear if that will work though and we are trying to figure it out before we add Exchange to PowerShell Module browser since there will be a connection between how the browser and the monikers work together. That's the back story. I know it is being worked on. Thanks for feedback. It is much appreciated!

**Comment by AndreaBarr** [comment]
@EdisonDa @kenwith I got this added to the backlog
