### ISSUE TITLE
Set-PnPTenantSite does not work with MFA

### ISSUE THREAD

**Issue by nikolayyordanov** [MicrosoftDocs/office-docs-powershell#1778]
When Multi-Factor authentication is enabled Set-PnPTenantSite gives error  403.

**Comment by AndreaBarr** [comment]
@nikolayyordanov Thank you for this feedback

I want to make sure this gets addressed properly. 
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  
 
Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
