### ISSUE TITLE
FieldOptions not adding to all content types

### ISSUE THREAD

**Issue by wonderplayer** [MicrosoftDocs/office-docs-powershell#1782]
Hello,

None of these commands add field to all content types, only to default:

Add-PnPTaxonomyField -List $sitePagesList -DisplayName "Categories4" -InternalName "Categories4" -TermSetPath $categoriesTermSetPath -MultiValue -FieldOptions AddToAllContentTypes

Add-PnPTaxonomyField -List $sitePagesList -DisplayName $dName -InternalName $iName -TermSetPath $categoriesTermSetPath -MultiValue -FieldOptions 63 -AddToDefaultView

Add-PnPTaxonomyField -List $sitePagesList -DisplayName $dName -InternalName $iName -TermSetPath $categoriesTermSetPath -MultiValue -FieldOptions 63 -AddToDefaultView

SharePointPnPPowershellOnline version - 3.1.1809.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2690c5-d59a-fe9c-2810-3a8141096d36
* Version Independent ID: edbc02e9-96ac-ee9b-0a3d-c115d7c38745
* Content: [Add-PnPTaxonomyField (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnptaxonomyfield?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTaxonomyField.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTaxonomyField.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@wonderplayer Thank you for this feedback

I want to make sure this gets addressed properly. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  
 
Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
