### ISSUE TITLE
MFA?

### ISSUE THREAD

**Issue by Shuwi75** [MicrosoftDocs/office-docs-powershell#1783]
What about multi factor authentication for SPO connection..?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 176873a5-a509-6337-0aa9-7db8ead2e863
* Version Independent ID: 73bb0f00-1909-6eb1-3a8c-247149480c9a
* Content: [Register-SPMTMigration (spmt)](https://docs.microsoft.com/en-us/powershell/module/spmt/register-spmtmigration?view=spmt-ps)
* Content Source: [spmt/spmt-ps/spmt/Register-SPMTMigration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/spmt/spmt-ps/spmt/Register-SPMTMigration.md)
* Service: **spmt-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@Shuwi75 I am not sure what your question is. What are you trying to find out about MFA for SPO?

**Comment by zvoltejinylogin** [comment]
Hello, please reopen this issue, what options are here for authentication when we have MFA authentication enabled on our tennant? I am getting errors while trying to utilize SMPT via powershell, the registration fails and I see Microsoft.IdentityModel.Clients.ActiveDirectory.AdalClaimChallengeException: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'guid ID'.

**Comment by kenwith** [comment]
@yogkumgit - on this one you can ask reach out to @JoanneHendrickson who has contacts on the product team that owns this migration tool. Let's make sure to capture any findings in the article from the question of @zvoltejinylogin has so that others get the answer resolved too. Thanks for taking the time to improve the documentation. It is very much appreciated.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by zvoltejinylogin** [comment]
Well, to give an update on this. If you are using MFA auth on your tenant and you wish to use the powershell commands for SPMT then you should use - Register-SPMTMigration without the "-SPOCredential" switch, then you will be prompted to authenticate against your azure/tenant and script will start. I've been informed that there is some kind of a bug in Azure Auth for this kind of stuff, and it wasreported to MS a few weeks ago, so well hang on...

**Comment by JoanneHendrickson** [comment]
Thank you for bringing this issue up;I am updating the article now. MFA can only be supported by an interactive UX. Will let you know when it goes live

Joanne

**Comment by yogkumgit** [comment]
#4381
