### ISSUE TITLE
Switches for Regional Settings

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/office-docs-powershell#1788]
Is there any plan to add additional switches to the New-PnPSite and/or Set-PnPSite commands? I could really use an option for setting the region. I realize there are site templates and PnP provisioning, but I don't have the time to invest in that at the moment. 

https://COMPANY.sharepoint.com/sites/SITENAME/_layouts/15/regionalsetng.aspx

**Comment by AndreaBarr** [comment]
@robertcaretta Thank you for this feedback

I want to make sure this question gets addressed properly. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  
 
Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
