### ISSUE TITLE
only displays 2013 platform workflows?

### ISSUE THREAD

**Issue by jjinatlanta** [MicrosoftDocs/office-docs-powershell#1822]
I can't get this to display workflows based on the 2010 workflow platform - if that is intentional, it should be documented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90616400-a52d-46ca-fc46-d33208198aae
* Version Independent ID: 434b2697-667f-cc60-f858-d406fbb6eced
* Content: [Get-PnPWorkflowDefinition (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpworkflowdefinition?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWorkflowDefinition.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWorkflowDefinition.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@jjinatlanta Thank you for this feedback

I want to make sure this gets the appropriate attention so that you can get the answers you are seeking. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  
 
Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
