### ISSUE TITLE
Get-PnPAvailableApp?

### ISSUE THREAD

**Issue by amac44** [MicrosoftDocs/office-docs-powershell#1828]
The cmdlet Get-PnPAvailableApp used in Examples 3 and 4 does not seem to exist. Was this replaced by Get-PnPApp ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a35e307-24b0-6bd3-f60d-62a253bd973f
* Version Independent ID: 17b2e303-31bd-2ed9-48ca-2fc3c82e66bb
* Content: [Install-PnPApp (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/install-pnpapp?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Install-PnPApp.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Install-PnPApp.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@amac44 Thank you for this feedback

I want to make sure your inquiry gets the appropriate attention. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  
 
Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
