### ISSUE TITLE
There is a typo using -Identity ?

### ISSUE THREAD

**Issue by PedroMordeP** [MicrosoftDocs/office-docs-powershell#1834]
Publish-PnPApp -Identity -Identity 2646ccc3-6a2b-46ef-9273-81411cbbb60f

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb85078-84d3-dc5a-f0e7-949823c45639
* Version Independent ID: 7722b6d6-eff6-bfb3-7ff4-d46acd12f7ac
* Content: [Publish-PnPApp (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/publish-pnpapp?view=sharepoint-ps#related-links)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Publish-PnPApp.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Publish-PnPApp.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@PedroMordeP Thank you for this feedback

I have submitted a pull request to fix the double -Identity peramater. I'm now just waiting on approval to merge the pull request. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by VesaJuvonen** [comment]
thx @PedroMordeP for reporting. As PnP PowerShell documentation is auto-generated from the source code, we have now updated the documentation in the md file and also in the source code at following location, so that this issue is permanently fixed - https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Apps/PublishApp.cs. Thanks for reporting. Appreciated.
