### ISSUE TITLE
Doesn't work with 2FA / MFA

### ISSUE THREAD

**Issue by nidelius** [MicrosoftDocs/office-docs-powershell#1872]
This method does not work with 2FA sms authenticated account....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@nidelius see the MFA specific instructions here: https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell

**Comment by blouwagie** [comment]
PLEASE add these instructions inside the document itself, not just in the comment

**Comment by VNJoe** [comment]
There is NO WAY to use these instructions any more, so UPDATE THIS document.  These DO NOT WORK, because you HAVE to be an admin and that means 2FA

**Comment by chrisda** [comment]
@VNJoe, this topic never worked with MFA, and we never said it worked with MFA. If you're using MFA, you need to use the instructions/module in https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell or https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.

We call this out very clearly at the top of the topic.

**Comment by VNJoe** [comment]
AGAIN, you MUST use MFA if you're an admin, and the link above is where the Partner Center documentation redirects everyone to, so it's really critical that Microsoft clean this up.

Joe Cimino
CTO, VitalNetix
267 282-5400

________________________________

**Comment by chrisda** [comment]
@VNJoe, are you able to update or suggest updates to the Partner Center docs? If so, they should be linking to https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2 for how to connect to Exchange Online PowerShell.

That's the best and most future-proof link (works with or without MFA).

**Comment by VNJoe** [comment]
No, I'm not.  I'm not a Microsoft employee.  I don't believe anyone DOESN'T need the new method who's a partner, as we all need MFA.  But they're saying it's called out at the top of the document, when really, the old way is (or should be) deprecated, I think? No partner doesn't need Powershell for Exchange, and no partner doesn't need to have MFA enabled, so if its a Partner Center doc....

**Comment by chrisda** [comment]
@VNJoe, let's take a step back. I want to help fix the issue.

- I've asked around an no one seems to know the whereabouts of the offending "Partner Center" doc that contains the non-MFA connection instructions link that you mentioned. If you have access to the doc, you're one up on me, and I thought you might be able to edit it or at least suggest changes to it. I wan't trying to imply that you were a Microsoft employee. I would ask for the link to the topic here, but I probably can't access it, anyway, so I'm not going to ask..

- It sounds like the best fix for that offending topic is to replace the bad link with [EXO V2 module link](https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2). That will 100% work for everyone using MFA.

- If/when the old method of connecting to ExO PowerShell goes away, then the topic will go away. Until then, it stays. We already have a big "doesn't work for MFA" call-out and link at the top, so that's the best we can do for now.
