### ISSUE TITLE
No links or descriptions for Security & Compliance cmdlets

### ISSUE THREAD

**Issue by andyschan** [MicrosoftDocs/office-docs-powershell#1892]
The articles outline how to connect to Security & Compliance PowerShell, but have no references or links on what the cmdlets are, and how to use them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54add98f-f5f7-74fe-7043-f55fc3699115
* Version Independent ID: c020556e-75d3-8d8b-00f2-5c1008b09c6e
* Content: [Office 365 Security & Compliance Center PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/office-365-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/office-365-scc/office-365-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/office-365-scc/office-365-scc-powershell.md)
* Service: **o365-security-and-compliance**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@andyschan It looks like nandelite updated the article. Did this resolve your issue?

**Comment by Tuxhedoh** [comment]
@AndreaBarr I don't think so.

**Comment by AndreaBarr** [comment]
@andyschan Thank you for checking to see if that update fixed your issue. I will get this over to the PowerShell team so we can get this investigated. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
I updated the https://docs.microsoft.com/en-us/office365/securitycompliance/labels#find-the-powershell-cmdlets-for-labels with direct links to the appropriate cmdlet reference topics.

Since the migration from TechNet to docs.microsoft.com, there is no Security & Compliance Center Cmdlet topic. The cmdlets are all under Reference and they're all munged together. We're working on a way to selectively filter the list of cmdlets by type (Exchange Server 2010 through 2019, Exchange Online, Exchange Online Protection, or Security & Compliance Center). It's taking much longer than we anticipated, but the plumbing is all in-place.
