### ISSUE TITLE
Description is wrong 

### ISSUE THREAD

**Issue by CloudHotShot** [MicrosoftDocs/office-docs-powershell#1899]
Description is wrong 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d853c49-1c50-5015-1e89-497fd05b7550
* Version Independent ID: 4345f7ab-f96c-3695-c386-3567bfe84c83
* Content: [Unregister-PnPHubSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/Unregister-PnPHubSite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Unregister-PnPHubSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Unregister-PnPHubSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@CloudHotShot Thank you for this feedback


We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  
 
Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
