### ISSUE TITLE
Error: Managed Metadata (multiple values with paths to terms) 

### ISSUE THREAD

**Issue by ErnstWolthaus** [MicrosoftDocs/office-docs-powershell#1903]
Where it says:
Managed Metadata (multiple values with paths to terms): -Values @{"MetadataField" = ("CORPORATE|DEPARTMENTS|FINANCE","CORPORATE|DEPARTMENTS|HR")}

it should say:

Managed Metadata (multiple values with paths to terms): -Values @{"MetadataField" = @("CORPORATE|DEPARTMENTS|FINANCE","CORPORATE|DEPARTMENTS|HR")}

You need to add the @ in front of the (term,term) because it's a PowerShell array.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362042ec-76bf-6da1-4551-a8baa7a26d27
* Version Independent ID: f30dd9c9-c9fc-f3f9-d5f4-ee4e1b8d3f53
* Content: [Set-PnPListItem (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItem.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@ErnstWolthaus Thank you for this feedback

I want to make sure we get the correct eyes on this. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  
 
Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.

**Comment by bobchauvin** [comment]
The following works, without the added @ sign, so not sure this is a bug. But it would break my code if it was added as a requirement.
$yourTerms="aa3a6aec-1a56-4262-9d03-e2776045ebe9,61a2ca23-a851-42b4-8987-39d51f645b7c,Path|to|some|term"
-Values @{"yourmetadatafield"=($yourTerms -split ",")
