### ISSUE TITLE
This command is probably not required, when working with ".app" (Add-in) model

### ISSUE THREAD

**Issue by ppatalong** [MicrosoftDocs/office-docs-powershell#1917]
This step is command not required, when working with ".app" (Add-in) model. It will throw error when called, see more:
https://github.com/SharePoint/PnP-PowerShell/issues/1296
It seems that it isn't required to Publish old add-in model apps (need confirmation from one of devs). If so, I would recommend updating documentation, so nobody will wonder :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb85078-84d3-dc5a-f0e7-949823c45639
* Version Independent ID: 7722b6d6-eff6-bfb3-7ff4-d46acd12f7ac
* Content: [Publish-PnPApp (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/publish-pnpapp?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Publish-PnPApp.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Publish-PnPApp.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@ppatalong Thank you for this feedback

I want to make sure that this gets the appropriate attention. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  
 
Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
