### ISSUE TITLE
Install all 3 modules instructions not precise enough

### ISSUE THREAD

**Issue by wojciech-wroblewski** [MicrosoftDocs/office-docs-powershell#1966]
I just discovered these modules so naturally I wanted to install all 3. While trying to install the second one I got a whole page of red text ending with "CommandAlreadyAvailable" error. Had to google elsewhere to discover the -AllowClobber parameter.
I realize the parameter is shown in another example but that example focuses on a different parameter. 

I think this aspect could use a little explanation (I think a one-liner with a link to https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-6#optional-parameters would be enough) or at least adding the parameter to the commands for the 3 modules. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3240d3-6a7d-fc4b-62fd-d3a5375d8a4a
* Version Independent ID: 561212df-4dab-92b7-b634-57d53d313c6f
* Content: [PnP PowerShell overview](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by VesaJuvonen** [comment]
hi @wojciech-wroblewski - as the PowerShell modules for different SharePoint versions are using same cmdlet names, what you are experiencing, is by design due limitations in the PowerShell side. Here's, however, guidance from the PnP PowerShell team around how to install and use them side-by-side, if you have multiple different SharePoint deployments which you need to manage - https://www.erwinmcm.com/running-the-various-versions-of-pnp-powershell-side-by-side/. 

Based on our metrics, the typical setup is to install only one of the modules, so we have intentionally kept the information short in the guidance. Having though this comment now on the page, will help others to find this information, even though we are not looking to update the actual article. Thanks for your input.
