### ISSUE TITLE
Purge is not completely cleaning up the message!!!

### ISSUE THREAD

**Issue by zaicnupagadi** [MicrosoftDocs/office-docs-powershell#2077]
Hey MS,

When performing purge command I got info that user won't be able to recover the elements. Done some tests and seems that items go to the "Deletions folder" instead of "Purges": https://paweljarosz.wordpress.com/2018/08/25/does-new-compliancesearchaction-purge-really-purges-the-mailbox-like-it-should/ Please take a look on this as for the GDPR it is a major issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e154eb-3e1c-b4a5-418e-5be55b581255
* Version Independent ID: 00b93f90-663f-c277-c7de-09c184b4a322
* Content: [New-ComplianceSearchAction (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-compliancesearchaction?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@zaicnupagadi I updated the topic. For reference, this issue is already documented for GDPR:

- [Deleting items in Exchange Online mailboxes](https://docs.microsoft.com/microsoft-365/compliance/gdpr-dsr-office365#deleting-items-in-exchange-online-mailboxes)

- [Deleting documents in SharePoint Online and OneDrive for Business](https://docs.microsoft.com/microsoft-365/compliance/gdpr-dsr-office365#deleting-documents-in-sharepoint-online-and-onedrive-for-business)
