### ISSUE TITLE
This content is pretty lame.

### ISSUE THREAD

**Issue by PreventRage** [MicrosoftDocs/office-docs-powershell#2282]
It's for "getting" a big object full of information and it has no explanation of the content of that object nor a link to somewhere that does. The "Outputs" section is entirely boiler-plate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb7a7897-2dc8-48d1-ef9d-515cc285e175
* Version Independent ID: 70fcd483-a0e1-54c4-877d-944e7ad7b626
* Content: [Get-HostedContentFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/get-hostedcontentfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Get-HostedContentFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Get-HostedContentFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@PreventRage, we typically don't describe the output of a cmdlet (the exception is reporting cmdlets) because there are often unmodifiable properties in the output. Typically, you can get a reckoning of the interesting (modifiable) properties by the parameters on the corresponding New or Set cmdlets.

Regarding the Output section, that is boilerplate, because it links off to programmatically-generated results of the output types (if available). In the case of this cmdlet, if you click on the link and scroll down to Get-HostedContentFilterPolicy and click the link in the Output Types column, it takes you to https://msdn.microsoft.com/library/Microsoft.Exchange.Data.Directory.SystemConfiguration.HostedContentFilterPolicy.aspx, and under that is https://msdn.microsoft.com/en-us/library/microsoft.exchange.data.directory.systemconfiguration.hostedcontentfilterpolicy_properties.aspx which is really just a retelling of the parameters that are available on New-HostedContentFilterPolicy and Set-HostedContentFilterPolicy.

We realize the click maze isn't ideal, but it would be monumental to keep that same information current and updated within each topic.
