### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/office-docs-powershell#2306]
Example 1 and Example 2 both have Set-CsAuthConfig followed by a parameter called -BlockWindowsAuthExternally or -BlockWindowsAuthExternallyAndModernAuthInternally.  These items are not parameters.  They are values for parameter -Scenario.  Both should be updated to have Set-CsAuthConfig -Scenario in front of the actual parameter value which should not have a hyphen in front of it.

Example:  Set-CsAuthConfig -Scenario BlockWindowsAuthExternally

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26656471-f4e4-3dbe-b915-5230400d7b7f
* Version Independent ID: 4dc006ee-6bf8-a929-94f7-499a5af1f7a1
* Content: [Set-CsAuthConfig (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csauthconfig?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsAuthConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsAuthConfig.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@NicholasBurkhammer - looks like @nenonix (Nicole) submitted a Pull Request to update this for you. Just a note though that you can also update articles yourself. You can check the README on the main repo (https://github.com/MicrosoftDocs/office-docs-powershell) to see how to do it. This way you can fix articles right away instead of opening an issue for someone else to do it. I am happy to guide you too when you want to make an update. Thanks.
