### ISSUE TITLE
Purpose of Web Parameter

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#2347]
Site collection admins are not relevant to Webs. What is the purpose of this parameter? please provide an example of its intended usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8252d581-2d4f-5f0d-e1f2-263bdba1b035
* Version Independent ID: 71d56dd3-e308-b84f-76a7-b4c7e930d013
* Content: [Get-PnPSiteCollectionAdmin (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpsitecollectionadmin?view=sharepoint-ps#related-links)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSiteCollectionAdmin.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSiteCollectionAdmin.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@DeanGross Looking at the code itself (https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Site/GetSiteCollectionAdmin.cs), I think this is just due to inheriting from a base class, `PnPWeb` (https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Base/PnPWebCmdlet.cs). You might consider raising it as an issue here: https://github.com/SharePoint/PnP-PowerShell/issues. This would be more of a product defect at this point rather than a documentation defect.

@VesaJuvonen may know more, but the `-Web` switch is indeed pointless for the intended purpose of the cmdlet.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DeanGross how are you? **Thanks for your feedback.**
Did you have chance to review @tseward comment about the issue? I could confirm also that the same behaviour is still present. We will work to determine if it is better to update the cmdlet's documentation to clarify this or wait until this is fixed in cmdlet's inheritance.
Hope this information helps you.

**Comment by DeanGross** [comment]
@get-itips  yes, I read the comment and that makes sense to me. I think it would be helpful if the code was updated, or a comment added to the docs, so that other people won't have the same question as me

**Comment by get-itips** [comment]
Hello @DeanGross I created an issue for you on the PnP-Powershell repo, and cross referenced it here.
Please follow up that issue for updates.
Thanks!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for reporting the issue in Sharepoint repository and linking here and also sharing this explanation. @DeanGross  Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
