### ISSUE TITLE
-QuickLaunch parameter on Get-PnPNavigationNode doesn't exist

### ISSUE THREAD

**Issue by veronicageek** [MicrosoftDocs/office-docs-powershell#2371]
The parameter `-QuickLaunch` on the cmdlet `Get-PnPNavigationNode` **doesn't exist**, and therefore, should be removed from the examples section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6633c99f-3565-84cf-f11a-cd055df5885e
* Version Independent ID: 40ba47f1-40f3-b4c4-cc93-fa29841595c2
* Content: [Get-PnPNavigationNode (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpnavigationnode?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPNavigationNode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPNavigationNode.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell

@VesaJuvonen Would you like me to open this in the SharePoint repo?

**Comment by VesaJuvonen** [comment]
@AndreaBarr as these are comments in the documentation - see comments section at https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpnavigationnode?view=sharepoint-ps page, they should NOT be opened in the PnP PowerShell repository as nobody would be able to see the reply to the comment... comments should be absolutely answered here so that they are visible in the docs.microsot.com area.... and these questions will be answered by the PnP PowerShell engineering team when we have resources available for this work. 

So - if there are things related to the documentation, we should NOT redirect people to somewhere which is not relevant. These issues will be dealt with the PnP PowerShell team as soon as possible given the resource constraints.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @veronicageek How are you? Thanks for your feedback.
I could confirm that the parameter -Quicklaunch _does exists_ and returns values, I am using 3.8.1904.0 version. Please be sure to run the latest version of the module.
Hope this information helps you.
Thanks!

**Comment by veronicageek** [comment]
@get-itips - I'm also using 3.8.1904.0 and it's **not** there

![image](https://user-images.githubusercontent.com/25181757/56673567-6669d580-66b0-11e9-8e7e-7e8218240622.png)

**Comment by get-itips** [comment]
Yes, the correct is Get-PnPNavigationNode -Location QuickLaunch and that was the cmdlet parameters I tested before when I posted here, but actually wrote it carrying that error  :)
We are trying to catch up all of this typos on documentation so you will see this and other updates soon.
Thanks

**Comment by get-itips** [comment]
Hello @veronicageek 
As the article has been corrected to reflect the behaviour of the cmdlet, we will proceed closing this issue.
**We appreciate your feedback!**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @veronicageek 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
