### ISSUE TITLE
it's a shame that this is called "Docs". But it's OK because it's M$

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/office-docs-powershell#2473]
Really, you call it docs?
You just ignore to doc ALL Properties.

Yes, this is a shame.
Yes, it's great that it's M$. In fact, it's exactly what we expect from M$.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3824c5-6b67-a548-314c-f97a7386e661
* Version Independent ID: 496d21c4-a547-3f32-644e-a3830149c181
* Content: [Get-SPOTenant (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenant.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by VesaJuvonen** [comment]
Thanks for your input @schittli and sorry that you did not find the documentation sufficient. If you have specific asks or missing properties, which should be documented, we would hope that you'd be slightly more specific on your input, so that we can help you. Notice also that if any properties are missing, these documents are open-source and we do welcome contributions... happy to help to find the detailed descriptions, if you provide details on what is missing. 

Thanks for your input around the quality fo the docs. As this is not really actionable comment with clear input on what's missing, closing it for now.

**Comment by schittli** [comment]
Thanks @VesaJuvonen for your feedback!
I'm **very** sorry, but:

### We pay a lot of $100,000 for Microsoft products.
therefore we expect professional and complete products and, of course, **we're not willing to pay the product and doing their work**.
It's a shame that Microsoft tries to outsource writing their docs and fixing their bugs to the community for their very expensive commercial products.

### Of course, if a command returns properties, then professional Docs describe _every_ property (do customers really have to describe this?)
Each description of the property contains a short explanation of the reason for its existence (what's the meaning of the property?) and if proeprty is numeric, of course the unit is also given (pieces, bytes, etc.).

Therefore, there is no need for Microsoft to ask which properties lack the description: it's obvious.
