### ISSUE TITLE
What-If actually performed the operation.

### ISSUE THREAD

**Issue by siliconWOLF** [MicrosoftDocs/office-docs-powershell#2476]
Used -WhatIf to test.
When submitted without the -WhatIf found that the operation had been performed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6281137-91e0-c2ea-44ce-56ae9d9544f3
* Version Independent ID: 14e8465e-8af5-2eb0-b3e8-5a1350c8c3df
* Content: [Undo-SoftDeletedUnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/undo-softdeletedunifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Undo-SoftDeletedUnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Undo-SoftDeletedUnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by get-itips** [comment]
Hi @siliconWOLF thanks for your comments, actually, if you ran the cmdlet without the -WhatIf parameter, it is expected that the operation will be performed, If I understand correctly, that is what happened to you.

**Comment by siliconWOLF** [comment]
Apologies if my comment was not clear. The -WhatIF parameter was used and performed the operation.
For clarity: 
Checked for the deleted group and found the deleted group. 
Performed the Undo operation with -WhatIf parameter.
Performed the Undo operation without the -WhatIf parameter.
The operation failed as the group was not found.
Checked for the deleted group and the deleted group was not found, thus, the -WhatIf parameter did not trigger in this instance.
Hope that makes sense. 
Thanks for your help.

**Comment by AndreaBarr** [comment]
@siliconWOLF Thank you for this clerification. 

Based on the information you provided above I think that the best option will be to get you to support since they have more resources available to dig in and fine a solution for this issue. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
