### ISSUE TITLE
Outputs?

### ISSUE THREAD

**Issue by mrft** [MicrosoftDocs/office-docs-powershell#2715]
On https://go.microsoft.com/fwlink/p/?linkId=616387 there is nothing to be found about this Cmdlet (and not only this one).
And why not just add the info about Output Type directly in this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77a564cf-b454-d046-070b-ddc0c05c7a7f
* Version Independent ID: 055a9698-c1cc-174d-6c66-33c3bf21a55c
* Content: [Get-UnifiedGroupLinks (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/get-unifiedgrouplinks?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroupLinks.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroupLinks.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@mrft Thank you for your feedback. The microsoft powershell document's are created to  understand how a cmdlet syntax is used and we try to provide examples as much as possible, rather than the output value as it differs from client to client. Having said that this document that you are referring to "https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/get-unifiedgrouplinks?view=exchange-ps"
talks about how the Get-UnifiedGroupLinks cmdlet syntax is used and  the output for this cmdlet depends on the linktype parameter that you specify ( property that you want to view) which is also specified under the link type section of the same document.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @mrft  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
