### ISSUE TITLE
-OAuthAuthentication on Exchange 2010

### ISSUE THREAD

**Issue by AndreyNov** [MicrosoftDocs/office-docs-powershell#2719]
Parameter OAuthAuthentication is not supported on Exchange Server 2010. Please correct "Applies to" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da3b3b1-12d9-608f-7379-f13d988d0fe2
* Version Independent ID: feaa10b4-067a-5ac9-6df3-c3c84567fb2f
* Content: [Set-WebServicesVirtualDirectory (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access-servers/set-webservicesvirtualdirectory?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access-servers/Set-WebServicesVirtualDirectory.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access-servers/Set-WebServicesVirtualDirectory.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@AndreyNov, since April, 2018, the Exchange cmdlet reference topics are single sourced between Exchange 2010, Exchange 2013, Exchange 2016, (now) Exchange 2019, Exchange Online, Office 365 Security & Compliance Center, and Exchange Online Protection. The value of single-sourcing these topics is enormous, as there are hundreds of cmdlets available and shared between the various environments.

Near the top of the topic is an Applies To: tag that sets the first level of "where is this cmdlet available?". For Set-WebServicesVirtualDirectory, it says this:

> Applies to: Exchange Server 2010, Exchange Server 2013, Exchange Server 2016, Exchange Server 2019

The next level is at the parameter description itself. Even though the cmdlet is available across different versions of Exchange, it's likely that not all parameters are available in all versions, so check the Applies To value _in the parameter description_. For the OAuthAuthentication parameter, the Applies To: information looks like this:

> Applies to: Exchange Server 2013, Exchange Server 2016, Exchange Server 2019

So, there's no indication that OAuthAuthentication in Set-WebServicesVirtualDirectory applies to Exchange 2010. And, the topic hasn't been updated since September, so someone didn't sneak in and fix it after you left your comment but before this response.

**Comment by AndreyNov** [comment]
Hello Chris,
Good explanation. Thank you!
Sorry for my mistake.
