### ISSUE TITLE
Inconsistant useage of colon in EXO

### ISSUE THREAD

**Issue by JohnGGeo** [MicrosoftDocs/office-docs-powershell#2735]
It seems that there is a inconsistant useage of the colon in the exchange online module for powershell.
If you notice you are requiring the use of a colon often (ex. Set-UnifiedGroup -AlwaysSubscribeMembersToCalendarEvents:$false) Compare this to Set-Mailbox (ex. Set-Mailbox -AuditEnabled $true)
It would be nice to get a standard in the usage. It would be nice to be able to use the cmdlet without the colon as it this is already the norm in the rest of the module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd7d69db-be49-179e-94ce-635337c98d07
* Version Independent ID: 9e372e66-5c7e-4d9a-56de-a35ae353fa09
* Content: [Set-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JohnGGeo, it's not so much an issue of consistency of the use of the colon between a parameter and its value; it's related to the _type_ of parameter.

Boolean parameters like AuditEnabled on Set-Mailbox accept the values $true or $false, and you can use a colon between the parameter and the value, or you can omit it; it's completely optional. In those cases, I'd say the examples and usage in Exchange-related cmdlet reference topics is pretty consistent with no colons (although there may be a few stragglers here or there).

But switch parameters like AlwaysSubscribeMembersToCalendarEvents parameter on the Set-UnifiedGroup require just the parameter itself to set the value to true. So how do you set it to false? You **must** use the colon between the switch and the value. And, this requirement is also on the common Confirm switch parameter, which is available on virtually all New, Set, and Remove cmdlets: you have to use -Confirm:$false to disable the confirmation prompt.

As far as the coding philosophy of using Boolean parameters vs. switches for parameter types, it likely has to do with the expected usage (Boolean = a 50-50 shot either way; SwitchParameters: you'll more than likely need to turn the value on instead of off).
