### ISSUE TITLE
SoftDeletedMailbox switch is ambiguous

### ISSUE THREAD

**Issue by DougChandler** [MicrosoftDocs/office-docs-powershell#2758]
The description of SoftDeleteMailbox is ambiguous:
- "The SoftDeletedMailbox switch specifies whether to include only soft-deleted mailboxes in the results."
- "This switch is required to return soft-deleted mailboxes."

The first indicates the switch will ONLY return soft deleted mailboxes,
The second indicates switch will INCLUDE soft deleted mailboxes.
Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b640892-b0a1-4f20-1e25-fe5f0e97f5b6
* Version Independent ID: 51774b36-90fa-1d9a-5800-1a54d9f70590
* Content: [Get-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by DougChandler** [comment]
Or does Get-Mailbox not return soft deleted mailboxes normally?
Doing testing it appears that it ONLY returns soft deleted mailboxes when used, not clear whether deleted mailboxes are returned otherwise when the switch is not set

**Comment by chrisda** [comment]
@DougChandler, I agree. In some cases, less is more, so I changed the description to say:

> This parameter is available only in the cloud-based service.
> The SoftDeletedMailbox switch specifies whether to include soft-deleted mailboxes in the results. You don't need to specify a value with this switch.
> Soft-deleted mailboxes are deleted mailboxes that are still recoverable.

I still think it conveys the correct meaning (if you don't use this switch, you won't get any soft deleted mailboxes in the results).

I similarly updated related parameters in the topic:

- Arbitration

- Archive

- AuditLog

- AuxAuditLog

- GroupMailbox

- Migration

- Monitoring

- PublicFolder

- RemoteArchive

InactiveMailboxOnly and IncludeInactiveMailbox were also in the mix, athough I needed to call out their relationship (Only = exclusive; Include = include).

The topic SYNTAX blocks reveal and testing confirms that none of these parameters are mutually exclusive, meaning you can use them together in the same command (with the exception of  InactiveMailboxOnly and IncludeInactiveMailbox, which conflict by definition). For example, `Get-Mailbox -Arbitration -PublicFolder` is a bit nonsensical, but it successfully returns all arbitration and public folder mailboxes in the same command; there's no exclusivity to just one type of mailbox or the other (otherwise, the command would have failed).

Thanks for the feedback.

**Comment by DougChandler** [comment]
Thanks Chris, but I think "whether to include soft-deleted mailboxes" is wrong as it seems to return ONLY soft deleted mailboxes, i.e. not non-deleted mailboxes.
Many thanks,
Doug

**Comment by chrisda** [comment]
@DougChandler, OK. I fixed it; hopefully for the last time:

> The SoftDeletedMailbox switch is required to return soft-deleted mailboxes in the results. You don't need to specify a value with this switch.
