### ISSUE TITLE
incorrect powershell

### ISSUE THREAD

**Issue by HenrikBernhard** [MicrosoftDocs/office-docs-powershell#2799]
Get-Mailbox | where {$.RetainDeletedItemsFor -gt '14.00:00:00'}.
should be 
Get-Mailbox | where {$_.RetainDeletedItemsFor -gt '14.00:00:00'}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/recipient-filters/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@HenrikBernhard, the topic was correct in raw markdown, but markdown was treating the unescaped underscore character as an underline formatting indicator, and I found many other instances of this. I escaped the underscore character ( \\\_ instead of \_ ), so it should be OK now.

Thanks for the feedback.
