### ISSUE TITLE
DataMoveReplicationConstraint description

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/office-docs-powershell#2869]
The description of the DataMoveReplicationConstraint parameter is missing details on the AllDatacenters value, can you please add those? And any others that are missing :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ab3da9-9d7a-449d-e689-0a21dda73dda
* Version Independent ID: 583a1b9c-1c90-150c-fef7-f3d63e317ae3
* Content: [Set-MailboxDatabase (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailbox-databases-and-servers/set-mailboxdatabase?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailbox-databases-and-servers/Set-MailboxDatabase.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailbox-databases-and-servers/Set-MailboxDatabase.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@michevnew, are we talking about Exchange 2016?

I ran the command `Get-MailboxDatabase | Set-MailboxDatabase -DataMoveReplicationConstraint` with a junk value, and the error returned these possible values:

None
AllCopies
AllDatacenters
CIAllCopies
CIAllDatacenters
CINoReplication
CISecondCopy
CISecondDatacenter
SecondCopy
SecondDatacenter

I then tried CIAllCopies, and I got a different error saying that value had been deprecated, and these are the valid values:

None
CINoReplication
CISecondCopy
CISecondDatacenter
SecondCopy
SecondDatacenter

Those are the available values for Exchange 2013, 2016, and 2019. Exchange 2010 doesn't accept the CI values, but still accepts AllDataCopies and AllDatacenters.

I added the new values with descriptions. Let me know what you think.

**Comment by michevnew** [comment]
Much better now, thank you. AllDatacenters should be available on 2013+ though, no? My 2019 box is a a standalone server so I cannot confirm it actually accepts this as valid value, but it should be, for example it's mentioned here: https://docs.microsoft.com/en-us/exchange/high-availability/manage-ha/manage-database-copies?view=exchserver-2019#effect-of-mailbox-moves-on-continuous-replication

Same for AllCopies.

**Comment by chrisda** [comment]
@michevnew, 2013, 2016, and 2019 all have the same behavior: when you feed it a junk value, you get the first error that contains the most values. If you try the value AllDataCenters in 2016 and 2019, you get the second error that says the value has been deprecated, and shows the shorter list of accepted values.

2013 gives a different error for AllDataCenters that says you can't use that value because you have only one database, which very likely indicates that AllDataCenters is supported (but like you, I can set it because I only have one Exchange server with one database in one AD Site). In 2013, none of the other values gave me the "this value has been deprecated" error, so it's very likely that for 2013 only, all of those values in the first error message are still supported.

It sounds like I need to update that other topic you mentioned. I'm sure it started its life back in 2010, and was just kicked forward for every release.

Thanks for the feedback.
