### ISSUE TITLE
The InvokeSynchronizer parameter seems to be explained twice

### ISSUE THREAD

**Issue by mailgut** [MicrosoftDocs/office-docs-powershell#2997]
The InvokeSynchronizer parameter seems to be explained twice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370b6a41-7766-a863-aad6-93b560c62df5
* Version Independent ID: 2cda209e-2e96-ded8-4d80-ce07053be4ab
* Content: [Update-PublicFolderMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/sharing-and-collaboration/update-publicfoldermailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/sharing-and-collaboration/Update-PublicFolderMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/sharing-and-collaboration/Update-PublicFolderMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@mailgut, this is a known issue. Parameters with multiple YAML blocks (usually required because the parameter is required in one parameter set, but optional in another) are now suddenly duplicating the entire parameter description on docs.microsoft.com. If you look at the topic on GitHub, the whole parameter description isn't duplicating.
