### ISSUE TITLE
Password switch duplicate

### ISSUE THREAD

**Issue by nsabiyera** [MicrosoftDocs/office-docs-powershell#3093]
-Password switch has been duplicated in the documentation

**Comment by chrisda** [comment]
@nsabiyera, which cmdlet topic are you talking about?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by nsabiyera** [comment]
New Mailbox https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/new-mailbox?view=exchange-ps

**Comment by chrisda** [comment]
@nsabiyera, this is a known issue. Docs.microsoft.com is duplicating the parameter description because the parameter description has multiple YAML block caused by the fact the parameter is required in some parameter sets and optional in others. If you check the underlying topic on GitHub, you'll see the whole parameter description isn't duplicated.

We're looking into the issue. Thanks for the feedback.
