### ISSUE TITLE
Export-DLPPolicyCollection only works on Exchange Admin not Security and Compliance

### ISSUE THREAD

**Issue by VotoCopy** [MicrosoftDocs/office-docs-powershell#3241]
The cmdlet is missing from Security and Compliance. When you create policies in S&C it doesn't pull through when using the export function from Exchange Admin.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@VotoCopy Export-DlpPolicyCollection is for the original, Exchange-only DLP, not the 'unified DLP' in the Security & Compliance Center that also involves SharePoint, Skype, etc. And, the topic and individual parameters are correctly identified as applicable to Exchange Server 2013/2016/2019 and/or Exchange Online, not Security & Compliance Center.

In short, this is by design.
