### ISSUE TITLE
Switch Defaults

### ISSUE THREAD

**Issue by curspice** [MicrosoftDocs/office-docs-powershell#3335]
The document says that the default for -DeleteComments is "None", but that doesn't make sense.  It'd be more helpful to know whether the default is true or false if you don't change this setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a9c45b-34dd-c1c8-89f0-84f3d968eac4
* Version Independent ID: ec9c910c-25f2-f36a-8f75-ce052f0e8be6
* Content: [Set-CalendarProcessing (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-calendarprocessing?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@curspice, that Default Value attribute is required by the Windows PowerShell schema, yet there is no good way to automatically populate it. This is a problem for everyone's PowerShell help. In the past, we've always just said the default value of a parameter (where possible) the text of the description.

It appears the default value is $true, so I'll add that to the description and also to the Default Value attribute, since I'm in there, anyway.

Thanks for the feedback
