### ISSUE TITLE
searching error

### ISSUE THREAD

**Issue by CarolWangMS** [MicrosoftDocs/office-docs-powershell#3352]
I can not use the searching feature in the left navigation bar in the below website(and all sub pages of it).  This has caused inconvenience. 
https://docs.microsoft.com/en-us/powershell/module/exchange/?view=exchange-ps

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @CarolWangMS, thank you for your feedback.

Could you please attach a picture here to show the issue?

Thanks.

**Comment by CarolWangMS** [comment]
Hi Dario,

Seems that there are changes in the searching feature. But still I can not search in the specific website.

The normal website looks like this:
[cid:image001.jpg@01D5096F.D8FBAD10]

But this site I mentioned is like this:


[cid:image004.png@01D5096F.D8ED0710]


Best Regards,
Carol Wang

**Comment by dariomws306** [comment]
Thank you @CarolWangMS.

Could you please try again to attach the images? Please try to comment directly on Github, not replying the mail.

**Comment by CarolWangMS** [comment]
![normal](https://user-images.githubusercontent.com/49627956/57635474-cf6eaa00-75d9-11e9-9fd8-34cf07ce237d.jpg)
![unnormal](https://user-images.githubusercontent.com/49627956/57635476-d1386d80-75d9-11e9-86df-1062a0b75493.jpg)

**Comment by CarolWangMS** [comment]
Actually, several months ago it worked well.

**Comment by dariomws306** [comment]
Hi @chrisda,

Are you aware of this? Maybe you are aware and Team is working on it.

Thanks!

**Comment by chrisda** [comment]
@CarolWangMS, it appears that when you start at the root of the site:

https://docs.microsoft.com/en-us/powershell/exchange/

The search feature works fine. But, if you find and select something in the search box, and then from that specific page you try to search again, the results aren't as good (filtered results aren't shown), although at least now you are given the opportunity to seaarch:

![image](https://user-images.githubusercontent.com/33166947/58193233-63461300-7c77-11e9-89e8-1fa40bb01413.png)

The overall experience has changed somewhat since you first opened the issue (I know the search experience was broken for a while there).

**Comment by CarolWangMS** [comment]
yes, I can search in the root website but not in the specific website.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and sharing this explanation. @CarolWangMS 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
