### ISSUE TITLE
DrainingTimeout

### ISSUE THREAD

**Issue by mdlister** [MicrosoftDocs/office-docs-powershell#3418]
DrainingTimeout says the format is minutes however when i did it -drainingTimeout 60 it did it in 60 seconds and not minutes. The waittimeout is listed in the example as 1:30:00 for 1 hour 30 there is no reference to the format you need to declare the value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2de71d2-6792-7bcc-0064-bfade0a3786d
* Version Independent ID: b342568c-752d-5ec4-dd0e-a3599f6887c7
* Content: [Invoke-CsComputerFailOver (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/invoke-cscomputerfailover?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Invoke-CsComputerFailOver.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Invoke-CsComputerFailOver.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @mdlister, thank you for your feedback.

I am updating the article to remove minutes in the description of DrainingTimeout because it is TimeSpan format.
The easy way to use TimeSpan in this cmdlet is hh:mm:ss. For example 30 minutes are 00:30:00.

Another easy way to use TimeSpan format is the New-TimeSpan cmdlet:
https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/new-timespan
The same example in this case:
$TimeSpan = New-TimeSpan -Minutes 30
I am adding this example in the article too.

**Comment by yogkumgit** [comment]
@kenwith Please merge PR #3484

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @mdlister Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
