### ISSUE TITLE
Services List is not returned when the command is run from Remote PS session

### ISSUE THREAD

**Issue by pbarsan** [MicrosoftDocs/office-docs-powershell#3493]
Is it possible to return the enabled services when running from a remote PS session? I'm running Exchange Server 2016.

From remote session I get below:
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "http://$ExchangeServer/PowerShell/" -Authentication Kerberos
Import-PSSession $Session
PS C:\&gt;  Get-ExchangeCertificate

Thumbprint                                Subject
----------                                -------

From Exchange Management Shell running locally I get:
[PS] C:\&gt;Get-ExchangeCertificate

Thumbprint                                Services   Subject
----------                                --------   -------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cdfbc9b-f49b-e466-1802-783902fbbfdd
* Version Independent ID: 2ba87135-37a5-8819-9450-be344535c3f7
* Content: [Get-ExchangeCertificate (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/get-exchangecertificate?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/encryption-and-certificates/Get-ExchangeCertificate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/encryption-and-certificates/Get-ExchangeCertificate.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @pbarsan thanks for your feedback.
I could confirm that is not currently possible to get the Services under a PSSession.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @pbarsan 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by JeremyTBradshaw** [comment]
Is there any chance somebody in there could tell us how it is that the Exchange Admin Center and previously in 2010 the Exchange Management Console, are doing Get-ExchangeCertificate -Server <server> and successfully determining the services for remote servers?

I've found this doesn't even work if you do Invoke-Command -Session <Exch PSSession>.  Trying to find a way to get Exchange certificates without having to logon to an Exchange server to do it.  The only way to automate this task as it stands is to schedule the task on an Exchange server or somewhere that the Exchange Management Shell has been installed.

I'm wondering if I could decipher from the RawData (byte array)?  Or some other means?  Just would like to know what trick is being done under the covers by the Exchange software so that I can do the same trick in my PS remoting scripts.
