### ISSUE TITLE
Article does not contain content

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/office-docs-powershell#3534]
This page in the live environment does not match the content in GitHub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a90c18-81d3-0ae4-0abb-a4fa9c331f4b
* Version Independent ID: bbfcc73a-2696-527e-8e6d-95b5bc8b7f17
* Content: [SharePointServer](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/sharepoint-server.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/sharepoint-server.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
It seems that on this one @kenwith can help us, do you know maybe why the live version of the article does not contain content but the version in the repo does contain content? maybe rendering issue?
Thank you

**Comment by kenwith** [comment]
Could be 2 things I have seen.
1. docs.microsoft.com pulls from the Live branch of the repo. So someone has to remember to go and merge master branch to live branch.
2. If there is a formatting error in the Markdown the docs.microsoft.com site won't render it properly.


I will merge master to live now. So within 30 minutes or so that should be fixed. If still an issue then it is likely #2.

**Comment by kenwith** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/pull/3582

**Comment by get-itips** [comment]
Thank you @kenwith let's wait and see

**Comment by get-itips** [comment]
Hello @kenwith 
It seems that it is the 2nd option because the article looks the same, I reviewed the markdown and could not find the issue, also, put it in a markdown checker and it looks ok, is there a way we can access the rendering logs somehow?

What we know is that it successfully renders this line and stops

_The following cmdlet references are for SharePoint Server._

which is present in the md file.

Thanks

**Comment by kenwith** [comment]
I will ask the Azure team that owns the platform and see what they say.

**Comment by get-itips** [comment]
@kenwith Thank you
