### ISSUE TITLE
Command deprecated?

### ISSUE THREAD

**Issue by JakeMoe** [MicrosoftDocs/office-docs-powershell#3636]
When I run this command to clear out user mailboxes of items, I've started to get this message in the last few days.

WARNING: Search-Mailbox is being deprecated. Please use New-ComplianceSearch and related eDiscovery commands instead.

It would be good to get some more info around this, especially the "-DeleteContent" switch, which apparently won't work well in the new command, as it's been limited to 10 items at a time per mailbox.  Also, while it says it's been deprecated, there's no mention of the intended timeline for deprecation; how long can I continue to use this command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c6c666-7221-7984-82a5-d731fee0ac3d
* Version Independent ID: 6970ac1a-0aaa-c625-24db-e3db2296b6f8
* Content: [Search-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/search-mailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @JakeMoe, thank you for your feedback.

I have added a note to the article so readers can now that Search-Mailbox is being deprecated. We don't have a deadline now to let you know when you won't be able to use it.

Also you can find more information about deletion with New-ComplianceSearch here:
https://docs.microsoft.com/office365/securitycompliance/search-for-and-delete-messages-in-your-organization

Thank you again!

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #3665

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @JakeMoe Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by jgwinner** [comment]
I'm now getting an error that -DeleteContent doesn't exist, although it's still documented on this page. Deprecated doesn't mean "Gone" … the command should still work, OR the page should be modified to indicate what does still work.

**Comment by dariomws306** [comment]
Hi @jgwinner, thank you for your comment.

Please have in mind this: "Only the Mailbox Import Export role gives you access to the DeleteContent parameter"

Is it something that you have considered?

**Comment by jgwinner** [comment]
LOL! Thank you for listening to a closerd item.

Yes, you were correct, I didn't have that permission. To help others:

The Import/Export permission doesn't show up on the O365 portal, and because of the note on the page that things may be different between on-prem and hosted, I figured maybe I had everything. Once I knew where to look I found how to give that permission to the admin.

What also threw me is that instead of saying "you don't have permission" it says "A parameter cannot be found that matches parameter name 'DeleteContent'." If I had gotten a permission denied error, then I would have looked for that.

Mind you, sometimes people think obscurity is valid obscurity, so maybe that's why, but my guess is, the import not only skips commands but parameters within the command ... odd. 

== John ==
