### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/office-docs-powershell#3926]
I posted this issue before but it was closed without resolution.  At the bottom of the page, under Related Links, there is a link called "Online Version."  I assume this link is supposed to point to the O365 version of Add-ADPermission but it doesn't--it just reloads this same page.

The response to my initial post was:
@Canis-Lupis, that link is used in command line help, i.e., 'Get-Help Add-AdPermission -Online` to take you to the topic. So, it's by design.

This is incorrect as it doesn't relate to the link (i.e. web link) I am referring to.  I don't know what you were looking at but it wasn't the "Online Version" link in the Related Links section of this page.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01a54a6b-1ef9-2809-c90f-a56defdba194
* Version Independent ID: 8d822e69-212a-9c8d-d6db-4f7ba1e7707d
* Content: [Add-ADPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/active-directory/add-adpermission?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/active-directory/Add-ADPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/active-directory/Add-ADPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@Canis-Lupis, the Related Links section in the Add-ADPermission topic looks like this:

## RELATED LINKS

[Online Version](https://technet.microsoft.com/library/bef9f3db-84f6-4a40-81cb-c9cb9b9ee201.aspx)

That link points back to the Add-ADPermission topic itself, which is used by `Get-Help Add-ADPermission -Online` from the command line. All Exchange-related cmdlets have this link in the Related Links section, and 99% or more have **only** this type of circular link in the Related Links section.

**Comment by Canis-Lupis** [comment]
Thanks for the explanation but this is really confusing for the reader.  I still don't fully understand it but I doubt MS is going to change anything given that 99% of the Related Links do this, as you mentioned.
________________________________

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and digging deep into it. @Canis-Lupis 
If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Please keep contributing with your suggestions to improve the documentation.

**Comment by chrisda** [comment]
OK. I think I understand the confusion now.

Add-ADPermission is an EXCHANGE cmdlet. It's only available in the [Exchange Management Shell](https://docs.microsoft.com/powershell/exchange/exchange-server/open-the-exchange-management-shell), or if you [use remote PowerShell to connect to an Exchange server](https://docs.microsoft.com/powershell/exchange/exchange-server/connect-to-exchange-servers-using-remote-powershell).

I agree that it's confusing since the **name** of the cmdlet gives no indication that it be belongs to Exchange; it looks like a Windows Server or Active Directory cmdlet.

The Exchange product was so early in the PowerShell game that best practices like cmdlet naming conventions hadn't been established yet. Products that were later to PowerShell like SharePoint or Skype for Business Server follow the later-developed naming conventions for their cmdlets (\*-SP\* for SharePoint, \*-SPO\* for SharePoint Online, \*-CS\* (Communication Server) for Skype for Business, etc.).

Most Exchange cmdlets are easily identified because of their association with Exchange/email features (Get-Mailbox, New-TransportRule, etc.). But there are some Exchange cmdlets like this one that are hard to identify with Exchange just by their name (Get-User, Get-Contact, Get-Group, etc.).
