### ISSUE TITLE
URL Standard for SharePoint On-Prem PoSh

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/office-docs-powershell#408]
Is there, or do we want to have one, a URL standard for SharePoint On-Prem PoSh cmdlets? Or use verbiage to express what we are intending. E.g.:

    $wa = Get-SPWebApplicatinon http://webAppUrl

    $site = Get-SPSite http://siteUrl

    $web = Get-SPWeb http://webUrl

Right now URLs are all over the place when looking at the cmdlets.

@Techwriter40

**Comment by AndreaBarr** [comment]
@tseward Thank you for this feedback

Let me get this to the PowerShell team so we can get this URL question answered and updated to the docs. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@AndreaBarr I think this is more or less a question of formatting of the docs and one for the SharePoint PG (@Techwriter40 @pamgreen-msft). It's not a technical issue that needs to be raised with anyone.

**Comment by AndreaBarr** [comment]
@tseward The standard that Ken is having me use is putting all the issue vso's under the repo where the issue was found. If it's a document update like this I'll be updating it and keeping it assigned to me. If it is a technical issue or I need to reach out to a team for something then it would be assigned to whoever I connect with to get the issue resolved.
