### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by cparker4486** [MicrosoftDocs/office-docs-powershell#4119]
What is this page supposed to be? Why are all the pages in the left-nav lowercase?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7b7f847-37c9-8da4-214d-7ab80a0b0aa5
* Version Independent ID: 5a8f45ca-3d30-7fe6-cca3-0297f300dced
* Content: [Exchange PowerShell](https://docs.microsoft.com/en-us/powershell/module/exchange/?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/exchange.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/exchange.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by tseward** [comment]
It's the root page for Exchange cmdlets. Some other products, such as SharePoint (https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/?view=sharepoint-ps) have more detail on that page. Left nav is in lower case because that is how the repo is set up - https://github.com/MicrosoftDocs/office-docs-powershell/tree/master/exchange/exchange-ps/exchange.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @cparker4486 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
