### ISSUE TITLE
Get-EXORecipient -Anr does not seem to do any name resolution

### ISSUE THREAD

**Issue by kevinblumenfeld** [MicrosoftDocs/office-docs-powershell#4472]
There seems to be no filtering.  Unlike Get-EXOMailbox -Anr which seems to work great.

Thank you for these cmdlets! Keep 'em coming!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@kevinblumenfeld Thank you for your feedback. Since there was no link to the document, I'm assuming you are referring to the doc with the cmdlet get-exroecipient (https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/get-exorecipient?view=exchange-ps)

I was able to execute the cmdlet 

Get-EXORecipient -Anr Commonname
Get-EXORecipient -Anr displyname 

Can you provide us more information on what module you are using and what is the message you receive when running any of the above cmdlets? I'll then take a look and find out if there is a change needed in the document. 

Thanks
Sri

**Comment by kevinblumenfeld** [comment]
@msbemba Thanks for your reply. When running for example, 

Get-EXORecipient -Anr Fred

... I get all the recipients in the tenant.  I do not get just those with Fred in their name.  Like Fredrick.

**Comment by msbemba** [comment]
@kevinblumenfeld  Thank you for your feedback. I was testing on a tenant where I had only one user and the command worked fine. I see the issue now after creating another user. This looks like a bug and I will check with the team to find out the best way forward.

Thanks
Sri

**Comment by msbemba** [comment]
@kevinblumenfeld I checked with the team and since the Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, contact support at exocmdletpreview@service.microsoft.com

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this information. @kevinblumenfeld Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
