### ISSUE TITLE
About applies to

### ISSUE THREAD

**Issue by EvgenyArtemyev** [MicrosoftDocs/office-docs-powershell#4501]
It's supposed that the normalization rules are applied to Teams as well. Not only to Lync/SfB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 940f3a9e-f4cb-4c60-c57a-3d064e79677a
* Version Independent ID: 52842215-3cd7-c8c8-6556-d166a92a7b48
* Content: [New-CsVoiceNormalizationRule (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csvoicenormalizationrule?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsVoiceNormalizationRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsVoiceNormalizationRule.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@tomkau Tom, are you positive on adding Microsoft Teams to the applies to metadata field of this article?
Asking this because this would apply to many other cmdlets that are shared between SfB and Teams.
Thanks for your feedback. cc @kenwith

**Comment by kenwith** [comment]
@EvgenyArtemyev - thank you for taking the time to open the issue. I know it takes time to share knowledge as you gain it while working with the products and I appreciate it.

I can provide some info on this one. The "applicable" in the metadata is a technical construct based on the PowerShell module. Screenshot below from the raw markdown for this file at this link: https://raw.githubusercontent.com/MicrosoftDocs/office-docs-powershell/master/skype/skype-ps/skype/New-CsVoiceNormalizationRule.md

![image](https://user-images.githubusercontent.com/27743960/70253692-84b0ad00-1738-11ea-8cd8-871028575c2a.png)

An open source tool, [PlatyPS](https://github.com/PowerShell/platyPS) is used to generate and update the markdown from the PowerShell modules. The same tool is also used to build an XML file so that `Get-Help <cmdlet>` works and pulls a recent version of the GitHub help. PlatyPS relies on the "applicable" to build that XML file. 

There is Skype and Teams functionality in the Skype module so even though the module is functionally accurate to 'applicable' to Teams it is in the Skype module. It is due to how Teams pulled in Skype and uses underlying components. I have heard there is an effort to consolidate the Skype and Teams PowerShell modules into a single module and that will solve this problem when that happens. I know the product team is well aware of the confusion and I am too on the docs side.

What we can do if there are particular areas that are confusing is add a note saying something along the lines that even though the cmdlet or parameter lives in the Skype PowerShell module it also affects Teams.
