### ISSUE TITLE
Documentation of Set-PnPSearchSettings is unavailable

### ISSUE THREAD

**Issue by coupalm** [MicrosoftDocs/office-docs-powershell#4503]
The command documentation is not available (Set-PnPSearchSettings)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by kenwith** [comment]
@coupalm - thank you for taking the time to provide feedback. The PnP cmdlets are a little different than the Office cmdlets. The PnP cmdlets are community driven and the source for the reference is embedded within the cmdlet source code. For this one it is here: https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Search/SetSearchSettings.cs  From time to time the PnP community will generate the reference files and then upload them here so that the references are on the same site as the other Office PowerShell references. I suspect maybe they are due to dump another reference from the cmdlets to this location. I went ahead and opened the issue as a cross posting here: https://github.com/SharePoint/PnP-PowerShell/issues/2390  I know the PnP community very much appreciates your feedback and would welcome any contributions you wish to make to the reference content as well. You can add to reference by adding it to the source file for each cmdlet.

**Comment by wobba** [comment]
Hi,
It's available at https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsearchconfiguration?view=sharepoint-ps

**Comment by wobba** [comment]
The docs are now out: https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsearchsettings?view=sharepoint-ps

You can also always do: `get-help set-pnpsearchsettings -detailed` to get the same :)
