### ISSUE TITLE
A pale comparison to Get-MailboxStatistics

### ISSUE THREAD

**Issue by Gideon122** [MicrosoftDocs/office-docs-powershell#4626]
When I run Get-MailboxStatistics against my Exchange Online environment, I only need to provide the userID (SamAccountName) of the mailbox owners, and I am provided with a wealth of information.  When I run Get-ExOMailboxStatistics, I am forced to use the UPN of the mailbox owners, and I am provided with only six lines of information.  Get-ExOMailboxStatistics requires the use of the -Properties switch to see any more information, but that switch doesn't take any wildcard characters, so I have to know the exact names of the properties I want to see.  There are 60 properties!!!!!  In order to see them all, I actually to type out all 60 properties separated by a comma.

I also noticed all there are many properties included with Get-MailboxStatistics that are missing from Get-ExOMailboxStatistics, like IsEncrypted and DataEncryptionPolicyId.

Get-ExOMailboxStatistics doesn't come close to the usability of the Get-MailboxStatistics.  I am greatly concerned about how all the other ExO cmdlets will compare to the original cmdlets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 718c1794-b07b-cada-343d-0c8db0d7882f
* Version Independent ID: 3184237b-ab2a-570d-8a8c-267b6bad270e
* Content: [Get-EXOMailboxStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/get-exomailboxstatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/powershell-v2-module/Get-EXOMailboxStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/powershell-v2-module/Get-EXOMailboxStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by Gideon122** [comment]
I have found that I can use the -PropertySets All command to display all the properties.  However, I still find Get-MailboxStatistics provides 126 different properties, over double what Get-ExOMailboxStatistics provides.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Gideon122, thank you for your feedback.

Exchange Online PowerShell Module V2 is on preview. Please provide this feedback on exocmdletpreview[at]service[dot]microsoft[dot]com.

We are here to help to improve/update documentation. Thank you!

**Comment by chrisda** [comment]
@Gideon122, by definition, the Get-EXO cmdlets return a much smaller list of properties as compared to the corresponding 'regular' Exchange cmdlet. It's all about speed and efficiency. The most frequently used properties should be included in the Default property set.

If you're trying to use Get-EXOMailboxStatistics to return every last available property, then it likely won't be much (if any) faster than Get-MailboxStatistics, so you might as well just use Get-MailboxStatistics.

If you think there are key properties that are missing from the Default or otherwise available property sets, please leave feedback at exocmdletpreview[at]service[dot]microsoft[dot]com.

Thanks for the feedback
