### ISSUE TITLE
Example format for -DescriptionTimeFormat is incorrect

### ISSUE THREAD

**Issue by geoffblack** [MicrosoftDocs/office-docs-powershell#4716]
`MM` is the specifier for month, while `mm` is the specifier for minutes. Your example should say:

`MM/dd/yyyy, where MM is the 2-digit month, dd is the 2-digit day and yyyy is the 4-digit year.`

Consider adding a canonical link to date specifier strings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb7d356a-b903-45af-7390-008a3c98d1e1
* Version Independent ID: 8822c739-073e-597b-a30f-7bc56e9e6d42
* Content: [Get-InboxRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-inboxrule?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-InboxRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-InboxRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @geoffblack, thank you for your feedback.

I don't consider this update important because I think there isn't a standard for this and in the description it's specified: "where mm is the 2-digit month".

**Comment by geoffblack** [comment]
@dariomws306 The point of this issue is that specification/example in the documentation is incorrect. Try it yourself. `mm` returns the minutes, not the month. Here's one standard, although specific to dotNet, that is applicable: https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#MM_Specifier.

**Comment by dariomws306** [comment]
Hi @geoffblack, thank you for your comment.

It's just a description, there isn't a grammar rule here. It could be "xx/dd/yyyy, where xx is the 2-digit month". You will find "mm/dd/yyyy, where mm is the 2-digit month" all around Microsoft documentation.

**Comment by geoffblack** [comment]
I disagree with your both of your assessments that "It's just a description" and that it's okay to have an "example" in documentation that is demonstrably incorrect.

**Comment by dariomws306** [comment]
Ok, I propose the following since I think this update is very important for you and I will not be able to persuade you to change your mind.
I will create a Pull Request to apply this update as it will be reviewed in another stage and they will approve or reject it.

Are you agree with this option?

**Comment by geoffblack** [comment]
Sure, that sounds great. It's less that it's important for _me_ since I've discovered the inaccuracy, and more that it's important for other people trying to follow incorrect documentation. Tons of people read this documentation every day, so I don't understand why you wouldn't want to fix it. There _is_ a standard, and the documentation is incorrect.

**Comment by chrisda** [comment]
Fundamentally, both of you are correct.

In looking at just Exchange cmdlet reference topics, there are roughly 409 similar/identical instances across 103 topics. Easy enough for me to update all of them globally, but here are my issues:

- I found a couple of instances that use MM/DD/YY. Technically, these are also incorrect, but is anyone really confused by this 'error'?

- When we're talking about dates, does anyone really think we're telling them to enter 'minutes/day/year' especially since we give them a clear date example in the same sentence?

  > For example, if the computer is configured to use the short date format mm/dd/yyyy, enter 09/01/2018 to specify September 1, 2018.

- This description has been 'wrong' since the Exchange 2013 days:

  ![image](https://user-images.githubusercontent.com/33166947/72926405-3f0c6b80-3d09-11ea-9299-ace3cd46d6dd.png)

- Technically (and this is very thin), that parameter type is String, not System.DateTime or ExDate.Time, so in reality, we can say whatever we want.

- 'MM/dd/yyyy' simply looks ugly and is very jarring to me. It looks like a typo, and I could just as easily see someone else thinking that it's a typo.

For these reasons, I'm not going to change it, particularly in just one topic.

Thanks for the feedback.

**Comment by dariomws306** [comment]
@chrisda Thank you!
