### ISSUE TITLE
Get-CsBatchPolicyAssignmentOperation [Forbidden] : Access Denied

### ISSUE THREAD

**Issue by AdamJParker** [MicrosoftDocs/office-docs-powershell#4729]
Installed the preview cmdlets for Teams, New-CsBatchPolicyAssignmentOperation returns no errors, but polices are not being applied to users. and when I run the Get I receive Get-CsBatchPolicyAssignmentOperation : Access Denied.

Category   : InvalidOperation
Activity   : Get-CsBatchPolicyAssignmentOperation_Get
Reason     : Exception
TargetName : { Status =  }
TargetType : <>f__AnonymousType0`1

Not sure what would be causing this, running as a Global Admin in Office365

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by AdamJParker** [comment]
Getting similar issue with another command.

New-CsGroupPolicyAssignment -GroupId $GroupName -PolicyType TeamsMessagingPolicy -PolicyName EduStudent_Custom -Priority 1

New-CsGroupPolicyAssignment : Access Denied.

Category   : InvalidArgument
Activity   : Get-CsBatchPolicyAssignmentOperation
Reason     : ParameterBindingException
TargetName :
TargetType :

**Comment by get-itips** [comment]
Hello @AdamJParker 
How are you? Hope you are doing good 👍 
Preview cmdlets can have some glitches, as they are currently under development and testing, and because of that I could not identify any documentation that needs to be changed.
If, for any reason, you identify that production cmdlets behave differently from what is documented, a documentation change should be required, but that is not the current scenario.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @AdamJParker 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
