### ISSUE TITLE
Edge based on Chromium doesn't work to download EoL PowerShell

### ISSUE THREAD

**Issue by joshmalik** [MicrosoftDocs/office-docs-powershell#4774]
The following line needs editing as the new Edge based on Chromium doesn't work:

Note: Internet Explorer or Edge is required because the download in the next step uses ClickOnce, so Google Chrome or Mozilla Firefox won't work.

https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell?view=exchange-ps

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @joshmalik, thank you for your feedback.

To get it working on Edge chromium you need to enable ClickOnce here:
edge://flags/

**Comment by chrisda** [comment]
This was similarly covered in Issue #4708. In that issue, the complaint was that ClickOnce does (now) work in the Chromium-based Edge using the method @dariomws306 mentioned. That issue was complaining about the note I originally added that said "ClickOnce doesn't work in the new Chromium-based Edge" (which it didn't at the time). Round and round we go.

I didn't want this topic to turn into "how to get ClickOnce working in your browser of choice" (even Chrome and Firefox apparently support ClickOnce with the right third-party add-ins), but it the spirit of cooperation, I added a note about Chromium-based Edge support.

Thanks for the feedback.

Closing.
