### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by PlayMa256** [MicrosoftDocs/office-docs-powershell#4833]
Hello Guys,

We are trying to expose the powershell apis into the external world, but all operations are getting slower, specially on creating a session.

Is there a way to keep a reference of the session?

Are there any rest apis for skype endpoints? Like the result we get from `Get-CsOnlineUsers` ?

Thanks!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @PlayMa256 Matheus
How are you? Hope you are doing good.
Is there an specific article that you see needs a correction? 
Can you please share the link to the article?

About REST API, the recommendation now is going for the [Graph API](https://docs.microsoft.com/en-us/graph/overview), have you checked it?

Thank you

**Comment by PlayMa256** [comment]
Hello @get-itips 
I'm doing fine and you?

So i asked the same question on https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/266#event-3007264011 and they told me to get here!

Also, we are having performance issues, some fetch operations take like, 2 minutes to complete. How can we decrease the performance?

And how can we keep track of sessions created? is there a pool of sessions?

**Comment by get-itips** [comment]
Hello @PlayMa256 again 👍 
Here, we are limited to address issues in documentation, like typos or wrong information. 
So specifically about issues like performance I need to kindly request you to open a support ticket on your tenant.
I am not sure about the other question because I would need the link of the Docs article that brought you here to read and understand better.
Thank you
