### ISSUE TITLE
New-TeamChannel Fails with BadGateway (Graph API Also Fails with BadGateway)

### ISSUE THREAD

**Issue by wisc75** [MicrosoftDocs/office-docs-powershell#4846]
When attempting to execute the New-TeamChannel via Powershell, it is throwing a useless error "BadGateway" - Executing as Global Admin.  Various Global Admins tried to execute without any luck.

When I try to execute via the Graph API - I also get the same BadGateway:
   "error": {
        "code": "BadGateway",
        "message": "Failed to execute backend request.",
        "innerError": {
            "request-id": "85f8ab46-e74c-4e9e-b986-c0f151629b37",
            "date": "2020-02-07T17:36:40" 

Process to reproduce:
- Open Powershell in elevated mode
- Install-Module -Name MicrosoftTeams
- Import-Module -Name MicrosoftTeams
- Connect-MicrosoftTeams
- New-TeamChannel -GroupId 77aa42c5-96e5-43f7-baf9-b4f88b6ec61e -DisplayName "Mondovi" -Description "Mondovi"

Responds With:

New-TeamChannel : Error occurred while executing 
Code: BadGateway
Message: Failed to execute backend request.
InnerError:
  RequestId: f96bfeeb-a590-40c2-a4b1-be966ef8d288
  DateTimeStamp: 2020-02-07T17:16:17
HttpStatusCode: BadGateway
At line:1 char:1
+ New-TeamChannel -GroupId 77aa42c5-96e5-43f7-baf9-b4f88b6ec61e -Displa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-TeamChannel], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.NewTeamChannel

**Comment by kenwith** [comment]
@wisc75 - I just wanted to jump in and respond right away. This issue list is for the docs and I want to make sure you get the issue resolved right away. Would you please open a service request support ticket? You can find the option in your tenant admin and it will be routed immediately to the support engineers and they can respond quickly and work through the issue with you. The service engineers have a process in place to escalate any bugs directly to product team and on-call product team engineers too.

I appreciate you opening the issue here too so that we can capture the resolution the support engineers work with you to get it resolved. If you don't mind reply back here we can update the docs so that others benefit for whatever the root cause.

**Comment by wisc75** [comment]
Hi @kenwith  - We opened a ticket via O365 console as well.  Thanks much!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@wisc75  Thank you

**Comment by wisc75** [comment]
Support Ticket is 18630673
