### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by TeddyLegs** [MicrosoftDocs/office-docs-powershell#4875]
The hyperlink for the module at the top is broken
https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38bb8d4e-9525-b291-ac2e-71c7da02984d
* Version Independent ID: 02753e62-8b57-90cc-bf6e-9f69661c3135
* Content: [Remove-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/Remove-UnifiedGroup?redirectedfrom=MSDN&view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Remove-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Remove-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @TeddyLegs, thank you for your feedback.

This is a known issue for the last several weeks. We're Investigating.

**Comment by yogkumgit** [comment]
@TeddyLegs The issue has been reproduced and verified as a bug and is being escalated to product team for investigation.
The issue is thus being closed because the issues section of this repository is intended for product documentation problems, not product support.
Also feel free to reply if there is anything else that could be done to improve the document itself.
Thanks

**Comment by dariomws** [comment]
The Exchange module link issue was fixed this week. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
