### ISSUE TITLE
Missing parameter "ErrorAction"

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/office-docs-powershell#4970]
Hi, 
It looks like set-remotemailbox accepts the -erroraction parameter but it does not work.

It is not documented on this page.  Has the erroraction parameter been deprecated?

e.g. 
Specifying "Set-RemoteMailbox -ErrorAction Stop"  has no impact on a failed execution, it does not stop as it should.
This means Try..Catch  error handling fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f329d9dd-6a2f-1b04-6cfe-40183d03826e
* Version Independent ID: cf7fa5f9-45f6-49d3-29e0-aa3aef6ad602
* Content: [Set-RemoteMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/set-remotemailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/Set-RemoteMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/Set-RemoteMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@anthonynz, do you happen to know if ErrorAction ever worked for this cmdlet? I ask because it seems like lack of support for a specific common parameter seems to be cmdlet specific. In other words, I wonder if ErrorAction ever worked with Set-RemoteMailbox, even as far back as Exchange 2007 or Exchange 2010.

The only other potential issue I would bring up is Windows PowerShell versions; anything greater than 5.1 isn't currently supported.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @anthonynz hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
