### ISSUE TITLE
Unregister-SPOHubSite should include a -Force

### ISSUE THREAD

**Issue by mrpullen** [MicrosoftDocs/office-docs-powershell#511]
Should support a -Force parameter, which would remove a HubSite entry. 

I've been playing with the Register-SPOHubSite command, deleted a hub site and recreated at the same URL, but the old "Hub reference" (from Get-SPOHubSite) is still there. 

So now if I Register-SPOHubSite I have two results from GEt-SPOHubSite with the same URL, but different HubSiteId and Id values.

The issue seems to be that the global navigation and other HubSite functionality (like adding a site to a hub) seems to be impacted, as it's no longer working.. News rollup is however working without issue..

**Comment by hrfmjp** [comment]
I can delete Hub Site by using latest SPO Management Shell(16.0.7625.1200): Unregister-SPOHubSite &lt;SiteId&gt;

**Comment by AndreaBarr** [comment]
@mrpullen Thank you for this feedback

I will get this to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@mrpullen The cmdlet in question Disables the hub site feature on a site so that it is no longer a hub site. Associated sites may still appear associated for up to an hour. If you want to speed up the process, use the Remove-SPOHubSiteAssociation cmdlet to remove the associated sites first. 

Please refer to https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/unregister-spohubsite?view=sharepoint-ps

Thank you for reporting and making the docs better. Much appreciated.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @mrpullen  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
