### ISSUE TITLE
whenMailboxCreated has a minimum value

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/office-docs-powershell#5324]
in my PowerShell script, I tried something like
[System.DateTime]$after = 0
$filter = "whenMailboxCreated -gt '$after'"
get-mailbox -filter $filter

This didn't return results.  When I set the year to 2000, then it *did* set results.

Can you add to the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/recipient-filters/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @anwarmahmood1, thank you for your feedback.

I think this doesn't make sense. If you want to return all your mailboxes regardless of creation date, just avoid using the whenMailboxCreated filter.

I think adding this comment does not add value to the article.

**Comment by anwarmahmood1** [comment]
Thanks Dario.  It was just an example
`PS C:\Users\amahmood5> [System.DateTime]$after = 0
PS C:\Users\amahmood5> $after

01 January 0001 00:00:00`


So $after is a valid date, and so my PowerShell...

`$filter = "whenMailboxCreated -gt '$after'"
get-mailbox -filter $filter`

...should have returned every mailbox created since 01 January 0001.  It did not.

IF I do...
`[System.DateTime]$after = get-date -year 2000`
$filter = "whenMailboxCreated -gt '$after'"
get-mailbox -filter $filter`

...then I *DO* get results back.  

Hence, whenMailboxCreated has an *UNDOCUMENTED* minimum value.

In real life, I would use a recent date, I was just trying the command to make sure it worked.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @anwarmahmood1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by anwarmahmood1** [comment]
Yogesh, *I* provided the explanation, not Dario.

Why have you closed this? Have you updated the documentation?
________________________________

**Comment by dariomws** [comment]
Hi @anwarmahmood1,

As you said, in real life, we would use a recent date. I think the minimal value here doesn´t have a sense as you won´t use it, instead you won´t use the filter.

But if you disagree, you insist that we have to add it to the document, and it won't let us close the issue, I can create a pull request because it needs approval and we can see another opinion.

Please let me know if it´s fair for you.

Thanks!

**Comment by anwarmahmood1** [comment]
I would still add it.

**Comment by dariomws** [comment]
Hi @get-itips,

Could you kindly help me here? Do you think adding the minimum value could help? In this case, we have to check it, because I tried it, and if you use 1500 for the year, it doesn't return results, if you use 1600, it returns. So, I think the minimum value is between 1500 and 1600.

Thanks!

**Comment by anwarmahmood1** [comment]
Not sure why 1600 worked for you; it doesn’t work for me.

A quick PowerShell script identified…

1 January 1601

According to…

https://support.microsoft.com/en-gb/help/188768/info-working-with-the-filetime-structure

This is the lowest value of the FILETIME structure.

**Comment by get-itips** [comment]
Hello @anwarmahmood1 How are you ? 👍 @dariomws Dario thanks for letting me share my thoughts on this.
Made a script to quickly test the initial datetime where the filter will get results and it is 01/01/1601
I honestly do not see any value adding this information to the article, like we did in the past, if there is anyone that stumbles upon this in the future they will be able to find the information here on this thread.

**Comment by anwarmahmood1** [comment]
Andres,

Not everyone looks at the issues list.

They shouldn’t have to look at the issues list!

When you buy a can of soda, do you check with the FDA to see if there has been a recall notice on that brand of soda because of a safety issue?  Do you do it for all your shopping? Course you don’t!

I recommend…

  1.  Add it in for now.
  2.  Escalate this to the Exchange PowerShell team.  A far better fix is for the PowerShell command to fail gracefully, saying something like “invalid date; whenMailboxCreated must be greater than more than 01/01/1601”.
  3.  You can remove it then!  People like me won’t need to look it up; we’re told!

As it stands, you’ll enter a valid PowerShell command, and get an invalid result back.

**Comment by dariomws** [comment]
Well, I think as a conclusion we can say that it´s not a limitation of whenMailboxCreated. It´s a limitation of DateTime object. Please check the following article:
https://docs.microsoft.com/dotnet/api/system.datetime.tofiletime

"The value of the current DateTime object expressed as a Windows file time"

"A Windows file time is a 64-bit value that represents the number of 100-nanosecond intervals that have elapsed since 12:00 midnight, January 1, 1601 A.D. (C.E.) Coordinated Universal Time (UTC)."

Considering it´s not a limitation related to this Property, and that really is related to any DateTime property, I am now more sure that we cannot add it as a limitation for whenMailboxCreated in this article.

**Comment by dariomws** [comment]
More information:
ttps://docs.microsoft.com/windows/win32/api/minwinbase/ns-minwinbase-filetime

**Comment by anwarmahmood1** [comment]
OK, let's follow the trail;

Get-Mailbox
https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailbox?view=exchange-ps

tell me I'll get...

Exchange Management Shell cmdlet input and output types | Microsoft Docs
https://docs.microsoft.com/en-us/exchange/client-developer/management/exchange-management-shell-cmdlet-input-and-output-types

...which tells me I'll get...

Mailbox class (Microsoft.Exchange.Data.Directory.Management) | Microsoft Docs
https://msdn.microsoft.com/library/Microsoft.Exchange.Data.Directory.Management.Mailbox.aspx

...which tells me the members...

Mailbox members (Microsoft.Exchange.Data.Directory.Management) | Microsoft Docs
https://docs.microsoft.com/en-us/previous-versions/office/exchange-server-api/ff341573%28v%3dexchg.150%29


...which DOESN'T EVEN EXPLAIN WHAT whenMailboxCreated is!  But if I do continue to...

Mailbox.WhenMailboxCreated property (Microsoft.Exchange.Data.Directory.Management) | Microsoft Docs
https://docs.microsoft.com/en-us/previous-versions/office/exchange-server-api/ff436589%28v%3dexchg.150%29

...which tells me it's a Type: System.Nullable<DateTime> which takes me to...

DateTime Struct (System) | Microsoft Docs
https://docs.microsoft.com/en-us/dotnet/api/system.datetime?redirectedfrom=MSDN&view=netframework-4.8

which tells me...

> The DateTime value type represents dates and times with values ranging from 00:00:00 (midnight), January 1, 0001 Anno Domini (Common Era) through 11:59:59 P.M., December 31, 9999 A.D. (C.E.) in the Gregorian calendar.

So, if you eventually wade through the links, you get incoherent behaviour anyway!

I could just write a blog article saying how terrible Microsoft documentation is, or I could be constructive and raise it as an issue.  I'm choosing to do the latter.  Help me out!

**Comment by dariomws** [comment]
There is a limitation of 64 bits in the Active Directory object/Windows File System, this is why DateTime properties "represent the number of 100-nanosecond intervals that have elapsed since 12:00 midnight, January 1, 1601 A.D. (C.E.) Coordinated Universal Time (UTC)".
More examples:
https://docs.microsoft.com/windows/win32/adschema/a-pwdlastset
https://docs.microsoft.com/windows/win32/adschema/a-lastlogon
https://docs.microsoft.com/windows/win32/adschema/a-lastlogontimestamp
https://docs.microsoft.com/windows/win32/adschema/a-accountexpires

Docs.microsoft.com feedback is available to listen to people and improve documentation. Listen to people does not mean apply all the changes they want, it means to listen to them and apply our criteria to consider whether these updates make sense or not, and we do our best with mistakes like anyone else. Hope you trust me that we want to do our best, I want to do my best.

Microsoft is always happy to listen and get feedback from people and their customers, docs feedback is just an example, User Voice is another good example. I encourage you to continue leaving feedback on docs as we will be happy to hear from you.

That being said, I disagree with this update, but if you insist my last effort might be to create a pull request to apply this update. Then, it needs to get approval from other people. If they agree and accept the update, it will be live in a few hours.

Thank you!

**Comment by chrisda** [comment]
@anwarmahmood1, there seems to be a mixture of issues here:

- If you want to see a change in how the product actually works, the best course of action is to open a support case.

- From a documentation perspective (which is what this forum is about and what we can control), specifically what would you like changed in the topic? The fact that whenMailboxCreated doesn't work with values before the year 2000? We can do that.

Frankly, I find this issue rather obscure. I wouldn't expect to enter values like 0 or 1600 or even 2000 and expect to get results.

**Comment by anwarmahmood1** [comment]
> The fact that whenMailboxCreated doesn't work with values before the year 2000? We can do that.

Yes please. All I asked for at the beginning. I've determined it's actually 1 January 1601. I would recommend that.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @anwarmahmood1 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
