### ISSUE TITLE
New-ComplianceSearch does not work

### ISSUE THREAD

**Issue by csdunaway** [MicrosoftDocs/office-docs-powershell#5377]
I have tried for days to get this search to work. All i get is this:
new-ComplianceSearch : The term 'new-ComplianceSearch' is not recognized as the 
name of a cmdlet, function, script file, or operable program.

I have connected my pssesson to:https://ps.compliance.protection.outlook.com/powershell-liveid/, but that command is not there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e72de6a-dd0f-e6e3-c4b1-63ee1cf752e8
* Version Independent ID: 228e51b7-a16a-1e5d-11c9-95cdc30b23dd
* Content: [New-ComplianceSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-compliancesearch?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by bjonesvcccd** [comment]
Not sure if it's related, but I'm also not able to populate new compliance search objects from the Security and Compliance center.  Searches will complete in the O365 admin center UI, but no object is created to target for compliance search actions.

**Comment by JimAdkins** [comment]
+1. I also run the standard PS commands, and the "New-ComplianceSearch" command is not avialable. Any updates? 

`$session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.protection.outlook.com/powershell-liveid/ -Credential $creds -Authentication Basic -AllowRedirection
Import-PSSession $session -AllowClobber`

`New-ComplianceSearch : The term 'New-ComplianceSearch' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

**Comment by dariomws** [comment]
Hi @csdunaway/@bjonesvcccd/@JimAdkins, thank you for your feedback.

Are you a member of the Discovery Management role group?

"This cmdlet is available in the Mailbox Search role. By default, this role is assigned only to the Discovery Management role group, and not to the Organization Management role group".

**Comment by JimAdkins** [comment]
@dariomws Thanks for the response. Yes, the account that runs my automation is a member of that group. 

Long Story:
This issue came up because I use automation to generate these content searches. I used the -ConnectionUri URL: 
https://ps.compliance.protection.outlook.com/powershell-liveid/
and for over a year or two now, this has worked as expected. 

About 2 weeks ago, it was brought to my attention that the creation was failing. The error was:

`Powershell Error: Running the Get-Command command in a remote session reported the following error: Processing data for a remote command failed with the following error message: The request for the Windows Remote Shell with ShellId CB65FC97-BDF4-4266-884F-D39BBE5A06E5 failed because the shell was not found on the server. Possible causes are: the specified ShellId is incorrect or the shell no longer exists on the server. Provide the correct ShellId or create a new shell and retry the operation. For more information, see the about_Remote_Troubleshooting Help topic..`

After some research around this error, I found the new -ConnectionUri:
https://ps.protection.outlook.com/powershell-liveid/ 
I updated my automation to use that, and things started working again just fine for about a week. Then, this issue came up a few days ago, and it has been failing ever since. 

I have been testing each URI every day since then, and nothing has changed.

**Comment by dariomws** [comment]
@csdunaway yes, ConnectionUri is https://ps.compliance.protection.outlook.com/powershell-liveid/ if you don´t have MFA enabled.
If it doesn´t work you can try with:
Connect-IPPSSession -UserPrincipalName <UPN>
https://docs.microsoft.com/powershell/exchange/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @csdunaway 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by bmercernccer** [comment]
Why is there nothing in the documentation explaining that it is not sufficient to merely use a new command, but that you must in fact completely change how you connect? This is important information, it should be placed in front of users who look for it rather than requiring google searches to uncover the meaning of an error. 
Actual user experience:
![exchange powershell wtf](https://user-images.githubusercontent.com/21127097/105882039-33661b80-5fd3-11eb-9c6c-0ccbe253948c.jpg)
Who thinks this is ok?

**Comment by chrisda** [comment]
@bmercernccer, I see what your saying. The error message should say:

> WARNING: This cmdlet is obsolete. Use Get-ComplianceSearch **in Security & Compliance Center PowerShell** instead.

I added the following note to the Synopsis section of each *-MailboxSearch cmdlet topic:

**Note**: As of October 2020, the \*-MailboxSearch cmdlets are retired in Exchange Online PowerShell. Use the \*-ComplianceSearch cmdlets in Security & Compliance Center PowerShell instead. For more information, see [Retirement of legacy eDiscovery tools](https://docs.microsoft.com/microsoft-365/compliance/legacy-ediscovery-retirement).

**Comment by ChrisB9907** [comment]
I have the same issue after installing the management module. It almost seems like it doesn't want to import the commands. Tested this with the current version 2.0.4 and the preview 9 version of 2.0.4.

![image](https://user-images.githubusercontent.com/60661129/110049297-6f914800-7d06-11eb-8d9a-35828404c861.png)

**Comment by dariomws** [comment]
@ChrisB9907 - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by ChrisB9907** [comment]
Thanks for the link, I will look into submitting a support ticket for it and see if a DCR can be done or have a bug ticket put in. I would recommend that if submitting a support ticket for issues like this is (I would assume that it is either just my tenant having this issue or it an issue globally with the module itself) is the best course of action, the docs might have a place when clicking on the "submit feedback" button navigate a user to submit a support request if they feel they have come upon a bug.

**Comment by luckman212** [comment]
Hitting this issue hard today. @csdunaway @dariomws @ChrisB9907 @chrisda -- did you guys figure anything out? Is this a per-tenant issue or a problem with the cmdlet? Or something else... permissions?

**Comment by chrisda** [comment]
@luckman212, you should open a support case about this. I have no new information.

**Comment by luckman212** [comment]
Thanks @chrisda - you know what, a good night's sleep fixed the problem. Must have been some kind of delay on propagating permissions (adding the `{Compliance,Discovery} Management` roles). I logged on this morning and the `New-ComplianceSearch` cmdlet was there. Some better feedback from the backend on the status of that propagation would be great. 🤷‍♂️
