### ISSUE TITLE
Applies to

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/office-docs-powershell#5405]
Should the "Applies to" bit at the top of the page also include MS Teams as the policy is for MS teams aswell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0dcf829-c8b6-7fc5-9f77-2b9c34584dda
* Version Independent ID: a6cd191e-2926-8ba6-5503-fa99c5c21561
* Content: [Set-CsTeamsMobilityPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmobilitypolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMobilityPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMobilityPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @saragava
* Microsoft Alias: **saragava**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by kenwith** [comment]
@obhayes - thank you for taking the time to login to GitHub and submit feedback. The cmdlet references are all open source and the quality is greatly improved by experts like you giving feedback and improving them. On this one I noticed a note that says the cmdlet is deprecated. However, you did hit on a major point which is the Applies To in the metadata. It is something that is a big source of confusion because there is a Skype for Business Online PowerShell module and a Teams PowerShell module. I know the product team is working to bring these together to a single Teams module but I don't know any details yet. Once that happens this confusion will go away. That Applies To is tied to the actual name of the module and it is used to build the XML file that is checked into code so that when someone types  Get-Help <cmdlet> at the terminal the help is displayed in the terminal. The tool we use is an open source one called PlatyPS ( https://github.com/PowerShell/platyPS ). PlatyPS ties the Applies To to the module name in PowerShell which is why I can't change the Applies To. There are some other cmdlet's in the same boat. They are in the Skype for Business Online PowerShell module yet they affect Teams. And it is something I try to add content to the reference to make clearer but it is always a bit confusing. Anyways, sorry for the long winded reply here but just wanted to shed some light on this one. :)
