### ISSUE TITLE
Deprecation notice does not account for secure application model

### ISSUE THREAD

**Issue by KelvinTegelaar** [MicrosoftDocs/office-docs-powershell#5458]
The Exov2 module currently does not support the secure application model for Microsoft Partners, MSPs and CSPs. The deprecation notice states that with the disablement of basic auth this access will also be lost. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @KelvinTegelaar, thank you for your feedback.

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, contact us at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

**Comment by Shadoxity** [comment]
This is also a big issue for us, we need to be able to use secure application model!
I have tried with the exchangeonline accesstoken but it fails to connect.
Sending an email to that address also.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @KelvinTegelaar Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Shadoxity** [comment]
Why has this been closed without resolution? We still cannot use this module!

**Comment by dariomws** [comment]
Hi @Shadoxity, thanks for your comment.

Docs feedback is available to improve documentation. This issue was closed because there is nothing to update in the referenced article.

Exchange Online PowerShell V2 general availability was announced last Wednesday. They're currently working on Service Principal and Certificate Based Auth support to provide a solution to those wanting non-interactive scenarios.
If you want to provide more feedback about this module you can go to the blog:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
Or in the Office 365 Admin/Exchange Admin UserVoice forum:
https://office365.uservoice.com/forums/273493-office-365-admin?category_id=96338
