### ISSUE TITLE
The credentials for step 1 ARE ACTUALLY YOUR OFFICE365 credentials

### ISSUE THREAD

**Issue by yuval-a** [MicrosoftDocs/office-docs-powershell#5498]
And NOT your Windows credentials. This was very unclear from the instructions!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?redirectedfrom=MSDN&view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @yuval-a, thank you for your feedback.

At the beginning of the article I can read:
"It's a simple three-step process where you enter your **Office 365 credentials**, provide the required connection settings, and then import the Exchange Online cmdlets into your local Windows PowerShell session so that you can use them."

In the step 1:
"In the Windows PowerShell Credential Request dialog box, type your **work or school account** and password, and then click OK."

Maybe I´m missing something, please let me know.

Thanks!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @yuval-a 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
