### ISSUE TITLE
Support for Azure Cloud Shell

### ISSUE THREAD

**Issue by dprzybylo** [MicrosoftDocs/office-docs-powershell#5637]
Hi. It appears the Security and Compliance center doesn't support Azure Cloud Shell access with MFA. The rest of Exchange Online already has this support. If this is supported, are you able to link the documentation?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @dprzybylo, thank you for your feedback.

I think it´s true, Connect-EXOPSSession is supported on Azure Cloud Shell but not Connect-IPPSSession. Also, EXO V2 module is not supported in PowerShell Core but it will be supported soon, and then support for Azure Cloud Shell could be added.
I cannot help you here with features request because this section is available to improve docs.microsoft.com, please try with these channels:
https://office365.uservoice.com/
https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2#report-bugs-and-issues

**Comment by yogkumgit** [comment]
@dprzybylo  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
