### ISSUE TITLE
Need missing word added to PWSH CLI help file for Remove-Mailbox

### ISSUE THREAD

**Issue by bingoglossy** [MicrosoftDocs/office-docs-powershell#5665]
[Enter feedback here]
In the classic PowerShell interface "help Remove-Mailbox" the third paragraph in the DESCRIPTION field needs to be changed from "Or, you can immediately the disconnected mailbox by using..." to "Or, you can immediately purge the disconnected mailbox by using..."

Thank you.

P.S. Yes, I did run Update-Help and it's still there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5286595d-c5b1-18e5-c5b7-4da806f66a68
* Version Independent ID: a51a4a6c-11f4-ba4d-46fa-5187e2d99e5f
* Content: [Remove-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@bingoglossy, I'll admin that it's bee a while since we've checked cmdlet reference help back into code (that's what updates command line help). Unfortunately, Exchange can't use Update-Help.

The topic on the web doesn't have that typo, so whenever we check help back into code, and the code is 'delivered' (to servers in the datacenters or in the next CU for on-premises Exchange Server), then the command  line help will be updated.

Thanks for the feedback.

Closing.
