### ISSUE TITLE
Add navigation sections/heading to page

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#580]
This page is very long, it would be easier to navigate if there were additional headings in the left or right side page navigation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3240d3-6a7d-fc4b-62fd-d3a5375d8a4a
* Version Independent ID: 561212df-4dab-92b7-b634-57d53d313c6f
* Content: [PnP PowerShell overview](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* Service: **unspecified**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

We want to make sure your PnP issue is handled appropriately.

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
