### ISSUE TITLE
UserSharedWith Property blank from Search-UnifiedAuditLog

### ISSUE THREAD

**Issue by ajhosek** [MicrosoftDocs/office-docs-powershell#5969]
According to the Docs on the detailed properties of audit logs, the property "UserSharedWith" should have the value of the user that the resource was shared with if the operation was "SharingSet". 

I have specifically filtered out the operations to be "SharingSet" and there is still not a value for the property "UserSharedWith"

**Comment by markjjo** [comment]
@ajhosek I would suggest that you determine if there are other audit records that are generate by the same SharingSet event and see if those records identify the UserSharedWith. Sharing operations often generate multiple records. Otherwise, you could open a ticket with Microsoft Support to investigate.
