### ISSUE TITLE
Deprecation of Basic auth for EXO PowerShell?

### ISSUE THREAD

**Issue by MikeDembek** [MicrosoftDocs/office-docs-powershell#5977]
The current SCT templates disable Basic auth; are there any plans to migrate EXO PowerShell to use another authentication mechanism?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @MikeDembek, thank you for your feedback.

You can use modern authentication to connect to Exchange Online PowerShell since the release of the V1 module:
https://docs.microsoft.com/en-us/powershell/exchange/mfa-connect-to-exchange-online-powershell

Now, we should use V2 as it was released in June 3rd:
https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2

**Comment by MikeDembek** [comment]
Hi Dario, I understand that Modern Auth is used to connect to O365, but basic auth is required to be enabled on the local WinRM client (see https://docs.microsoft.com/en-us/powershell/exchange/mfa-connect-to-exchange-online-powershell?view=exchange-ps).  That is not the case for the V2 module.  Is that slated for a fix?  Alternatively, when will the v2 module have feature parity?

**Comment by dariomws** [comment]
Basic or legacy authentication it's still there until the second half of 2021:
https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-april-2020-update/ba-p/1275508

But it's recommended that you block it and only use Modern Authentication. Exchange PowerShell Module v2 requires that WinRM has Basic Auth enabled but it connects to EXO using Modern Auth. Even you can have WinRM disabled in the source machine, but you have to enable Basic Auth.

More information:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/5833
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4504

**Comment by MikeDembek** [comment]
Hi Dario, that exchange team article addresses client access; I don't see how that relates to auth requirement for EXO administration.  This issue specifically pertains to local WinRM settings and the requirement for WinRM basic auth to be enabled in the local settings; legacy auth is already disabled for my user account in O365 and I understand that modern auth is used, but I'm trying to understand why basic auth is still required on the client side as described in https://docs.microsoft.com/en-us/powershell/exchange/mfa-connect-to-exchange-online-powershell?view=exchange-ps.

The EXO v2 module can successfully authenticate without WinRM basic auth enabled, but the v1 module cannot.  Can you explain that?  @eric-ash-1 mentions similar behavior with the AzureAD module in issue  #4504. 

Is that slated to be fixed for the v1 module?  How about feature parity for the v2 module?

**Comment by dariomws** [comment]
Hi @MikeDembek, the article states that basic auth will be retired in Exchange Online in the second half of 2021. Anyway, it´s recommended that you use EXO PS V2 and it will connect using modern auth.

I don't have detailed information about why WinRM basic auth is required, sorry about that. But V1 requires it because it establishes a remote PowerShell session according to my understanding.
I think the product team is working on remove this requirement.

If you need more information please try to leave a comment here:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
https://office365.uservoice.com/forums/264636-general/suggestions/20570782-allow-winrm-authentication-other-than-basic-when-c

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @MikeDembek Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
