### ISSUE TITLE
"Exchange Service administrator"

### ISSUE THREAD

**Issue by mramnet** [MicrosoftDocs/office-docs-powershell#6079]
For RBAC role assignment, there is no "Exchange Service administrator" only "Exchange administrator"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @mramnet, thank you for your feedback and help us to improve docs.microsoft.com.

In the Microsoft Graph API and Azure AD PowerShell, this role is identified as "Exchange Service Administrator." It is "Exchange Administrator" in the Azure portal. It is "Exchange Online administrator" in the Exchange admin center.

Anyway, I'll update the article because the steps are performed in the Azure Portal.
