### ISSUE TITLE
More Details MacOutlook parameters

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/office-docs-powershell#6185]
Hi,
the Set-CasMailbox has two paramaters namend -EwsAllowMacOutlook and -MacOutlookEnabled.
Where is the difference between those two commands? Could you give more details or refer to other documentation?
Basically both parameters just say "Outlook for Mac"
How do I know which Outlook for Mac uses EWS? 
One says:
> The EwsAllowMacOutlook parameter enables or disables access to the mailbox by Outlook for Mac clients that use Exchange Web Services (for example, Outlook for Mac 2011 or later).
The other:
> The MacOutlookEnabled parameter enables or disables access to the mailbox by using Outlook for Mac.

I have an O365 plan and use Outlook for Mac 16.39.  Does it use EWS or not?
Do I need to disable both?

best regards
Joerg
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54cde16c-a0fd-2dc4-762e-3e953c3cb426
* Version Independent ID: eaaa07c6-4335-2fcf-6d8a-976e3589039d
* Content: [Set-CASMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-casmailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-CASMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-CASMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@joergrenn, both of those statements are semi-correct. EWS is used in Outlook for Mac 2011 or later. Apparently, only the [New Outlook for Mac](https://techcommunity.microsoft.com/t5/outlook-blog/introducing-the-new-outlook-for-mac/ba-p/936884) that's currently in Preview doesn't use EWS; it uses the newer 'Microsoft Sync technology' that's used in the Windows 8 and 10 mail app, and also [Outlook for iOS and Android](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq#native-microsoft-sync-technology-migration).

Further evidence is the EwsAllowMacOutlook parameter is very old (likely, it was used back in the day to allow block newer versions of Outlook for Mac vs. older versions of Entourage), while the MacOutlookEnabled parameter is quite new by comparison (added to the topic just yesterday, but likely available since ~January).

**Comment by chrisda** [comment]
I updated the descriptions for the EwsAllowMacOutlook and MacOutlookEnabled parameters as described.

Thanks for the feedback.

Closing
