### ISSUE TITLE
Get-ComplianceSearchAction - Inputs & Outputs

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/office-docs-powershell#6322]
Could you please complete the documentation for Inputs and Outputs? Thank you.
https://docs.microsoft.com/en-us/powershell/module/exchange/get-compliancesearchaction?view=exchange-ps#outputs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c88089d-82e3-9d16-780a-51411ed2a095
* Version Independent ID: b74df581-0143-996a-b3b4-663f31d2eb71
* Content: [Get-ComplianceSearchAction (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-compliancesearchaction?view=exchange-ps#outputs)
* Content Source: [exchange/exchange-ps/exchange/Get-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@robertcaretta, the results of the platyPS utility that we use to dump cmdlets to topics only shows this:

## OUTPUTS

### System.Object

Typically, we don't spend time documenting output properties for cmdlets because a) they change frequently and without warning, b) they often contain unmodifiable or datacenter-centric values (in other words, those properties don't correspond to parameters in the New-\* or Set-* cmdlets), and c) that's a level of customization we have historically not wanted to do. The only exception to this rule is reporting cmdlets; we document those as thoroughly as possible.

Is there anything in particular that you're looking for?

**Comment by robertcaretta** [comment]
HI Chris,

I figured as much, but thought I would inquire. I totally understand. We
are running a fairly large batch of eDiscovery searches and exports. We ran
into a 3 exports per user limit, and also a 10 per tenant limit. Was
curious if there was a way to poll the compliance center for the number of
active exports currently running for each of those limits. So I started
researching other cmdlets. Hence my ticket.

Actually it would be really nice if eDiscovery could queue up all of our
exports and run them in sequence. We have roughly 200-300.  3 exports
processing at a time per person is fine.

Thanks,
Rob

**Comment by chrisda** [comment]
@robertcaretta, I'm told there isn't an official way to queue eDiscovery searches like this. That being said, you could like script something that periodically checks the value of the Status property value in the output of Get-ComplianceSearchAction cmdlet. When the value is Completed, then you could move on to the next one.

Or, you could open a support case and see if they have a better solution.

**Comment by robertcaretta** [comment]
Sounds good. Thank you for the feedback.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @robertcaretta Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
