### ISSUE TITLE
Update the ConnectionURI

### ISSUE THREAD

**Issue by shrikantbhere** [MicrosoftDocs/office-docs-powershell#6326]
[Enter feedback here]
Please update the below ConnectionURI to this page, as it allows the global users to connect.
https://ps.compliance.protection.outlook.com/powershell-liveid/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b188049-5302-25da-5bd2-89401be1db96
* Version Independent ID: a1d18859-a50d-acd2-1ef1-3729925dc1f1
* Content: [Connect to Security & Compliance Center PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/mfa-connect-to-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/mfa-connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/mfa-connect-to-scc-powershell.md)
* Service: **o365-security-and-compliance**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@shrikantbhere, are you saying that the ConnectionUri value is required to connect? The way the topic is currently written, you don't need to specify a ConnectionUri value for 'regular' O365/M365 Security & Compliance Center PowerShell.

And if the ConnectionUri value is required, is an AzureADAuthorizationEndPointUri parameter value also required?

**Comment by shrikantbhere** [comment]
Hello Chris,

Yes, the Connection URI and AzureADAuthorizationEndPointURI parameter are required for regular O365/M365 users to connect.

The Exchange Online PowerShell Module does not allow you to connect without those parameter.

Regards,
Shrikant Bhere
________________________________

**Comment by chrisda** [comment]
@shrikantbhere, the topic has claimed that no ConnectionUri or AzureADAuthorizationEndPointUri for 'normal'/WW O365 tenants since its creation (3+ years ago), and this is the first I've heard about any problems.

I just tested the procedures in a normal E5 tenant, and they worked fine without either of those values with an MFA account.

What is the nature of your subscription/SKU? What errors do you receive? And just to clarify, we're talking about the older Exchange Online PowerShell module that you install via ClickOnce in the Exchange admin center (EAC) **not** the much newer [EXO V2 module](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2) that you download from the PowerShell Gallery?

**Comment by chrisda** [comment]
The ExO V2 module is now available for MFA or non-MFA connections to Security & Compliance Center. Basic authentication and the older V1 module will go away eventually.

The connection instructions in the following topic should be considered authoritative:

<https://docs.microsoft.com/powershell/exchange/connect-to-scc-powershell>

Thanks for the feedback.

Closing
