### ISSUE TITLE
Document Update Request | Extended Message trace or Historical Search may not return all the result when filtered with Distribution group

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/office-docs-powershell#6351]
[Enter feedback here]

This is a document update request for scenario where when a report is pulled specifying the the DL email address in the UI or using start-historicalsearch, certain messages may be not returned in the report, however if the report is pulled by specifying DL group member, they appears in the report.
Currently this is by design because we did not log the recipient if it is a Distribution group so the message will not show up by filtering with group. (Issue1584020)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c796e0b-9ee3-146b-856c-1e1c5786666b
* Version Independent ID: 4e5c08ec-a2d4-63a4-27f0-e08445f64f8a
* Content: [Start-HistoricalSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/start-historicalsearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Start-HistoricalSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Start-HistoricalSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @qaehtesh, thank you for your feedback.

I see that you are a Microsoft employee. Here is a site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=qaehtesh

And if you have a Microsoft alias you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

I'm not sure about what update applies to this article. I don't have access to Issue1584020, could you kindly provide more detail? Does it also impact to Get-MessageTrace and Get-MessageTraceDetail?
Maybe Start/Get-HistoricalSearch doesn´t show the Expand event as Get-MessageTrace and Get-MessageTraceDetail.

Thank you again!

**Comment by qaehtesh** [comment]
@dariomws Thank you for the response.
This applies to all, message trace, detail and historical search.
The issue here is that recipient filter in message trace if recipient is a Distribution group so the message will not show up message because we do not log it for group as recipient and one needs to use the group member as recipient filter.
The behavior is consistent with all type of trace with UI and shell.

It is been informed to me that currently this is by design that we do not log the recipient if it is a Distribution group so the message will not show up by filtering with group. (Issue1584020) and thus a document update request.

**Comment by dariomws** [comment]
Thanks, @qaehtesh. Sorry but I still don´t understand.

If I use the RecipientAddress parameter with Get-MessageTrace and Get-MessageTraceDetail to filter output by DL I get this for example:
![image](https://user-images.githubusercontent.com/33589238/91200558-ae01d680-e6d5-11ea-8246-26d18131789e.png)

I'm testing now with Start-HistoricalSearch.
