### ISSUE TITLE
Output section is empty, needs to explain return values

### ISSUE THREAD

**Issue by schumatt-msft** [MicrosoftDocs/office-docs-powershell#6368]
The Outputs section should explain the properties returned and values that might be returned in those properties.  As it stands, users are left to "experiment" with running the command to understand the possible return values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1ef000-2e09-c225-f4cc-1250d5f12fde
* Version Independent ID: 9a556920-1923-9611-e3e6-96c10a567d51
* Content: [Get-OMEMessageStatus (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-omemessagestatus?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-OMEMessageStatus.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-OMEMessageStatus.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@schumatt-msft, the only viable way to populate the Output sections for all 1200+ Exchange-related cmdlets (Exchange Server, Exchange Online, Security & Compliance Center and Exchange Online Protection) is do do it programmatically using the same utility that we use to dump cmdlets to topics. This is the results for the Output section in Get-OMEMessgeStatus:

## OUTPUTS

### System.Object

Not exactly useful, right?

Since you are an MSFT, feel free to follow up with me directly in email.

Closing
