### ISSUE TITLE
Where does this policy show up in the gui?

### ISSUE THREAD

**Issue by Absoblogginlutely** [MicrosoftDocs/office-docs-powershell#6424]
After creating a policy with this command, I typically find that it generates a 500 error in the old Exchange filter page at https://outlook.office365.com/ecp/?rfr=Admin_o365&exsvurl=1&mkt=en-US# and also does not show up.
![image](https://user-images.githubusercontent.com/21364480/91494873-95d1b900-e887-11ea-9071-e5145005a4cd.png)
Looking for the filter in the new Mail filtering at https://protection.office.com/antispam also does not have any filters show up.
![image](https://user-images.githubusercontent.com/21364480/91494942-b437b480-e887-11ea-9ee3-d78df5559f64.png)

This is despite it being listed in powershell - 

![image](https://user-images.githubusercontent.com/21364480/91495015-d7fafa80-e887-11ea-8cfd-1c573b4f3b50.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f3e148b-3c06-fc14-a019-ad6c667538ba
* Version Independent ID: 4dbad4f9-02fb-5fbd-3bff-18e2e6c8f82e
* Content: [New-HostedContentFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-hostedcontentfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-HostedContentFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Absoblogginlutely, the UI (either the Security & Compliance Center or the Exchange admin center) does a bit of behind-the-scenes trickery to create the underlying rule *and** the policy at the same time. If you create just the policy in PowerShell, it won't show up in the UI because there's no corresponding rule.

This is explained [here](https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-your-spam-filter-policies#use-powershell-to-create-anti-spam-policies):

Creating an anti-spam policy in PowerShell is a two-step process:

1. Create the spam filter policy.
2. Create the spam filter rule that specifies the spam filter policy that the rule applies to.

 **Notes**:

- You can create a new spam filter rule and assign an existing, unassociated spam filter policy to it. A spam filter rule can't be associated with more than one spam filter policy.
...
- A new spam filter policy that you create in PowerShell isn't visible in the Security & Compliance Center until you assign the policy to a spam filter rule.

So are you saying we need similar guidance in the New-HostedContentFilterPolicy topic?

**Comment by chrisda** [comment]
And... no need to answer. I updated the Description section of every malware/spam related New-\*Policy topic to mention that creating the rule in PowerShell isn't enough.

Thanks for the feedback.

Closing
