### ISSUE TITLE
too many user mailboxes

### ISSUE THREAD

**Issue by mgrimesii** [MicrosoftDocs/office-docs-powershell#6515]
I have over 13K user mailboxes, this script runs too long to get accurate feed back since EOL power-shell has a timeout, what is the work around for getting the output?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16eaecbc-a74e-855b-190e-05e4104f88e4
* Version Independent ID: 036e3c50-429d-f592-f626-d0f88d9e5772
* Content: [Get-TextMessagingAccount (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-textmessagingaccount?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Get-TextMessagingAccount.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-TextMessagingAccount.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @mgrimesii, thank you for your feedback and help us to improve docs.microsoft.com.

The script Start-RobustCloudCommand.ps1 is available to help customers that they used to running commands against large numbers of users at once:
https://techcommunity.microsoft.com/t5/exchange-team-blog/updated-running-powershell-cmdlets-for-large-numbers-of-users-in/ba-p/1000628

Also, even this cmdlet is not included I recommend that you read the following article because EXO PowerShell Module V2 has improved performance for a large number of users:
https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @mgrimesii Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mgrimesii** [comment]
Thank you….

Thanks,

Melvin Grimes II
System Administrator
Office of the CIO, IT Shared Services
United States Department of Transportation
Room E51-209, 1200 New Jersey Ave, S.E.
Washington, DC 20590
Office - (202) 366-4954 | Mobile - (202) 897-5249

For IT Assistance, Please contact the 5-Help Service Center:
(202) 385-4357
(866) 466-5221 (toll-free)
5-HelpExpress@dot.gov<mailto:5-HelpExpress@dot.gov>

**Comment by mgrimesii** [comment]
Thank you!

Thanks,

Melvin Grimes II
System Administrator
Office of the CIO, IT Shared Services
United States Department of Transportation
Room E51-209, 1200 New Jersey Ave, S.E.
Washington, DC 20590
Office - (202) 366-4954 | Mobile - (202) 897-5249

For IT Assistance, Please contact the 5-Help Service Center:
(202) 385-4357
(866) 466-5221 (toll-free)
5-HelpExpress@dot.gov<mailto:5-HelpExpress@dot.gov>
