### ISSUE TITLE
TAP no longer needed for Meeting Migration Service (MMS)

### ISSUE THREAD

**Issue by MichaelLaMontagne** [MicrosoftDocs/office-docs-powershell#6537]
This line should be removed: "This functionality is currently available to TAP customers only. For customers not in TAP, meetings are always migrated to Skype for Business Online."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22159e01-061b-499a-fe99-3fe19bed57e9
* Version Independent ID: 98b9a798-e232-0b2c-ee0f-857071885c1d
* Content: [Move-CsUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Move-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Move-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by get-itips** [comment]
Thanks @MichaelLaMontagne will update the article with your feedback.

Also, here is a site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=MichaelLaMontagne

And if you have a Microsoft alias you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any Issue or PR's you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html
