### ISSUE TITLE
Clarify why there are three sets of parameters in the Syntax section

### ISSUE THREAD

**Issue by VShrubowich** [MicrosoftDocs/office-docs-powershell#665]
Please clarify what each of the three sets of parameters in the Syntax section is for.  Are they for Exchange Server 2010, Exchange Server 2013, and Exchange Server 2016, respectively?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5b0c5d-0466-d55a-1f7b-0b2d25a316fd
* Version Independent ID: 07b0c093-eb6b-4834-3cd4-d8f2af6ca0f5
* Content: [Set-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@VShrubowich, a cmdlet reference topic for any product will have multiple Syntax blocks due to the presence of mutually exclusive parameters on the cmdlet (parameters that's can't be used together in the same command). This is (hopefully) explained in the topic https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/exchange-cmdlet-syntax that's linked to from the Synopsis section. And for a cmdlet like Set-Mailbox that has a lot of parameters, it can be difficult to find the unique parameters that exist in one Syntax block but not another (I call it "playing Where's Waldo?").

To your point about 2010/2013/2016, we did combine the separate versions of Set-Mailbox on TechNet into the single version on GitHub, which could have caused separate Syntax blocks for a unique but mutually exclusive parameter that's only available in one version of the product but not the others. And, Set-Mailbox is one of those cmdlets that's available in on-premises Exchange and in Exchange Online. So, some Syntax blocks for this cmdlet are definitely caused by mutually exclusive parameters between on-prem and the cloud (for example UserPrincipalName and MicrosoftOnlineServicesID).

For simpler cmdlets with fewer parameters, the Syntax blocks can be useful to quickly determine which parameters can or can't be used together in the same command. But, for big, complex cmdlets like Set-Mailbox, there are so many parameters and so many Syntax blocks, that they become effectively useless. If you try to use parameters that can't be used together in the same command, you'll get an error, anyway.
