### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by monsterapp** [MicrosoftDocs/office-docs-powershell#677]
Can you clarify how to add a header with this command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce02f005-8ecf-69cf-6d4d-49d325056725
* Version Independent ID: eaf106fc-2d67-d98d-b276-e17045277b55
* Content: [Add-PnPNavigationNode (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpnavigationnode?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPNavigationNode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPNavigationNode.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@monsterapp Thank you for this feedback

We want to make sure your PnP issue is handled appropriately.

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
