### ISSUE TITLE
Disconnect after Connect-IPPSSession ?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/office-docs-powershell#6836]
Like `Connect-ExchangeOnline` / `Disconnect-ExchangeOnline` is there also a **Disconnect-...** counterpart to `Connect-IPPSession`?
In other words is there a way to disconnect or terminate the session?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 945ab2ea-22ae-814f-8898-fe84b7f29870
* Version Independent ID: 5383d152-988d-b1ee-4957-db5fb6213754
* Content: [Connect-IPPSSession (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-ippssession?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-IPPSSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Connect-IPPSSession.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@andrePKI, no. But, Disconnect-ExchangeOnline works on sessions created with Connect-IPPSSession. See <https://docs.microsoft.com/powershell/exchange/connect-to-scc-powershell>.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @andrePKI Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by andrePKI** [comment]
Yes, this is helpful for me. It just doesn’t seem symmetrical, that’s why I asked. @chrisda and @yogkumgit thank you both.

**Comment by schittli** [comment]
What a shame!

M$ tells us, that it is important for the security that `Connect-ExoV3` does not connect to the Security & Compliance, therefore we must use `Connect-IPPSSession`.

Because there is no `Disconnect-IPPSSession`, M$ says, it's not so important for the security to close the session to the Security & Compliance as soon as we have done the job: _"just keep it open until you no longer need the Exchange session"_, M$ says.

Or does M$ really expect that we kill the Exchange Session to close the IPPSSession just to restart the common Exhange-Session seconds later?


M$'s behavior and concepts are getting more and more peculiar every day.
To close the circle: It's a shame.
