### ISSUE TITLE
How do you connect to EXO with OSX? 

### ISSUE THREAD

**Issue by jmcadams-r7** [MicrosoftDocs/office-docs-powershell#6945]
[Enter feedback here]

With Basic Authentication being depreciated, how can we connect to EXO services with PowerShell on a non-windows device? That hasn't been made clear in any of the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10052620-9909-c335-1913-fdf9db8ab16b
* Version Independent ID: e4be7843-4540-96fd-dcd8-09d6b91a4249
* Content: [Basic auth - Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/basic-auth-connect-to-exo-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jmcadams-r7, the 2.0.4-PreviewX (X=2 or later) versions of the EXO V2 Module support PowerShell Core on non-Windows devices. For more information, see <https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#powershell-core-support-in-the-exo-v2-module>.

It's likely that the 2.0.4 version of the module will be officially released in time for the Basic auth deprecation in the [second half of 2021](https://developer.microsoft.com/office/blogs/deferred-end-of-support-date-for-basic-authentication-in-exchange-online/).

**Comment by jmcadams-r7** [comment]
I just tried 2.0.4-Preview6 and it still has a dependency on WSMan. WSMan, as far as I know isn't supported anymore because it has a dependency on OpenSSH 1.0.x.

**Comment by chrisda** [comment]
@jmcadams-r7, the 2.0.4 version of the module, which supports PowerShell 7, went public on 2/10. Windows and Linux work fine; there appears to be an issue with macOS, and that's being tracked in  #7327.

Also, the subject of this issue is the older, now out of favor Basic auth connection instructions that you shouldn't use anymore. The current connection instructions that you need to use is [Connect to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell).

Thanks for the feedback.

Closing
