### ISSUE TITLE
Small typo in webpage?

### ISSUE THREAD

**Issue by GIT-RDonker** [MicrosoftDocs/office-docs-powershell#7037]
Hi There,

First of all : This piece of documentation has helped me a lot to find the right accesgroups for my collegues. Thank you very much!

However, under the Troubleshooting paragraph (first entry under **These possible causes have the same solution**)I found a small puzzle :
The line states 
You might have entered a cmdlet or parameters that are defined in a role that isn't assigned to anyone by default.

Shouldn't the word _**anyone**_ be replaced by **_any role group_**?

Thanx again for this article!
Greetings, Richard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f0a60b-0a31-dd92-53eb-4f7def6319f3
* Version Independent ID: 06ad3c31-d631-cb66-07e7-380f9f923ff9
* Content: [Find the permissions required to run any Exchange cmdlet](https://docs.microsoft.com/en-us/powershell/exchange/find-exchange-cmdlet-permissions?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/find-exchange-cmdlet-permissions.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/find-exchange-cmdlet-permissions.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@GIT-RDonker, I see what you're saying, but it isn't a typo; it's more of a subtlety (I used the word 'anyone' in similar contexts in the topic).

Of course, role group membership is used to assign RBAC roles to users in the vast majority of cases. But there's nothing to stop an admin from directly assigning an RBAC role to a user. Then, if that admin leaves the company, their successor is left to pick up the pieces.

When I initially wrote the topic, I was very proud of the fact that it worked in common/default and heavily customized environments. In retrospect, I'm not sure how important that is.

I replaced the instances of 'anyone' with 'role group' as you described, and also did some other clean-up to the topic (it's been a long time since I touched it). We'll see if anyone complains (I doubt it).

In the future, instead of opening an Issue, you can modify the topic directly. Someone like me will need to approve your changes before they go live. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
