### ISSUE TITLE
Running Install-Module -Name ExchangeOnlineManagement no valid module

### ISSUE THREAD

**Issue by KSib** [MicrosoftDocs/office-docs-powershell#7062]
Referencing this issue since it's the same as mine, but it's closed and will probably get overlooked https://github.com/MicrosoftDocs/office-docs-powershell/issues/6507

I also tried the same command as @ahamin01  and it definitely doesn't work as written. I'm trying it on Powershell x64 windows 7.1.0 and I see this:

```
PS C:\Users\[redacted]> Import-Module ExchangeOnlineManagement
Import-Module: The specified module 'ExchangeOnlineManagement' was not loaded because no valid module file was found in any module directory.
```

If it does work for you, that's great, but the documentation should be updated in a way that helps people it doesn't work for.

If I run the following command then it does work:

```
PS C:\Users\[redacted]> Install-Module -Name ExchangeOnlineManagement -RequiredVersion 2.0.3

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
```

Also, something I should note is I do get the same error on Powershell that's built into Windows 10

**Comment by KSib** [comment]
Also, something to note to others if they see this: don't use Powershell 7 as it's incompatible with the following command which was certainly interesting to learn. I figured it was an upgrade on the existing powershell, but I was apparently wrong:

`Connect-ExchangeOnline -UserPrincipalName <UPN> -ShowProgress $true`

You'll eventually get an error around a Cryptography DLL.
https://github.com/PowerShell/PowerShell/issues/10473

**Comment by dariomws** [comment]
Hi @KSib, thank you for your feedback.

PowerShell 7 is not supported yet. From [](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#prerequisites-for-the-exo-v2-module):
"Windows PowerShell 5.1 is the latest version of PowerShell that's publicly supported by the EXO V2 module. Support for later versions of PowerShell (and by definition, support for Linux or Mac) is a work in progress*."
"* The 2.0.4-Preview2 version of the module supports PowerShell 7 in Linux and Windows. For more information, see the [PowerShell Core support in the EXO V2](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#powershell-core-support-in-the-exo-v2-module) module section later in this topic."

**Comment by chrisda** [comment]
@KSib, @ahamin01, the intent of the [Connect to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell) topic is to show the steps that you use to connect to Exchange Online PowerShell. The very important prerequisite steps to install the module are covered in the [What do you need to know before you begin?](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps#what-do-you-need-to-know-before-you-begin) section, and you'll notice the first item is:

- The requirements for installing and using the EXO V2 module are described in [Install and maintain the EXO V2 module](exchange-online-powershell-v2.md#install-and-maintain-the-exo-v2-module). The rest of the instructions in the topic assume that you've already installed the module.

Furthermore, right below the first Install-Module command, the following text is visible:

**Note**: If you've already [installed the EXO V2 module](exchange-online-powershell-v2.md#install-and-maintain-the-exo-v2-module), the previous command will work as written.

I purposefully kept that module installation/maintenance information in a separate topic, because a) it's vast, and b) it's bascially a **one-time** process. My thought was, why clutter up the connection instructions with steps that you likely did months before?

More to your point, PowerShell Core support is currently in Preview, and will eventually be more fully incorporated into the EXO V2 module installation instructions (it's there, but sort of treated as a second-class citizen, which will eventually change).

**Comment by KSib** [comment]
Thanks this makes sense. I definitely overlooked that part! 

When I was looking at the previous reply, I followed the link that closed that topic and it still didn't work so I didn't consider I overlooked something else as I expected it would have been in the reply.

This is what was linked: 

> Please try installing the latest version of the module:
> https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#update-the-exo-v2-module

which I tried

but what I needed was right above it. It came off as dismissive when it was basically a "couldn't reproduce" so I wanted to make sure it got more visibility as well. Thanks again!

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @KSib Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
