### ISSUE TITLE
Get-UserBriefingConfig not being replaced 

### ISSUE THREAD

**Issue by paul9955** [MicrosoftDocs/office-docs-powershell#7069]
Hello, I'm a writer for the Workplace Analytics & MyAnalytics products. I've received word from one of my PMs that there is an error on this page (https://docs.microsoft.com/en-us/powershell/module/exchange/get-userbriefingconfig?view=exchange-ps). He said that we need to remove the Note near the top of the page that states "This cmdlet is being replaced by the Get-MyAnalyticsFeatureConfig cmdlet."
If you need more info from this PM, you can reach him at vikgup@microsoft.com.
Thank you,
 - Paul Schafer (v-pausch@microsoft.com)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ba71df-1342-b487-af8b-b95780cd01de
* Version Independent ID: a373b836-a5e6-4755-eb9f-df4cdddd8026
* Content: [Get-UserBriefingConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-userbriefingconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-UserBriefingConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-UserBriefingConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@paul9955, if you have a GitHub account (which you do, because you submitted this issue), then you can remove the offending text. Editing directly on the web is super simple (click the Edit pencil on the topic on docs, then click the Edit pencil again on the topic on GitHub). This is all explained here: <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md#quickly-update-an-article-using-githubcom>.

Also, you likely want to remove the same offending text from the [Set-UserBriefingConfig](https://docs.microsoft.com/powershell/module/exchange/set-userbriefingconfig) topic.

**Comment by paul9955** [comment]
Thank you Chris, I'll give that a try!

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @paul9955 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
