### ISSUE TITLE
PermanentlyClearPreviousMailboxInfo Discontinued? 

### ISSUE THREAD

**Issue by JBines** [MicrosoftDocs/office-docs-powershell#7078]
-PermanentlyClearPreviousMailboxInfo
I could be having a noob day but I think this switch has been discontinued and moved to the Disable-Mailbox testmbx -PermanentlyDisable. If so the documentation needs updating. Seems there is some confusion out there with this failing cmdlet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae09acf-5413-eb3c-e4c7-2481b7b178f5
* Version Independent ID: d0d555a7-de13-0173-7a8c-e13587b334bc
* Content: [Set-User (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-user?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-User.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-User.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by JBines** [comment]
Confirmed: noob day

**Comment by jonwbstr** [comment]
How do you disable mailbox on a user with a license?
You can't
> Cannot Disable-Mailbox for 'User' because this user has a valid license.

How do you disable mailbox on a user without a license? 
You can't?
> The operation couldn't be performed because object 'User' couldn't be found...

Seems like a catch 22

To reset previous mailbox info, we CAN
1. Move user out of AADConnect scope
2. Initiate AADConnect sync (Delete the user from o365)
3. permanently delete the user 
4. Move user back into AADConnect scope
5. Initiate AADConnect sync (recreate user)

if the switch above worked, we would have a 30s fix that required an o365 admin only instead of the current ~15min fix that requires an AADConnect admin and O365 admin.

**Comment by jonwbstr** [comment]
Related to #7028

**Comment by JBines** [comment]
@jonwbstr I believe that if you have the mailbox on-hold even if you remove the license the mailbox will remain and the disable-mailbox cmdlet could work. I found that -PermanentlyClearPreviousMailboxInfo switch would work once no retention polices were applied to the mailbox.  See my comment here https://techcommunity.microsoft.com/t5/exchange-team-blog/permanently-clear-previous-mailbox-info/ba-p/607619

**Comment by chrisda** [comment]
#7208 was fixed and closed (the parameter is available in Exchange Online PowerShell, but it doesn't work, so the parameter is effectively on-premises Exchange only).

Thanks for the feedback.

Closing
