### ISSUE TITLE
Module installation and setup guide link should be in this doc

### ISSUE THREAD

**Issue by loftwah** [MicrosoftDocs/office-docs-powershell#7089]
[Enter feedback here]

I love the docs you guys have put a tonne of work into recently but I've had an issue with finding information about installing, configuring and actually getting going with Powershell first. I want to connect to 365 using the exchange online v2 module, which I had to do a tonne of digging and work to actually get working before I could use the document. A link to somewhere that describes how to do this would be awesome because I doubt there will be too many that persist as long as I did.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@loftwah, I'm sorry to hear you were having trouble. The [Connect to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell) is the first result in Bing and Google when searching for the phrase "Connect to Exchange Online PowerShell". I recently refactored that topic to use the EXO V2 module, since the old Basic auth instructions will eventually stop working and using the module will be the only way you can connect. The intent was to reuse the search results capital of that very old and longstanding Connect to Exchange Online PowerShell topic and get people used to using the module.

The topic that you filed this issue against used to contain both background information, prerequisites, installation instructions, etc. AND connection instructions before I moved the connection instructions into the separate topic.

Is the cross-linking between the two topics lacking? Is there information lacking in either topic? Are there higher level M365/O365 topics where you think links to these EXO V2 module topics would be helpful?

**Comment by loftwah** [comment]
> @loftwah, I'm sorry to hear you were having trouble. The [Connect to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell) is the first result in Bing and Google when searching for the phrase "Connect to Exchange Online PowerShell". I recently refactored that topic to use the EXO V2 module, since the old Basic auth instructions will eventually stop working and using the module will be the only way you can connect. The intent was to reuse the search results capital of that very old and longstanding Connect to Exchange Online PowerShell topic and get people used to using the module.
> 
> The topic that you filed this issue against used to contain both background information, prerequisites, installation instructions, etc. AND connection instructions before I moved the connection instructions into the separate topic.
> 
> Is the cross-linking between the two topics lacking? Is there information lacking in either topic? Are there higher level M365/O365 topics where you think links to these EXO V2 module topics would be helpful?

Hi, I'm sorry I didn't get back to you sooner. I can't remember exactly what the details were but I do remember it feeling a little clunky to get going. I was able to persist and work around whatever it was I was doing. The best I can give you is that I believe I tried to use Powershell 7.x instead of the default Windows 10 version of Powershell. When I switched I was able to use the module the way I expected.

I'm not an expert with PowerShell by any means so it may even be my configuration that caused it. I think if there is a tip or a gotcha warning to users about whatever caused it (I'm happy to share my configurations).

Cheers
Dean

**Comment by chrisda** [comment]
The 2.0.4 version of the module, which supports PowerShell 7 in Windows, macOS and Linux, went public on 2/10, so confusion over PowerShell 5.1 vs. PowerShell 7 should no longer be an issue. All things being equal, I think the current cross linking between the prerequisites topic and the how to connect topic are adequate, but I'm certainly willing to listen to feedback regarding what a where to cross link.

Closing

**Comment by loftwah** [comment]
Cool, thanks for checking it out, it is very much appreciated.
