### ISSUE TITLE
In Step 5, unable to select registered app from Roles and Admin Assignments

### ISSUE THREAD

**Issue by singhkamall** [MicrosoftDocs/office-docs-powershell#7113]
On [App Only Authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps), I followed all 4 steps successfully however, I cannot add my newly created application as an assignment to **Roles and administrators** > **Exchange administrator** > **Add Assignment**.

My registered application:

![image](https://user-images.githubusercontent.com/31941421/105108327-3a42da80-5a77-11eb-81b3-a1460dc39360.png)

When I try to search it within **Roles and administrators** > **Exchange administrator** > **Add Assignment**:

![image](https://user-images.githubusercontent.com/31941421/105108548-bb9a6d00-5a77-11eb-8651-eea9bda86dfd.png)

**Comment by singhkamall** [comment]
Looks like this doc is incomplete. I have solved my problem using this PowerShell command:

`Add-AzureADDirectoryRoleMember -ObjectId xxxxx -RefObjectId xxxxx`

After running it successfully, my app started appearing under Exchange Administrator assignments.

**Comment by dariomws** [comment]
@singhkamall, this is how it looks now when you click on **Add assignments**. You need to click on **No member selected** and there you can select the app.
![image](https://user-images.githubusercontent.com/33589238/106122880-fcf5e100-6137-11eb-8be5-6ffdb1f87db1.png)
I'll update the article.

**Comment by chrisda** [comment]
I just completed a major overhaul of [the topic](https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2) with lots of screenshots to match the current UI. I, to agree that several weeks ago when I started, something was amiss; Step 5 didn't work at all as described. Whatever mojo the Azure AD team was working through seems to have cleared up.

At least for me in my tenant. Please comment here if your UI doesn't match.

Also note, this issue is basically a duplicate of #7068.
