### ISSUE TITLE
Add-TeamChannelUser not recognized (PS module version 1.1.6) 

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#7127]
Hi,

Still like to re-open this. Version 1.1.6 should be GA but that still have no Add-TeamChannelUser CMDLet.

```
PS C:\> Get-Command -Module MicrosoftTeams -Name add*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-TeamUser                                       1.1.6      MicrosoftTeams
```

**Comment by get-itips** [comment]
Hello @Petri-X how are you? Hope you are doing good.

Correct, Add-TeamChannelUser is still in the preview module version and is not in the GA version (yet).

Let me know if I understood your inquiry.

Thanks

**Comment by Petri-X** [comment]
@get-itips 
Oh !? What do you mean by that? When doing installation via PowerShell I'm getting 1.1.6

Also [PS callery ](https://www.powershellgallery.com/packages/MicrosoftTeams/1.1.8-preview)looks like this:
![image](https://user-images.githubusercontent.com/43988151/106160168-33f6e180-618e-11eb-90c8-19d927a798fb.png)
There is a clear differences between 1.1.6 and others. And see the amount of downloads, and you are saying that is having bugs..?

So what is the valid version then?

**Comment by get-itips** [comment]
Hello @Petri-X 

Thanks for returning! I hope you have a great day.

In this article, you can see the difference between the modules and how to install a specific version.

https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-overview

> Teams PowerShell is available on PowerShell Gallery in two release types.
General Availability (GA): Production-ready cmdlets, updated monthly.
Public Preview: Early access to features. May be updated more frequently than GA.

As here we are limited to **documentation issues**, did you identify a documentation issue I can take care of? Otherwise, if you want to reach the team behind the development of the Teams Ps module, I recommend https://microsoftteams.uservoice.com/ 

Thank you

**Comment by Petri-X** [comment]
Aah, okay, so you are saying your team has remove that CMDLet from the GA module.

[CMDLet statuses](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes#cmdlet-availability)

Sorry, perhaps I read this incorrectly :D

**Comment by get-itips** [comment]
> Aah, okay, so you are saying your team has remove that CMDLet from the GA module.
> 
> [CMDLet statuses](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes#cmdlet-availability)
> 
> Sorry, perhaps I read this incorrectly :D

Hello @Petri-X 
The table that you shared says that Add-TeamChannelUser is not in the GA version of the module (currently the 1.1.6) and is available in the Public Preview version.

Thanks for returning and sharing your feedback!
