### ISSUE TITLE
Can't authenticate with Microsoft365 and Powershell.

### ISSUE THREAD

**Issue by the-epoch** [MicrosoftDocs/office-docs-powershell#7200]
Constantly get an error that I'm using the wrong username and password trying to connect to Office 365 with Powershell.
e.g. 
```
New-ExoPSSession: C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.3\ExchangeOnlineManagement.psm1:426
Line |
 426 |  … PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | AADSTS50126: Error validating credentials due to invalid username or password. Trace ID:
     | 7c780f3c-28f6-4b23-aaa0-9cf934787a00 Correlation ID: e2d224cd-c1a1-4a08-8229-67da6bb7e299 Timestamp:
     | 2021-02-01 23:38:54Z.
```
e.g.
```
PS C:\Program Files\PowerShell\7> $UserCredential = Get-Credential

PowerShell credential request
Enter your credentials.
User: netadmin@mydomainname.onmicrosoft.com
Password for user netadmin@mydomainname.onmicrosoft.com: ****************

PS C:\Program Files\PowerShell\7> $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
New-PSSession: [outlook.office365.com] Connecting to remote server outlook.office365.com failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.
```

e.g.
with Modern Authentication ([see pic here](https://imgur.com/a/hUhNOrL) )
```
Sign in to your account
Microsoft
<- netadmin@mydomainname.onmicrosoft.com
**Enter password** 
Your account or password is incorrect. If you don't 
remember your password, reset it now.
Password
Forgot my password 
Sign in with another account 

```

However, If I login to Microsoft365 portal with the same (administrative) username and password it works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@the-epoch, you followed the prerequisites information [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2) and then the connection instructions [here](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell#connect-to-exchange-online-powershell-using-modern-authentication)?

It should work.

Beware about [disabling ExO PowerShell access](https://docs.microsoft.com/powershell/exchange/disable-access-to-exchange-online-powershell), and possibly [Client Access Rules](https://docs.microsoft.com/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules) that block PowerShell. If you're using the module, lack of Basic auth isn't an issue since the module uses modern auth.

**Comment by the-epoch** [comment]
@chrisda Sorry for wasting your time, seems it was a weird pebkac (my fault) error with copying passwords and my lastpass sync.
