### ISSUE TITLE
Add "Recipients" and "AttachmentNames" properties as part of the output of the cmdlet in the Description area

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/office-docs-powershell#7212]
In the Description area https://docs.microsoft.com/en-us/powershell/module/exchange/get-dlpdetailreport?view=exchange-ps#description, we do not have the "Recipients" and "AttachmentNames" properties mentioned, although they have been added per https://o365exchange.visualstudio.com/IP%20Engineering/_workitems/edit/1359643.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54810913-01ba-f2ed-76dd-3d810e4beeda
* Version Independent ID: 1fd3a291-d8bd-13b9-785f-8fa88170c1f7
* Content: [Get-DlpDetailReport (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-dlpdetailreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-DlpDetailReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-DlpDetailReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @Alex-Catalin, thank you for your feedback. I'll try to confirm this information as I don't have access to https://o365exchange.visualstudio.com/IP%20Engineering/_workitems/edit/1359643.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=Alex-Catalin

**Comment by Alex-Catalin** [comment]
Hi Dario,

My MS account should be linked to the github account. You gave me these steps before and I followed them to link the 2 accounts 😊.

Thank you,

Alexandru Cazacu
Sr. Support Escalation Engineer
Exchange Online
M365 EMEA Customer Service & Support
alexandru.cazacu@microsoft.com<mailto:alexandru.cazacu@microsoft.com>
9 AM - 6 PM (GMT+2)
[cid:image001.png@01D70469.8E289360]
