### ISSUE TITLE
Disable-RemoteMailbox does not delete the mailbox anymore

### ISSUE THREAD

**Issue by FrankPlawetzki** [MicrosoftDocs/office-docs-powershell#7214]
This article states in various places, that using this command the mailbox will be removed in EXO. This is no longer true.
When you remove the license and run Disable-RemoteMailbox, the mailbox stays in EXO. Only logon for the user is disabled

**Comment by dariomws** [comment]
Hi @FrankPlawetzki, thank you for your feedback and help us to improve docs.microsoft.com.

I think it's still the right way to remove a mailbox in a hybrid environment:

1. Remove the license
2. Run Disable-RemoteMailbox

The mailbox will remain as soft-deleted for 30 days.

The following sentence appears in the article:
"Remove a cloud-based mailbox but keep the associated on-premises user account. To do this, you first need to remove the Exchange Online license for the mailbox. Otherwise, the mailbox won't be removed. The on-premises mail user is automatically converted to a regular user object. You can mail-enable the on-premises user object using the Enable-MailUser cmdlet."

Disable-RemoteMailbox won't remove the Exchange Online mailbox if you didn't remove the license.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @FrankPlawetzki Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by FrankPlawetzki** [comment]
Seems my statement was based on incorrect pieces of information I got. Sorry for that

**Comment by FrankPlawetzki** [comment]
see above comment

**Comment by FrankPlawetzki** [comment]
Seems my statement was based on incorrect pieces of information I got. Sorry for that

**Comment by dariomws** [comment]
Don't worry @FrankPlawetzki! We appreciate that you tried to help and encourage you to do the same in the future.

**Comment by SM19-Tech** [comment]
Hi @dariomws ,

We have a scenario where the user left the company and rejoined..... so his account in AD was earlier suspended and now restored as he rejoined. We have a hybrid environment and accidentally O365 mailbox is provisioned for this user whereas he still has his On-premise Exchange mailbox in Disconnected State. If we remove the license and disable the O365 mailbox via Disable-RemoteMailbox it still has mailbox on O365 as you said and also has On-premise mailbox that was reconnected. So 2 mailboxes ... any suggestion how to permanently remove the O365 mailbox without going through soft deleted process. further suggestion will be highly appreciated.... Thanks
