### ISSUE TITLE
2.0.4-Preview9 Connection Issue

### ISSUE THREAD

**Issue by whatanatta** [MicrosoftDocs/office-docs-powershell#7355]
Attempting use connect-exchangeonline command not working as intended, depending on the circumstance. Running the command by itself is fine. Running it in a script is not either A: not launching the credentials window or B: after credentials window it doesn't continue on with the rest of the script - depending on how it's being ran. 

This issue started with 2.0.4. I figured out it was this version by installing version 2.0.3 and my script started working fine again. I have no idea how to provide further information in this. Please let me know what I can do to help out.

**Comment by whatanatta** [comment]
Since I'm unable to recreate it outside of my script, I'll provide a sanitized version of the script. Before it gets thrown back into my face about "it's probably just your script", I emphasize that I uninstalled 2.0.4-preview9 and installed 2.0.3 and the script started working just fine again.

When script is ran, check the box "Disable - Check here if user is being disabled" and input whatever you want in the box below that called "INsert username of user to be terminated here". Then click on "Enter". Expected results: Exchange module appears to start running but the credentials box does not appear. This portion of the script is on line 397. 

A weird alternative would be to manually run line 397 in ISE, exit the credentials box when it appears (or authenticate fully, doesn't matter), then run the entire script while still in same ISE session. Expected results: Credentials box will appear but does nothing after authentication. 
[Create and Disable Sanitized Accounts vs 1.8 - Copy.txt](https://github.com/MicrosoftDocs/office-docs-powershell/files/6064325/Create.and.Disable.Sanitized.Accounts.vs.1.8.-.Copy.txt)

**Comment by whatanatta** [comment]
I just realized that 2.0.4 has been released for a month. That'd be the version I was on, not Preview9.

**Comment by yogkumgit** [comment]
If you do not see any document update, please go ahead and close this one. Thanks

**Comment by dariomws** [comment]
@whatanatta, thank you for your feedback. Here we are limited to documentation issues and improvements.

In this case, if you are experiencing this issue outside the script using the latest version, I recommend opening a support ticket to report it.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

You can also provide feedback about this issue on the [product team blog](https://techcommunity.microsoft.com/t5/exchange-team-blog/bg-p/Exchange).

Version 2.0.4 starts using a different authentication library, and I think this issue is well known by the product team and was reported before:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/7326

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @whatanatta Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
