### ISSUE TITLE
Connect-MicrosoftTeams Ignores AccountId

### ISSUE THREAD

**Issue by SOM-SPeters** [MicrosoftDocs/office-docs-powershell#7374]
After upgrading to MicrosoftTeams 2.0.0 `Connect-MicrosoftTeams -AccountId admin@mytenant.onmicrosoft.com` no longer obeys -AccountId. Testing with -Identity and -AccountId returns the correct users but gives `Get-Team : Unauthorized in /v1.0/groups/ endpoint`.

**Comment by shivtorov** [comment]
Version 2 of the module introduced breaking changes for connect experience.

As @SOM-SPeters said above, one of the popular login methods was to run `Connect-MicrosoftTeams -AccountId admin@mytenant.onmicrosoft.com` to allow for MFA verification but save manually typing login name. It is not working anymore since upgrade to v.2.

It would be great if the cmdlet article can be expanded and include one example per parameter set to demonstrate how to use various authentication methods.


* Content: [Connect-MicrosoftTeams (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @SOM-SPeters and @shivtorov 
Thanks for your feedback. I noticed that too in 2.0.0, however as here we are limited to documentation changes, I will add some more connection examples to the article, and I'll try to pass this to the Team behind the Ps module.
Thank you
