### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jamiepassa** [MicrosoftDocs/office-docs-powershell#7401]
This does not work for Exchange Online/Office 365. 

Yes I am a Global Admin and Have the AddressLists role under Organization Management.

The term 'New-GlobalAddressList' is not recognized as the name of a cmdlet, function, script file,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 802f63aa-9fc7-087a-9b81-b604e1de3968
* Version Independent ID: 7ce3633b-e9c4-2753-2aed-c3ab2a075a2e
* Content: [New-GlobalAddressList (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-globaladdresslist?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-GlobalAddressList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-GlobalAddressList.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jamiepassa, barring some type of transient problem, a connection problem (you are connected to Exchange Online PowerShell, yes?), or temporary disabling on our end due to a security/support issue (which happened recently with Import-TransportRuleCollection) it should work.

See [this topic](https://docs.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions) for troubleshooting.

Otherwise, you might need to open a support case.

I presume you're using the latest version of the [EXO V2 module](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2) (v2.0.4) in a supported version of PowerShell (5.1 or 7) on a supported OS (Windows 10 = 5.1 or 7; Ubuntu 18.04/20.04 = 7).

**Comment by jamiepassa** [comment]
Hi Chris, thanks for the fast response. Yes I have a ticket open, however, its been open for a few days. They keep bouncing it around and cant figure out why, but they see the same issue on their side. Its not transient, however, as its been happening for the past 2 weeks. Yes I am using EXOP session due to MFA requirement.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @jamiepassa Hope this comment is helpful for you. Thanks for opening a service ticket in your tenant and please keep following with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
