### ISSUE TITLE
Exchange Online Remote Powershell: Enable-OrganizationCustomization failing

### ISSUE THREAD

**Issue by barclayadam** [MicrosoftDocs/office-docs-powershell#7519]
I'm really not sure where best to ask this question. This GitHub repo was the closest to anything related to Exchange Online Remote Powershell, but I do not know if this is a documentation issue (in that I'm missing something I need to be doing) or a product issue of sorts.

I am connecting to Exchange Online to configure email flows (outbound connectors etc.), and as part of that I need to run the command `Set-HostedConnectionFilterPolicy`. On a new tenant that fails with the message that I need to run `Enable-OrganizationCustomization`.

I am doing this using Powershell SDK 7.0.4 via. C#, connecting using an access token granted to the same application the cmdlets use and the same `New-PSSession` and `Import-PSSession` calls (distilled) as the cmdlet:

```powershell
$PSSession = New-PSSession `
    -AllowRedirection `
    -Authentication "Basic" `
    -ConfigurationName "Microsoft.Exchange" `
    -ConnectionUri $ConnectionUri `
    -Credential $Credential `
    -Name "RemoteExchangeOnline"

Import-PSSession $PSSession -AllowClobber -DisableNameChecking -CommandName @("*") -FormatTypeName @("*")
```

The issue is an error, `The role assignment policy "Default Role Assignment Policy" wasn't found. Make sure that you typed the identity correctly`, that gets thrown when I then try to execute `Enable-OrganizationCustomization`, coming from the below source which is, I'm presuming, part of the remote cmdlet:

```powershell
if (!$AdvancedHydrateableObjectsSharedEnabled) {
    $unifiedRAP = ($NewServicePlanSettings -eq $null -and -not $ServicePlanSettings.Organization.PerMBXPlanRoleAssignmentPolicyEnabled) -or ($NewServicePlanSettings -ne $null -and -not $NewServicePlanSettings.Organization.PerMBXPlanRoleAssignmentPolicyEnabled)
    $raPolicyName = [Microsoft.Exchange.Data.Directory.SystemConfiguration.RoleAssignmentPolicy]::DefaultRoleAssignmentPolicyName
    $policyDescription = [Microsoft.Exchange.Data.Directory.SystemConfiguration.RoleAssignmentPolicy]::PrecannedRoleAssignmentPolicyDescription
    $raPolicy = $null
    
    Write-ExchangeSetupLog -info ("PerMBXPlanRoleAssignmentPolicyEnabled Task; unifiedRAP=" + $unifiedRAP)
    
    if($unifiedRAP) 
        #Trying to find local RAP object with default name 
        $raPolicy = Get-RoleAssignmentPolicy -DomainController $RoleDomainController -Organization $RoleOrganizationHierarchicalPath -IgnoreDehydratedFlag | Where {$_.Name -eq $raPolicyName}
     	Write-ExchangeSetupLog -info ("PerMBXPlanRoleAssignmentPolicyEnabled Task; raPolicyFound=" + ($raPolicy -ne $null))
    } 

    if($unifiedRAP) { 
     	if($raPolicy -eq $null) { 
     		Write-ExchangeSetupLog -info ("Creating Default RAP " + $raPolicyName)
     		$raPolicy = New-RoleAssignmentPolicy ` -Name $raPolicyName ` -DomainController $RoleDomainController ` -Description $policyDescription ` -IsDefault ` -IgnoreDehydratedFlag ` -Organization $RoleOrganizationHierarchicalPath
    	} 
    } 

    Write-ExchangeSetupLog -info ("PerMBXPlanRoleAssignmentPolicyEnabled Task looping through mailboxplans:" + $ServicePlanSettings.MailboxPlans.Count)

    foreach ($mp in $ServicePlanSettings.MailboxPlans) { 
     	if($mp.Instance -eq $null) { 
     		Write-ExchangeSetupLog -error ($mp.Name + " MailboxPlan instance value is not set")
     	} 

     	#MailboxPlan has non-null RoleAssignmentPolicy property only if RAP link is stamped explicitly - no implicit default there 
     	if($mp.Instance.RoleAssignmentPolicy -ne $null -and $unifiedRAP) { 
     		Write-ExchangeSetupLog -info ("MailboxPlan already with RAP " + $mp.Name)
     		continue
    	} 

    	if(!$unifiedRAP) {
    		$raPolicyName = "RoleAssignmentPolicy-" + $mp.Name
    		$raPolicy = Get-RoleAssignmentPolicy -DomainController $RoleDomainController -Organization $RoleOrganizationHierarchicalPath -IgnoreDehydratedFlag | Where {$_.Name -eq $raPolicyName}
    		if($raPolicy -eq $null) { 
    			Write-ExchangeSetupLog -info ("Creating RAP for " + $mp.Name)
    			$raPolicy = New-RoleAssignmentPolicy -Name $raPolicyName -DomainController $RoleDomainController -Description $policyDescription -Organization $RoleOrganizationHierarchicalPath -IgnoreDehydratedFlag
    		} 
    	} 

    	Set-MailboxPlan -Identity $mp.Instance.Identity -RoleAssignmentPolicy $raPolicy.Identity -DomainController $RoleDomainController
    } 
} 
```

I have seen two future outcomes of this failing:

 1. For one tenant I manually connected via. a local Powershell instance and the cmdlet, and ran `Enable-OrganizationCustomization` fine
 
 2. For a different tenant I did not run it manually. When calling `Get-OrganizationConfig` I could see that `IsDehydrated` returned `$false`, indicating the command had been run (as per https://docs.microsoft.com/powershell/module/exchange/enable-organizationcustomization). If I then tried to run `Set-HostedConnectionFilterPolicy` in the automated session it threw an error o say I needed to run `Enable-OrganizationCustomization`, contrary to what the config said. Running that same cmdlet manually once worked, and after that the automated method also started to work.

**Comment by chrisda** [comment]
@barclayadam, I'm not sure how connecting/authentication works with C#, but the connection method that you're using is the old [Basic auth method](https://docs.microsoft.com/powershell/exchange/basic-auth-connect-to-exo-powershell), which is eventually going away next year. It was supposed to go away this year, but COVID happened. See [this announcement](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-february-2021-update/ba-p/2111904) for details.

The new/preferred connection method always uses the [EXO V2 module](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell). The EXO V2 module always uses Modern authentication and also supports multi-factor authentication (MFA), [certificate based authentication (CBA)](https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2) for unattended scripts, and [additional PowerShell 7 log in experiences](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell#powershell-7-log-in-experiences).

All of that being said, and regardless of how you are connecting to ExO PowerShell, there are lots of configuration actions that require an already hydrated organization. If you're trying to build a script or use automation in different organizations, you should start with a check of the hydration state (`Get-OrganizationConfig | FL IsDehydrated`). If the result is True, run `Enable-OrganizationCustomization` and wait for it to complete (and error out if it can't complete); otherwise continue with the other actions in the script. You get the same warning if you ran an "offending" cmdlet like Set-HostedConnectionFilterPolicy manually.

And, to be clear, Exchange Online PowerShell is the best place to hydrate your org.  The only issues I've had recently seemed to be related to very new organizations (after a couple of hours, it worked fine).

In the (now) classic Exchange admin center (EAC), if you did something that required hydration, it would interrupt your action and hydrate for you in a dialog box with a progress bar:

![Hydrating old EAC](https://user-images.githubusercontent.com/33166947/113931485-5cf7ac00-97a7-11eb-8d72-5824015c36ea.PNG)

In the Security & Compliance Center, you get a similar interruption dialog, but the hydration act always seems to error out in the multiple situations where I've encountered it.

For reference, this is the old [error topic](https://docs.microsoft.com/previous-versions/exchange-server/exchange-150/jj156967(v=exchg.150)) that was linked to on the EAC dialog when there was an error.

Does this hep?

**Comment by barclayadam** [comment]
Hi @chrisda 

Sorry for delay in getting back to you. 

Further to the above, we have been able to replicate this without connecting via. C# and instead only using plain Powershell (Windows 10, PowerShell v5.1), and the Exchange Management module v2.0.4 (and v0.4578.0).

We would only run two commands:

````powershell
Connect-ExchangeOnline
Enable-OrganizationCustomization
`````

That is to say, that the way we connect was *not* responsible for the problem. I'm not really sure where to go with this. If we retry the command in most cases it will work the second time, but it being so unreliable makes it very hard for us to do this in a safe way.

We have seen this problem most often on newer tenants, but have seen the issue on ones that were created days in the past too.

How can we progress this further with a relevant team?

Powershell version for more info:

````
Name                           Value
----                           -----
PSVersion                      5.1.19041.906
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.906
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
````

**Comment by chrisda** [comment]
@barclayadam, your best way forward is to open a support case.
