### ISSUE TITLE
Get-TeamChannelUser is not a valid cmdlet (yet?)

### ISSUE THREAD

**Issue by gabrieljtaylor** [MicrosoftDocs/office-docs-powershell#7534]
This documentation seems great, however the cmdlet it is documenting, Get-TeamChannelUser, is not present in the latest version (v2.0.0) of the MicrosoftTeams PowerShell Module available on the PowerShell Gallery at the time I make this post.

As you can see in the following image, I have v2.0.0 of the MicrosoftTeams PowerShell module, and this command doesn't exist:

![image](https://user-images.githubusercontent.com/8386413/113332619-0130ad00-92e7-11eb-8285-d5480177535b.png)

Should the release of this documentation be delayed until the update containing the command is released, or is there a bug in the module where the command should be present but is not exposed or available to users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f95f52f4-85d0-c4bf-e807-36c1fe72c806
* Version Independent ID: 28ecb86c-661d-c0ee-6b2c-956c97d02352
* Content: [Get-TeamChannelUser (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamchanneluser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by Markus-Hanisch** [comment]
@gabrieljtaylor 
I currently struggle with the same issue ... 
Seriously, running different Teams module versions side by side shall be better documented because this issue was opened several times in the past: 
- #7127 
- #6723
- #6549

Lessons learned:
The availability of Cmdlets differs from module version to version. The link below shows if a Cmdlet is available in Public Preview or in GA:
https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes#cmdlet-availability

However, based on the that information, I installed the [v2.1.0-preview](https://www.powershellgallery.com/packages/MicrosoftTeams/2.1.0-preview), where the **Package Details** > **Cmdlets** states that the cmdlet `Add-TeamChannelUser` shall be included.

However, I still face the same issue.
In some of the related issues it was stated to use version `1.1.3-preview` or `1.1.5-preview`

**Comment by Markus-Hanisch** [comment]
@gabrieljtaylor 
FYI: The cmdlet availability table on the release notes documentation page has been removed by one of the recent commits:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/124051613c1eb00b0908f0909fab6c6c7aae0df8#commitcomment-49553187
