### ISSUE TITLE
This command (Add-TeamChannelUser) has not been implemented in version 2.0.0 of the package. Is there a plan to implement it? If not, wouldn't it be a good idea to say that in the documentation?

### ISSUE THREAD

**Issue by kristjan-halldorsson** [MicrosoftDocs/office-docs-powershell#7600]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd91d571-ca88-5766-2666-d6a4d34cdbed
* Version Independent ID: 2481b258-b593-e323-90f0-e9ca6e7797bf
* Content: [Add-TeamChannelUser (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by Markus-Hanisch** [comment]
@kristjan-halldorsson 
The availability of Cmdlets differs from module version to version. 
There used to be a Cmdlet availability table on the Release notes documentation page, illustrating which Cmdlet is available in Public Preview or in GA: 
https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes#cmdlet-availability
However, within the last couple of days it has been removed by one of the recent commits: 
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/124051613c1eb00b0908f0909fab6c6c7aae0df8#diff-dfcd8ba1c2db27cb53f8e6d349ca64b05d4fd50484b55cf578365217a62d0fe9
Don't ask me why.

Based on that information, I installed the v2.2.0-preview, where the Package Details > Cmdlets states that the cmdlet Add-TeamChannelUser shall be included. And it works like a charm.

**Comment by kristjan-halldorsson** [comment]
Thank you, excellent.
I'll try it out.

**Comment by MilutinPP** [comment]
Hi I am fresh PS user trying to use PS with MS Teams. I can not program myself.  My problem is that I can't install certain previews. At the moment I am using 2.0.0 version, but fail with 2.2.0-preview (current version). And exactly this version I need because of certain cdmlets. 

PS version I use is 5.1.18362.1171, MS Teams cdmlet 2.0.0.  

To upgrade to 2.2.0-preview I enter this here: Install-Module -Name MicrosoftTeams -AllowPrerelease

https://www.powershellgallery.com/packages/MicrosoftTeams/2.2.0-preview

I get the following error message: 
Install-Module : No parameter was found that matches the parameter name "AllowPrerelease".
In line:1 character:37
Install-Module -Name MicrosoftTeams -AllowPrerelease
CategoryInfo : InvalidArgument: (:) [Install-Module], ParameterBindingException
FullyQualifiedErrorId : NamedParameterNotFound,Install-Module

When I try to install with: Install-Module -Name MicrosoftTeams -RequiredVersion 2.2.0-preview -AllowPrerelease 
I get this error message:

Install-Module : The argument transformation for the "RequiredVersion" parameter cannot be processed. The value "2.2.0-preview" cannot be converted to the type "System.Version".
type. Error: "The input string has the wrong format."
In line:1 character:54
ll-Module -Name MicrosoftTeams -RequiredVersion 2.2.0-preview -AllowP
CategoryInfo : InvalidData: (:) [Install-Module], ParameterBindingArgumentTransformationException
 FullyQualifiedErrorId : ParameterArgumentTransformationError,Install-Module

Can someone help me and clarify what I am doing wrong and what should I do to make it work. It's my 2 day with PS and still struggling with simple things. Thanks in advance

**Comment by get-itips** [comment]
Hello @kristjan-halldorsson how are you? hope you are doing good.
As @Markus-Hanisch Markus kindly explained the availability of cmdlets differs from version to version and it is right that there was a table describing which cmdlet was included in which version. Personally, I maintain two environments, one with GA version and one with Public Preview, but, that is my personal choice.
@MilutinPP Seems that you need to make sure you meet the prerequisites described [here](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install) ([PowerShellGet](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-5.1))
Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @kristjan-halldorsson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
