### ISSUE TITLE
Delegates and meeting requests

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/office-docs-powershell#7847]
Hello,

the Add-MailboxFolderPermission cmdlet has the parameter "SharingPermissionFlags".
When using the outlook client to assign a delegate, after assigning the persmissions and checking the "Delegate recieves..." checkbox I have three more options:
<img width="433" alt="image" src="https://user-images.githubusercontent.com/62641471/119994112-93de8700-bfcc-11eb-84df-0185fde8d152.png">
Which of these options is set when I use the command "Add-MailboxFolderPermission -SharingPermissionFlags Delegate"
And how can explicitly set one of these three options using Powershell?

best regards
joerg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1a893c8-66de-1f8a-f8d2-aa573379e778
* Version Independent ID: 1c32c637-d003-820c-594f-a9adc9c353d9
* Content: [Add-MailboxFolderPermission (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/add-mailboxfolderpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@joergrenn, I did some investigation about this a long time ago (Outlook 2010 days), and I determined that you can't set those options in PowerShell (the last bullet). Luckily, I saved my findings:

- The delegate permissions can be duplicated using the Add-MailboxFolderPermission and the -AccessRights parameter. The values **Editor**, **Reviewer** and **Author** are available just like Outlook.
  - Using **Get-MailboxFolderPermission**, delegate access permission assigned using Outlook is indistinguishable from delegate access assigned using **Add-MailboxFolderPermission**.
  - **Add-MailboxFolderPermission** has lots of additional permissions and roles (combinations of permissions) that aren’t available in Outlook.
  - If you use **Add-MailboxFolderPermission** to add permissions, those permissions aren’t visible in Outlook under the delegate access settings. However, the user can open the mailbox folder. This will cause confusion: why do settings made by Outlook appear in PowerShell, but settings made by PowerShell don’t show up in Outlook? **[chrisda: Not sure if this is still true?]**
- I can find no way using Exchange PowerShell to duplicate (or even see) any of the following Outlook delegate access settings:
  - Delegate receives copies of meeting-related requests sent to me **[chrisda: Fixed in Exchange Online by the _SharingPermissionFlags_ parameter and the `Delegate` value.]**
  - Delegate can see my private items **[chrisda: Fixed in Exchange Online by the _SharingPermissionFlags_ parameter and the `CanViewPrivateItems` value.]**
    Deliver meeting requests addressed to me and responses to meeting requests where I am the organizer to:
    - My delegates only, but send a copy of meeting requests and responses to me **[chrisda: One of these 3 values has to be used for `-SharingPermissionFlags Delegate`. If I had to guess, I would guess this one.]**
    - My delegates only
    - My delegates and me

![image](https://user-images.githubusercontent.com/33166947/120013602-cae57600-bf95-11eb-8e86-326b0cd4f04c.png)

![image](https://user-images.githubusercontent.com/33166947/120013648-d9339200-bf95-11eb-82f0-354d6c54980a.png)

**Comment by joergrenn** [comment]
@chrisda Thanks for the information.
I also did some research and apparently you can set these values via EWS:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.exchange.webservices.data.meetingrequestsdeliveryscope?view=exchange-ews-api
I also read somewhere that it is not possible to use the Add-MailboxFolderPermission command for this, because it is a setting that applies for all delegates at the same time.
Maybe it would be a good idea to add this information, or at least a note to the documentation of the Add-MailboxFolderPermission cmdlet.

**Comment by chrisda** [comment]
@joergrenn, OK. Done.

Thanks for the feedback.

Closing
