### ISSUE TITLE
Get-MailboxExportRequest -BatchName AcceptWildCardCharacter false?

### ISSUE THREAD

**Issue by TenkaiDoki** [MicrosoftDocs/office-docs-powershell#7977]
Hello, 

In the BatchName parameter description is stating "Accept wildcard characters: False" 

But calling Get-MailboxExportRequest -Batchname "Batchnamestart*****" does work.

Maybe it is a misunderstanding of the "Accept Wildcard Character" from my part? 

Cheers, 

Aurélien

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e8826dd-9a2b-c067-b7d3-cfa239e753c6
* Version Independent ID: a9ca32ee-03cf-421f-15d9-41174ab0525b
* Content: [Get-MailboxExportRequest (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailboxexportrequest?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Get-MailboxExportRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MailboxExportRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@TenkaiDoki, as I understand it, that  "Accept Wildcard Character" property never seems to populate correctly, and is always False, even when the parameter accepts wildcard characters. In looking at the [relevant platyPS utility issue](https://github.com/PowerShell/platyPS/issues/202), this issue appears to have been fixed in January ,but that only works if the cmdlet code populates this property correctly.

So what does this mean for Exchange cmdlets? Unknown. We would need to re-dump all cmdlets to markdown topics and find/compare/fix those parameters  where `Accept wildcard characters: False` but it should be `Accept wildcard characters: True`.

With the Identity or identifier parameter in a Get- cmdlet, you can always try a single trailing \* to see if it works. If a trailing \* works, then you can see if a leading \* or multiple \*'s work.

**Comment by yogkumgit** [comment]
@TenkaiDoki Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
