### ISSUE TITLE
ShowConversationAsTree vs. ConversationSortOrder 

### ISSUE THREAD

**Issue by pirminf** [MicrosoftDocs/office-docs-powershell#8023]
From the descriptions it seems that the these parameters have redundant functionality: Both have an impact on how messages are sorted in the reading pane:

- ShowConversationAsTree
- ConversationSortOrder 

ConversationSortOrder seems to provide more options. However to me it is unclear if/how these two parameters interact.

thanks for clearification
Pirmin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d9fd24-705e-4fa4-7ab0-9c35c31b013e
* Version Independent ID: 9cab50c8-7f41-40e2-ae3f-1be6ae94b28e
* Content: [Set-MailboxMessageConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxmessageconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@pirminf, this is likely the same as the View options in Outlook:

- _ShowConversationAsTree_ corresponds to **Show as Conversations**: The first message is farthest to the left, then replies are indented to the right below that first message:

  ![image](https://user-images.githubusercontent.com/33166947/125361108-b5e45c80-e321-11eb-97fc-1c9b1fb4b63a.png)

- _ConversationSortOrder_ likely controls how the individual conversations (the parent or "left-most" messages) sort.

I can see the confusion due to the presence of the `Tree` value for _ConversationSortOrder_. `Tree` likely means newest tree on top, as opposed to _TreeNewestOnBottom_.

I've used Outlook for a long time, and the combinations of View settings was always hit and miss and required a lot of experimentation.

**Comment by chrisda** [comment]
Closing due to lack of response.

Thanks for the feedback.
