### ISSUE TITLE
Can't filter with a wildcard at the start of the search string - HOW DUMB IS THAT!

### ISSUE THREAD

**Issue by EngineerHGH** [MicrosoftDocs/office-docs-powershell#8046]
THIS IS A COMPLAINT... 

Dear Microsoft, 

You've had 5 years to fix this, one of the most used filter/search requirements needed. We just want to filter something like this for Dynamic Distribution Lists "-like '*@mydomain.com'".

Please can you explain to the community why this is so hard for you to deliver? Don't just say because it's unsupported... It's just code behind the scenes and anything can be done in code. I would go as far as to request "-match <regex>" but I wouldn't want to be unreasonable now!!!

**Comment by chrisda** [comment]
@EngineerHGH, I remember ~ 10+ years ago when this behavior was taken away. As I recall, the leading \* was too resource intensive in the datacenters and was negatively affecting performance.

It doesn't ease the pain, but that's why you can't lead with an \* in filters in the cloud. It still works fine in on-premises Exchange environments.

**Comment by chrisda** [comment]
Closing due to lack of response and no actionable outcomes for documentation.
