### ISSUE TITLE
Get-Whiteboard -UserId throws gateway error

### ISSUE THREAD

**Issue by vellabati** [MicrosoftDocs/office-docs-powershell#8125]
[Enter feedback here]
In an attempt to find out whiteboard usage in our tenant, i was getting whiteboard for all users and it errored out in the middle with gateway error. I wish there is a flag to return all whiteboards in the tenant and corresponding owners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8a6935c-013b-7196-1f41-434c4486d382
* Version Independent ID: 22971c35-eeda-ee3a-4cd8-2df1af8f43f2
* Content: [Get-Whiteboard (MicrosoftWhiteboardAdmin)](https://docs.microsoft.com/en-us/powershell/module/whiteboard/get-whiteboard?view=whiteboard-ps)
* Content Source: [whiteboard/whiteboard-ps/whiteboard/Get-Whiteboard.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/whiteboard/whiteboard-ps/whiteboard/Get-Whiteboard.md)
* Service: **whiteboard-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @vellabati how are you? Hope you are doing good.
Here, we are limited to documentation changes and fixes, is there any special fix you see to documentation?
Otherwise, and please corrent me if I am wrong, your inquiry looks more suitable to uservoice, please follow here for directions https://support.microsoft.com/en-us/topic/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a and https://whiteboard.uservoice.com/
Thank you

**Comment by yogkumgit** [comment]
@vellabati  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
