### ISSUE TITLE
Connect-ExchangeOnline fails with ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by wcarson** [MicrosoftDocs/office-docs-powershell#8222]
Connect-ExchangeOnline fails with ArgumentOutOfRangeException sometimes** when running from the command line and always when run as part of a script.  The command fails with the following exception/stack trace:

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession.SetClientEnvData()
   at Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession.ProcessNewConnection()
   at Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
```

The relevant code that triggers the exception is very basic

```powershell
$creds = Get-Credential #login uses a @{tenant}.onmicrosoft.com UPN
Connect-ExchangeOnline -Credential $creds
```

As mentioned above, this always fails when run as part of a script, but only sometimes when run from the command line. What seems to happen is that it will work from the command line until I run it as part of a script. After that, it won't work from the command line either, failing with the same error.

**Comment by chrisda** [comment]
@wcarson, I would suggest trying a different method to connect:

PowerShell 7: <https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell#inline-credentials>

<https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2>

**Comment by wcarson** [comment]
@chrisda - Thank you for the feedback. I'll give the certificate-based auth a shot as described in the 2nd link as a workaround. However, I'd prefer to use the credentials approach as it's more in line with other related scripts we use (e.g. MSOnline module). Any idea what could be causing the exception when using credentials? Seems like a bug rather than a usage issue.

-Wayne

**Comment by chrisda** [comment]
@wcarson, it could very well be a bug. You can open a support case and/or ask for assistance as described [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#report-bugs-and-issues-for-the-exo-v2-module).

Also, worth mentioning that the latest official version of the EXO V2 Module is 2.0.5, and there's also a 2.0.5-Preview2 version available that you could try. See [Update the EXO V2 Module](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#update-the-exo-v2-module).

Generally speaking, a way to simplify (and possible secure) scripts is to leave the connection part out of them; just connect manually first and then run the script. Of course, there are scenarios where you can't do that because connecting to different PowerShell environments simultaneously is an important part of the actions in script.

I'm not sure how helpful this is, but we have [this topic](https://docs.microsoft.com/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window) that describes how to connect to all M365 PowerShell environments in a single Window.

**Comment by wcarson** [comment]
Thanks @chrisda. I reported the bug as described in the KB article. I'll also try the preview/newest version of the module in the same scenario to see if there's any difference in behavior.

**Comment by yogkumgit** [comment]
@wcarson If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
