### ISSUE TITLE
Connect-MicrosoftTeams -AccountID is not working with account with MFA enabled

### ISSUE THREAD

**Issue by Onenote4Exchange** [MicrosoftDocs/office-docs-powershell#8307]
Hi, 
Can you please help regarding this issue?
I am trying to connect to Microsoft Teams powershell module using Connect-MicrosoftTeams -AccountID <UPN>.
I have a strange behavior, This CMDLet will work on personal device but not on my work device.
I am trying to user this CMDLet because I am creating a powershell application, so I cannot use Connect-MicrosoftTeams because I will not be able to manage the prompt for MFA.

Can you please let me know if Connect-MicrosoftTeams -AccountID <UPN> is not using the same authentication method as Connect-MicrosoftTeams?

The error message is: Connect-microsoftTeams : Broker response returned error: WAM Error Wam plugin Microsoft.Identity.Client.Platforms.Features.WamBroker.AadPlugin Error code: 3399614476 Error Message: SubError: basic_action
V2Error: invalid_grant AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access
'00000003-0000-0000-c000-000000000000'.
Thank you
John

**Comment by DEberhardt** [comment]
Hello,
you can help yourself by removing the AccountId-Parameter and running the CmdLet without any parameters 
```powershell
Connect-MicrosoftTeams
```
This will trigger an MSAL authentication where you can select the Account which works with MFA (MFA challenge is done right after authentication with Username and Password, like logging into [admin.teams.microsoft.com](https;//admin.teams.microsoft.com)).

Hope that helps,
David

**Comment by get-itips** [comment]
Hello @Onenote4Exchange how are you?
Currently, the method to connect to Teams PowerShell with an account enabled for MFA is the one described[ here](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps#example-1--connect-to-microsoftteams)

> If multi-factor authentication is enabled for your credentials, you must log in using the interactive option.

**Comment by DEberhardt** [comment]
Apologies, I did assume that you wanted to sign in interactively... 
`-AccountId` while being somewhat fashionably broken can only be used to provide the Username... - I wish it could be used to re-use a previously established session to other services (like AzureAd) - this is how I would want to use it, without having to have a second MSAL window pop up.
As there is no `-Password` Parameter (and Basic-Auth is gone), I have assumption you wanted to log in interactively.

If you need to sign in through a script (through a Scheduled task) that connects you to MicrosoftTeams, you cannot require MFA for this account. Here, too, I would use the `-Credential` Parameter rather than `-AccountId`. Better yet, would be to use an AccessToken (but I think this, too, is also broken currently...)

**Comment by Onenote4Exchange** [comment]
Dear @DEberhardt,
it s very strange Azure AD Module is working fine with  -accountID even if we have MFA enforced. I was hoping Teams module can have the same feature. I will checked with Microsoft Support premier if we can find a solution.

**Comment by get-itips** [comment]
Hello @Onenote4Exchange 
How are you? Hope you are doing good.
As said, the current method that supports MFA is to login interactively as I described in https://github.com/MicrosoftDocs/office-docs-powershell/issues/8307#issuecomment-919412273 
If upcoming versions of the module start supporting other methods we will update the documentation.
Thank you

@yogkumgit please close
