### ISSUE TITLE
ReturnConnection example

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#832]
It would be helpful is there was an example showing how the ReturnConnection optional parameter can be used

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f910a5c-5883-6394-19a3-4cf1670c431f
* Version Independent ID: 4451fe4c-df86-34a8-0db0-46a47e70b5a5
* Content: [Connect-PnPOnline (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by nsshommo** [comment]
@DeanGross Thanks for your suggestion. We are working on this.

**Comment by DeanGross** [comment]
I'm still waiting, any idea when the example will be added?

**Comment by Techwriter40** [comment]
@VesaJuvonen for your review and add example.

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

We want to make sure your PnP issue is handled appropriately.

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
