### ISSUE TITLE
Contradiction in parameters

### ISSUE THREAD

**Issue by fjuhasz** [MicrosoftDocs/office-docs-powershell#8734]
Hi,

If you compare the -CustomAlertText parameter that states the following: ".....This parameter is only meaningful when the Action parameter value is ReplaceWithCustomAlert." with the content at the -Action parameter you will see that the ReplaceWithCustomAlert is not existing.

It would be important for me to see how to configure the system to use the custom alert text. 
Currently the EXO is not using it and I cannot make it to use.

This is not just a documentation issue (like a typo) but also a product issue in my view.

BR,
Ferenc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d342c899-b103-7cfa-2ddd-4f6855552cb5
* Version Independent ID: 8194874e-f75a-4e3c-7924-b5024936cdc5
* Content: [New-MalwareFilterPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-malwarefilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MalwareFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@fjuhasz, fundamentally the problem was a typo (correction in bold):

> This parameter is only meaningful when the Action parameter value is **DeleteAttachmentAndUseCustomAlert**.

Malware policies and default/custom notifications are all described [here](https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-anti-malware-policies#use-the-microsoft-365-defender-portal-to-create-anti-malware-policies).

But, I also know that these legacy "notification" options are in the process of being retired and replaced by [quarantine notifications in quarantine policies](https://docs.microsoft.com/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages).

**Comment by yogkumgit** [comment]
@fjuhasz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
d
