### ISSUE TITLE
-PhoneNumberType how to retrieve value

### ISSUE THREAD

**Issue by CharLind87** [MicrosoftDocs/office-docs-powershell#8901]
The Set-CsPhoneNumberAssignment requires the parameter -PhoneNumberType. What cmdlet or process can one use to retrieve this information?
We have an environment with a mix of calling plans and direct routing.

Been trying different cmdlets to see if anything includes phonenumbertype but haven't found one so far.

Any help would be much appreciated!

**Comment by JensTrier** [comment]
@CharLind87 Thanks for the feedback! 

To a certain extent it is assumed that the administrator knows which type of phone number that will be assigned, because based on type of phone number different configuration needs to be done, i.e. for Direct Routing you need to set certain policies and you also need to ensure the SBC is configured etc.

For Calling Plan and Operator Connect numbers you should be able to see them in the Teams admin center under Voice -> Phone numbers and the number provider name tells you what is which. Microsoft as provider name is Calling Plan and others will in most if not all cases be Operator Connect.

For Direct Routing you can't really see the phone numbers anywhere using our tools before they have been assigned to a user or a resource account.

Get-CsOnlineTelephoneNumber will show you different phone numbers based on NumberType. Cloud will be Calling Plan or Operator Connect numbers and Hybrid will show you numbers from Direct Routing and other types.

The assignment cmdlet needs to know the number type and that's why we are asking for it. Unfortunately it can't fully determine the type for you.

So my recommendation is to talk to the person that gave you the number and see if the type can be determined.

I'll see if I can make the documentation clearer on the point you have raised.

**Comment by DEberhardt** [comment]
I have written a CmdLet that tries to bridge that gap and determine the number type for you: [`Get-TeamsPhoneNumber`](https://github.com/DEberhardt/TeamsFunctions/blob/main/docs/Get-TeamsPhoneNumber.md) - hope you like it.
