### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by stromnessian** [MicrosoftDocs/office-docs-powershell#8922]
When following the instructions (using Global Admin account)...

_WARNING: Please note that you can only use above 9 new EXO cmdlets (the one with *-EXO* naming pattern).You can't use
other cmdlets as we couldn't establish a Remote PowerShell session as basic auth is disabled in your client machine. To
 enable Basic Auth, please check instruction here
https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#prerequisites-for-t
he-exo-v2-module
New-ExoPSSession : Create Powershell Session is failed using OAuth
At C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\netFramework\ExchangeOnlineManagement.psm1:475 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Security & Compliance Center PowerShell using the EXO V2 module](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-scc-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@stromnessian, the error says it all:

> You can't use other cmdlets as we couldn't establish a Remote PowerShell session as basic auth is disabled in your client machine.

You have two options:

- Enable Basic auth in WinRM on your PC as described [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#prerequisites-for-the-exo-v2-module). As explained, you aren't using Basic auth to authenticate. WinRM needs Basic auth enabled in WinRM to send the session's OAuth token, since the client-side WinRM implementation has no support for OAuth.

- Try using the v2.0.6 Preview version of the module (Preview4 is the latest, I believe). Upgrade instructions are [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#update-the-exo-v2-module). As explained [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#updates-for-version-206), there are ~250 cmdlets that are now backed by REST, so no Basic auth in WinRM required. This will work if the cmdlets that you're trying to use are included in the ~250.

**Comment by stromnessian** [comment]
Thanks @chrisda - my bad - I didn't read the part about needing basic auth enabled for the OAuth flow to succeed.  Will check out the preview version.

**Comment by chrisda** [comment]
No problem.

Thanks for the feedback.

Closing
