### ISSUE TITLE
set-csipphonepolicy

### ISSUE THREAD

**Issue by jdubyaeber** [MicrosoftDocs/office-docs-powershell#9]
the old version was complete with descriptions and values.  the new version is blank?

https://docs.microsoft.com/en-us/powershell/module/skype/Set-CsIPPhonePolicy?view=skype-ps

-John

**Comment by kenwith** [comment]
Working on getting this fixed. Thanks for reporting issue John!

**Comment by kenwith** [comment]
This issue is resolved. I was able to get the content from the old version into this 'evergreen' version. The reason the content was missing is that the content that shows with Get-Help has to be checked into code and then pushed out with each version or update. The 'evergreen' content pulled from the product itself (whatever customer can see shows up in cmdlet reference, even if it is an internal only parameter or cmdlet). So there was a gap between when the 'evergreen' content was generated and the last help check in to code that went out with the product. If you find more of these let me know and I will track down the old content and get it updated. Thank you for reporting!
