### ISSUE TITLE
Why is the M$$ Docs since some years always incomplete??

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/office-docs-powershell#908]
Good evening
It's really annoying that the expensive M$$ Product Documentation is much worse than Open Source Products.
Is this the reason why M$$ itself is moving to Linux for IoT? That's great!, we're replacing M$ products, too.

Until then, we pay for Software and expect complete Docs as you had 10 years ago.
And no, we are not interested to write your Docs ourself.

Here, of course, the counterpart of Enable-ExchangeCertificate is missing. How do we check which certificate is used for which Service?

It's great to have Google to answer M$$ questions.
But it's annoying.

Kind regards,
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1da49c-c865-3ec1-b559-8c0be45b38b0
* Version Independent ID: 9555b2ed-e96b-6ac1-9e57-ec9cfd026a04
* Content: [Enable-ExchangeCertificate (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/enable-exchangecertificate?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/encryption-and-certificates/Enable-ExchangeCertificate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/encryption-and-certificates/Enable-ExchangeCertificate.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nsshommo** [comment]
@schittli Thanks for your query. We will get back to you soon.

@chrisda Can you help or point me to someone who can help on this one?

**Comment by schittli** [comment]
@nsshommo Thank you for your answer. 

In Enable-ExchangeCertificate there is just a missing link to Get-ExchangeCertificate, which will answer the question about assigned Services.

I still hope that Microsoft itself will start fixing their issues, it seems that there are volunteers working on products that Microsoft sells for a lot of money. Yes: PowerShell is one of them. Without PowerShell, Microsoft cannot sell Windows Servers or Azure. That's why PowerShell is primarily a commercial product.

Kind Regards, Thomas

**Comment by kenwith** [comment]
@schittli thank you for your critical feedback. My intention with open sourcing the PowerShell references wasn't to have others write the content but to become more open and transparent. This is a perfect case in that you were able to raise the issue with us and we can find a subject matter expert to get this fixed. I still shudder to think of how the processed flowed with issues like the one you found before this new open way. It was all in a proprietary system with various cruft built up over the years. Now it is all open and transparent and my goal is to get the docs better and better.

There was some discussion when we originally migrated from TechNet to keep the GitHub repo private but Microsoft is opening up in general and pushing for a public repo won out. The idea behind this is not to shift the work to the community but just to give the opportunity to the community if they want to fix something or add some value.

I recently just wired up the Product Feedback and Article Feedback from the docs.microsoft.com articles for PowerShell to go into this public repo so that everyone can see issues and Microsoft can be accountable for getting them fixed.

I am not any type of manager and focus on development but just wanted to share this info. I am a huge open source fan too and use Linux at home daily. :)

@chrisda  and I are peers and he is a SME on Exchange so we will work together to get this fixed and updated.

Thanks for taking the time to provide the feedback. My opinion is that for every one person, like you, who takes the time to provide feedback there are hundreds of others who experience the same issue.

PS - I completely agree with you about the importance of PowerShell and never miss an opportunity internally to bring up this point. :)

**Comment by chrisda** [comment]
@schittli, I added a sentence and link in the Synopsis for Get-ExchangeCertificate. Thanks for the feedback.
