### ISSUE TITLE
Set-MailboxPlan parameter description is confusing

### ISSUE THREAD

**Issue by jianhsieh** [MicrosoftDocs/office-docs-powershell#9081]
Hi Team,

I've just came across this PowerShell command, and the parameter "-RetentionPolicy" seems a bit misleading. I've tested in lab:
- Neither Set-MailboxPlan nor Set-RetentionPolicy updates existing mailboxes’ retention policy
- MailboxPlan’s default retention policy has a higher priority than setting policy to default via Set-RetentionPolicy
- By default, MailboxPlan’s default should be Default MRM Policy
- If MailboxPlan’s retention policy is set to “$null”, then it will honor the default policy set via Set-RetentionPolicy, else new mailboxes honors MailboxPlan’s retention policy on creation

This description is confusing, maybe need clarification: 
"Note: Only existing mailboxes respect a custom retention policy that's set by this parameter. New mailboxes are always created using the default policy."

Regards,
Andy (jianhsieh@microsoft.com)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 895e6cb2-f60c-66d1-204b-8693647aff7a
* Version Independent ID: 27304071-8cf8-7776-1c18-1185388317a5
* Content: [Set-MailboxPlan (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxplan?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailboxPlan.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
Hi @jianhsieh, thank you for your feedback.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=jianhsieh

**Comment by dariomws** [comment]
@jianhsieh, what specific update are you suggesting to the description of this parameter?

Thanks.

**Comment by yogkumgit** [comment]
@dariomws

**Comment by yogkumgit** [comment]
@dariomws Gentle reminder

**Comment by dariomws** [comment]
Sorry to bother you @chrisda, but I'm a bit lost here. Do you think you can help?

**Comment by chrisda** [comment]
@jianhsieh, I did some testing of my own:

- IsDefault does, in fact, work in New/Set-RetentionPolicy as you described.
- Without touching the retention policy that's specified in the mailbox plans ("Default MRM Policy" for me), using IsDefault in Set-RetentionPolicy on a new policy that I created  changed had the following immediate effects:
  - Changed the retention policy of 65/75 of user mailboxes. I can find no immediate correlation for the 10 user mailboxes that weren't updated. All appeared to be licensed; some were admins, some were not.
  - Changed the retention policy of 0/7 of room, equipment, and shared mailboxes.
  - Changed the retention policy of 1/1 of arbitration mailboxes.
- In a fresh demo tenant where the retention policy in the mailbox plan was blank, I also created a new retention policy and then made it the default. That action changed **all** of the existing user, room, and arbitration mailboxes to use the new default retention policy (which basically confirms what you said).
- I set the retention policy in the mailbox plan to "Default MRM Policy" and created a new mailbox. The new mailbox got "Default MRM Policy" as its retention policy and did not change any of the existing mailboxes (this confirms what you said).
- I created a new retention policy and made it the default in one step. Doing so changed the retention policy on every mailbox **except** the mailbox I created in the previous step; its policy stayed at "Default MRM Policy".

Here's what I think all of this means: you really should NOT set a retention policy in the mailbox plan, because changes you make to which retention policy is the default will not be reflected for any mailboxes created during the period when you specified the retention policy in the mailbox plan.

I think that's what's going on in that original tenant where I was testing; it's very old, and it had a retention policy set in the mailbox plan, whereas the fresh new tenant I continued on did not.

Here are my proposed changes to the RetentionPolicy parameter:

> By default, the value of this parameter is blank ($null) in new organizations, which means the default retention policy is used (the retention policy where the IsDefault property value is True). By default, the default retention policy is named Default MRM Policy.
>
> If you don't set a value for this parameter, new mailboxes are assigned the default retention policy, and existing mailboxes are updated if you change which retention policy is the default (using the IsDefault switch on the New-RetentionPolicy and Set-RetentionPolicy cmdlets). Setting a value for this parameter has the following potentially negative effects:
>
> - Only new mailboxes you create after you specify the retention policy are assigned that policy. Existing mailboxes are not updated when you set or update retention policy value for this parameter
> - Changes to which retention policy is the default are ignored on new and existing mailboxes.
> - If you change the value of this parameter from a specific retention policy back to $null (blank), changes to which retention policy is the default affect only mailboxes that were created when this parameter value was last blank, and any new mailboxes you create going forward. Existing mailboxes you created when this parameter identified a specific retention policy are not affected by changes to which retention policy is the default, and are basically stuck using the specific retention policy from that time.

Comments?

**Comment by jianhsieh** [comment]
Thank you, Chris,

Extremely detailed explanation! I have no further comments to add.

Regards,
Andy

**Comment by dariomws** [comment]
@chrisda thank you!

**Comment by jianhsieh** [comment]
There is one thing not directly related but may need considerations.

*IF* customer's mailboxes are all created with -IsDefault, we may need to prevent setting another new policy as the new default. If the policy updates to whole bunch of mailboxes and the users are all within corporate network, Outlook will be downloading massive changes as MAPI properties needs to be synced.

This will saturate network which we've encountered quite a few cases in the past when retention policy are pushed to thousands of users.

From: Andy Hsieh
Sent: Thursday, April 28, 2022 9:04 AM
To: MicrosoftDocs/office-docs-powershell ***@***.***>; MicrosoftDocs/office-docs-powershell ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/office-docs-powershell] Set-MailboxPlan parameter description is confusing (Issue #9081)

Thank you, Chris,

Extremely detailed explanation! I have no further comments to add.

Regards,
Andy
