### ISSUE TITLE
Information about "configuration pending"

### ISSUE THREAD

**Issue by thomyg** [MicrosoftDocs/office-docs-powershell#911]
Would be good to add an information about the async behaviour of the Cmdlet and what to expect in terms of duration. Get-PnPTenantOrigin lists the newly added as "configuration pending" but would be nice to get a heads-up in this here in the documentation upfront. Something like "Once you've run the command, the system synchronizes the configuration across the datacenter. This takes 15 minutes." like here: https://support.office.com/en-us/article/use-the-office-365-content-delivery-network-with-sharepoint-online-bebb285f-1d54-4f79-90a5-94985afc6af8 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3b6781-410b-bdc8-0e8e-fa67a0569cf2
* Version Independent ID: d1abc1ba-6432-79d7-8365-855ad11ea1a7
* Content: [Add-PnPTenantCdnOrigin (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnptenantcdnorigin?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTenantCdnOrigin.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTenantCdnOrigin.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by nsshommo** [comment]
@thomyg Thanks for your valuable comment. We will try to update as necessary.

**Comment by AndreaBarr** [comment]
@thomyg Thank you for this feedback

We want to make sure your PnP issue is handled appropriately.

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
