### ISSUE TITLE
Description missing for parameter RejectIfRecipientHasNoRights 

### ISSUE THREAD

**Issue by deividfoggi** [MicrosoftDocs/office-docs-powershell#9130]
The parameter RejectIfRecipientHasNoRights has no description making difficult to understand the implications of changing it.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebaffb3-b4a1-9ba1-d6cb-cea3befecc89
* Version Independent ID: 8b7b857e-4090-d865-79dc-5e14f6fa7748
* Content: [Set-IRMConfiguration (ExchangePowerShell)](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-irmconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-IRMConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-IRMConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@deividfoggi, empty parameter descriptions are a known issue. See [this issue and my response](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for more background.

If you know that this parameter is supposed to be available and how it works, I encourage you to add a description for it directly. Painfully easy instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

**Comment by deividfoggi** [comment]
Hi Chris, unfortunetly I know nothing about this one so this is why I opened this issue instead of creating a PR. Hope you can ask PG about the description.

Thanks.

**Comment by chrisda** [comment]
As described in that link I provided, it's an availability vs. functionality issue. I know 100% that the parameter is available. Whether or not it's supposed to be is another story (accidental release, Private Preview, too early release, etc.).

If the issue is simply that the description is empty, my response is, "thanks, known issue". If they are actually trying to use the thing, perhaps because the parameter was mentioned in other content or a blog post OR they're trying to use it for a specific task and it isn't working, then we can proceed.
