### ISSUE TITLE
Get-CsOnlineUser and -filter

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#9138]
Hi,
I was reading your documentation [MS Docs: Get-CsOnlineUser](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps) and especially the "-filter" section.

Text says, that "-NOT" and "-LIKE" are not anymore available and yes, that is true "The method or operation is not implemented" :D But just before that the document is saying e.g.:
_All users with an AssignedPlan that starts with MCO: -Filter "AssignedPlan **-eq** 'MCO*'"_

Is this something like a "new normal", that "-EQ" in PowerShell should covers also what "-LIKE" was offered? If this is like that, once more I do not understand the logic. EQ in Teams' PS means **equal** and **like**, but elsewhere those are different? Or is there some wider change ongoing on PS which I have not noticed?

**Comment by Petri-X** [comment]
Hi @isrumnon 
The reason to asking this, was just to get understood of the background of this. I'm not sure, but in my mind I have not seen any communication of fundamental changes (in my mind) like this.

When you read these:
```
All users with an AssignedPlan that ends with "MCO": -Filter "AssignedPlan -eq '*MCO'"
All users with an AssignedPlan that starts with MCO: -Filter "AssignedPlan -eq 'MCO*'"
All users with an AssignedPlan that contains MCO: -Filter "AssignedPlan -eq '*MCO*'"
```
In my mind those wildcard versions has been the same what **-like** has done earlier?

And yes, I was incorrect with "**-like**" that seems to be still available. But I faced to this error "_The method or operation is not implemented_" when I tried to use "**-notlike**". At least for me it has been super useful to use **-not** on the queries. Now this basically means, I need to download the whole results, and do the exclude statements on my site. Which in my mind is a bit shame. At the same time I have asked if they could implementing similar parameter to this get command than what e.g. [get-aduser -parameters](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2022-ps) do have. So far this has not become reality.

So is this TPM's new own path that standard comparison operators will be removed, while rest of the PS world still supporting those. Which might not be so good idea. Or is this some kind wider change for the PowerShell comparison operators?

**Comment by ExSkip** [comment]
Hi Guys,

Let me also problems we've faced in our hybrid environments related to -filter in new Teams powershell module.

1. According to the doc it's no longer possible to filter by OnPremLineURI attribute. And it makes some problems for admin. Why is it important? Well, in hybrid env you sync LineURI from AD <> AAD <> Teams. And there is always a chance that the same number is specified for multiple users. Normally number syncs from OnPremLineURI to LineURI if there is no number conflict (owned by other user or voice app) and licensing plan is correct. If the number is assigned to multiple users one of them will properly sync it to LineURI but the second one not leaving the number on OnPremLineURI attribute. Another example could be non-did number provisioning for a group of users and number is occupied by i.e. voice app (attendant or a call queue). In this case numbers will be specified for users in the OnPremLineURI only without sync to LineURI.
So usually when we troubleshoot some number assignment issues we're filtering both LineURI and OnPremLineURI to see if the number for some reasons got assigned for multiple users or it's assigned to user without proper licensing plan or disabled enterprise voice.
i.e. Get-CsOnlineUser -filter "LineURI -like '*<number>*'-or OnPremLineURI -like '*<number>*'"
Is it possible to return filtering for the OnPremLineURI  ?

2. VoicePolicy was removed completely and replaced by FeatureTypes.
That make things quite complicated when you need filter Calling Plan users from Direct Routing. 
i.e. Get-CsOnlineUser -filter "VoicePolicy -eq 'BusinessVoice'"
Now you cannot properly filter it which makes reporting inconvenient.
Or maybe there is any kind of alternative because FeatureTypes is not filtered attribute?

3. Not really clear why phone attribute was removed. It's maybe not really important but in some cases allowed to quickly check what number is presented in the Teams tenant (synced from GAL). It's not  critical but was nice to have.

Thank you

**Comment by isrumnon** [comment]
Hi @ExSkip, for:
1.1 We're looking into support for filtering based on OnPremLineURI in the modernized TPM. We'll update you soon on when we can reintroduce this in the short term (2-3 months) 
1.1 We've created a bug and are looking into this
2. This is a bug on our end and will introduce this Filtering capability in FeatureTypes in the long term (4-5 months from now)
3. This was a design choice from our team and will not be supporting this anytime soon
4. MCOValidationError is now renamed to UserValidationError

**Comment by yogkumgit** [comment]
@Petri-X Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Petri-X** [comment]
Actually not so much.. for example. is it so that "-EQ" start taking role from "-LIKE" and is this change for Teams PS module only, or is this wider change in PS world? Also would like to understand the reason why -NOT has been removed.

**Comment by isrumnon** [comment]
@Petri-X "-EQ" will not take over the "-LIKE" role. It will continue to function as is. The "-LIKE" operator is not available right now and we are looking into how to re-introduce it, it is the same case for the "-NOT" operator.

**Comment by isrumnon** [comment]
Hi @Petri-X @ExSkip we've changed the format for filtering based on assigned plans to accommodate older formats (using -like operator)
e.g., AssignedPlan that starts with MCO: -Filter "AssignedPlan -like 'MCO*'"

Also, Filtering on lineuri with ext based numbers is now supported
