### ISSUE TITLE
Difference between this an Get-PnPContext

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#914]
What is the difference between Get-PnPConnection and Get-PnPContext. The instructions above are not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726aca9d-6df0-6691-bc00-f913ebee663f
* Version Independent ID: 34f7d6c0-930b-c46a-f1e1-1b8719a38991
* Content: [Get-PnPConnection (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpconnection?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPConnection.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPConnection.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by DeanGross** [comment]
Following up, can someone please respond?

**Comment by kenwith** [comment]
@DeanGross you might also try github.com/sharepoint  .. I know @VesaJuvonen has a large PnP community there.

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

We want to make sure your PnP issue is handled appropriately.

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
