### ISSUE TITLE
SharePoint Online Powershell - Root element missing error when run Connect-SPOService command

### ISSUE THREAD

**Issue by muges01** [MicrosoftDocs/office-docs-powershell#919]
Hi Everyone,

I have newly installed SharePoint Online Management Shell (SharePointOnlineManagementShell_7521-1200_x64_en-us) on a windows 10 machine.

When i tried to run the 'Connect-SPOService -Url $adminUrl -Credential $credentials' I'm getting 'Root element is missing' error.

![image](https://user-images.githubusercontent.com/22563887/39243956-a887d286-48c1-11e8-80eb-cce6a0eab3d5.png)

## Expected or Desired Behavior
When I ran the following command, I expect to connect to my SharePoint online tenant.

##Steps to Reproduce
Install the SharePointOnlineManagementShell_7521-1200_x64_en-us
Open the SharePoint Online Managemnet Shell as administrator
Run the following commands
$adminUrl = "https://{domain}-admin.sharepoint.com" $userName = "admin@{domain}.onmicrosoft.com" $password = Read-Host "Please enter the password for $($userName)" –AsSecureString $credentials = New-Object -TypeName System.Management.Automation.PSCredential -argumentlist $userName, $password Connect-SPOService -Url $adminUrl -Credential $credentials
What am I missing? Any guidance to resolve this issue is appreciated.

Thank you In advance

**Comment by nsshommo** [comment]
@muges01 Thanks for letting us know your query. We are looking into this matter and will get back to you very soon.

**Comment by muges01** [comment]
Thank you @nsshommo. I'm looking forward to hear from you soon.

**Comment by kenwith** [comment]
@muges01 - thanks for this issue. It could very well be something that is not expected behavior and we really appreciate you taking the time to report so we can put any information back into the docs.

@nsshommo is going to try on a test tenant and see as well. Here is the documentation to follow on how to [Connect to SharePoint Online with PowerShell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps). 

While we are investigating on the docs side it would also be worth opening a support ticket on your tenant. You can login to the Admin on your tenant and open a service request. Here is an article that is a little bit out of date but shows the general process: https://blogs.technet.microsoft.com/praveenkumar/2013/07/17/how-to-create-service-requests-to-contact-office-365-support/

We will keep this issue open and report back as well. If you get information in the meantime please update this Issue so we can incorporate. Thanks again for taking the time on this!

**Comment by muges01** [comment]
I manage to resolve this issue by adding Google's DNS server as my DNS instead of using your ISPs by entering 8.8.8.8 and 8.8.4.4 as your primary and secondary DNS.

Please refer to the following article
https://www.koskila.net/2017/07/14/fixing-security-reasons-dtd-prohibited-xml-document-issue/ 
https://sharepoint.stackexchange.com/questions/94741/dtd-error-with-connect-sposervice

**Comment by purna429** [comment]
Is there any verified resolution for this issue... I am getting the same when running the csom code to connect a sharepoint online site.

Error is at on ctx.ExecuteQuery() after creating the connection.

Error :Root element is missing.
![RootElementError](https://user-images.githubusercontent.com/20446017/57822637-636b7d80-7762-11e9-97d6-5657258e080f.png)

Note :
1> The same code is working to connect the same online site from other machine.
2> The same code is working for other sharepoint online sites from the same machine.


Any help appreciated..

TIV,
PCM

**Comment by purna429** [comment]
This issue is resolved after changing the DNS address.  Refer this link for more details.
http://moresharepoints.blogspot.com/2019/05/root-element-missing-when-connecting-to.html

Thanks
Purna

**Comment by stevearivera** [comment]
This is not resolved this is going around.

**Comment by katjones23** [comment]
I receive this error when using 'Connect-SPOService', and I tried the DNS work around, but it didn't work for me.
