### ISSUE TITLE
Your product feedback button links back to the documentation feedback GitHub repo.

### ISSUE THREAD

**Issue by jeremytbrun** [MicrosoftDocs/office-docs-powershell#929]
It seems like your product feedback button should link to a feedback portal for the Exchange PowerShell modules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d47105-b32e-f0f8-3e71-db411c6abe7c
* Version Independent ID: 338beb1b-1f13-0a77-9ac3-1c4fe542b612
* Content: [Search-UnifiedAuditLog (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/search-unifiedauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by kenwith** [comment]
@jeremytbrun - thanks for taking the time to provide feedback. This is by design as the product teams are opening up as well and taking feedback directly on this GitHub repo. A lot of times the lines are blurred about what is 'product feedback' and what is 'article feedback'. A lot, maybe most, of the time a product feedback is really about how an example is phrased or put together in an article and an article feedback is really about something specifically within the product. Unfortunately I couldn't just have a single button due to how docs.microsoft.com is setup so I have both going to this Issues repo and we all keep a close eye on it. This way we can address all issues directly and openly. Product teams are getting directly involved here too so they can also use the tighter loop to improve the products more quickly. Let me know if you have other questions and I can do my best to answer.

**Comment by jeremytbrun** [comment]
I appreciate the clarification. It makes sense the way you describe it. It just initially seemed inconsistent with the wording I had seen elsewhere around the new documentation experience. I've sent my question via a service request through our support contract. Thanks!

**Comment by kenwith** [comment]
@jeremytbrun - that is great to also send through service request too. Also, the reference docs here are now open source so if you are interested to make any contributions or edits just let me know and I can provide guidance. I created a README on the main repo page and am always open to help however I can too. My goal is to open things up so the rest of the community can capture and benefit from the knowledge that experts like you have and decide to share openly. It is just an option now. Thanks again for taking the time to engage on the docs!
