### ISSUE TITLE
Script tag isn't needed

### ISSUE THREAD

**Issue by bmarcos81** [MicrosoftDocs/office-docs-powershell#940]
Script tag isn't needed and breaks the page rendering.
I tested it in SPO with a modern team site with NoScript disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22b9cc6f-64ae-6848-7249-222a5ece3997
* Version Independent ID: cee9a1dc-e067-b90b-675c-6a7d56865068
* Content: [Add-PnPJavaScriptBlock (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpjavascriptblock?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPJavaScriptBlock.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPJavaScriptBlock.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by nsshommo** [comment]
@bmarcos81 Thanks for letting us know. We are working on this.

**Comment by AndreaBarr** [comment]
@bmarcos81 Thank you for your feedback

We want to make sure your PnP issue is handled appropriately.

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
