### ISSUE TITLE
IsDirSynced missing

### ISSUE THREAD

**Issue by ivanfioravanti** [MicrosoftDocs/office-docs-powershell#9404]
IsDirSynced is missing from Get-EXORecipient, it was present in old Get-Recipient. Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9145396-cc72-6e54-4204-6867397e67ea
* Version Independent ID: ca86d515-e4d3-ce0f-11e3-87ddfda38b75
* Content: [Property sets in Exchange Online PowerShell V2 cmdlets](https://docs.microsoft.com/en-us/powershell/exchange/cmdlet-property-sets?view=exchange-ps#get-exorecipient-property-sets)
* Content Source: [exchange/docs-conceptual/cmdlet-property-sets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/cmdlet-property-sets.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ivanfioravanti, there is no IsDirSynced (or similar) parameter on Get-Recipient, so you must be talking about a property that's displayed in the output of Get-Recipient.

If you're using v2.0.5 of the EXO V2 module, you should open a support ticket and tell them that IsDirSynced is missing from the Get-ExORecipient output.

If you're using v2.0.6-PreviewX, regular support can't help you because that version is still in Preview, so use the following support alias.

## Report bugs and issues for the EXO V2 module

When you report an issue at `exocmdletpreview[at]service[dot]microsoft[dot]com`, be sure to include the log files in your email message. To generate the log files, replace \<Path to store log file\> with the output folder you want, and run the following command:

```powershell
Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All
```

**Comment by yogkumgit** [comment]
@ivanfioravanti Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
