### ISSUE TITLE
Error while creating a new compliance case using Security & Compliance Center PowerShell (Connect-IPPSSession)

### ISSUE THREAD

**Issue by jaganpt** [MicrosoftDocs/office-docs-powershell#9458]
Hi Team,

Unable to create a new compliance case using Security & Compliance Center PowerShell (Connect-IPPSSession).
Please find the error details below.

**Error details:**
WARNING: An unexpected error has occurred and a Watson dump is being generated: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
+ CategoryInfo : NotSpecified: (:) [New-ComplianceCase], NullReferenceException
+ FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Office.ComplianceCase.Tasks.NewComplianceCase
+ PSComputerName : 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Version of the ExO module that you're using? Command with PII removed?

**Comment by jaganpt** [comment]
2.0.6 preview5
Yes.

**Comment by chrisda** [comment]
Sorry, for the second thing, I meant "provide an example command with PII removed".

Because v2.0.6-Preivew5 is still in Preview, you won't be successful opening a support ticket (they will defer, saying they don't support Preview features). You'll need to use the module alias exocmdletpreview[at]service[dot]microsoft[dot]com.

Report back here if we need to update the documentation for anything:

**Comment by yogkumgit** [comment]
@jaganpt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by bluestarcs** [comment]
Hi, 
I have this same issue, am able to connect and use S&C powershell cmdlets with app authentication (like get-ComplianceSearch) but cannot run eDiscovery cmdlets like New-ComplianceCase successfully. I get the same error as noted above; Object reference not set to an instance of an object. Any guidance would be much appreciated!
TIA,
Sarah

**Comment by fpsacha** [comment]
@bluestarcs Same here.
`failed with exception: Object reference not set to an instance of an object..`

**Comment by chrisda** [comment]
@fpsacha, @bluestarcs, make sure you're using the latest version of the module (current v2.0.6 version is Preview7). Update instructions are [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#update-the-exo-v2-module). If that doesn't work, send a message to exocmdletpreview[at]service[dot]microsoft[dot]com and tell them what's going on.

**Comment by rudesome** [comment]
Same issue here, i can create a compliance search but when i try to start the search i get the error:

```pwsh
Get-ComplianceSearch -Identity testing | Start-ComplianceSearch
WriteError: Unable to execute the task. Reason: Compliance search initialization for "testing" failed with exception: Object reference not set to an instance of an object..
```

am on Preview8 
```pwsh
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.0.6      Preview8   ExchangeOnlineManagement            {Get-ConnectionInformation, Get-EXOCasMailbox, Get-EXOMailbox, Get-EXOMailboxFolderPermission…
```

when i start the same compliance search from within the portal it works as expected

**Comment by fpsacha** [comment]
> 

Same with V8 for me.

**Comment by bluestarcs** [comment]
> 

Thanks @chrisda 

I checked and I am on v3 and still not working. See below. I will submit to the email you provided and update this thread if we get anywhere. 

![image](https://user-images.githubusercontent.com/66495240/191372496-def6895e-91b0-4a54-9257-fb58b4eece5a.png)

**Comment by chrisda** [comment]
Any/all: v3.0.0 was officially released today, so I would highly encourage you to upgrade from the v2.0.6-PreviewX versions you might have been using and try again in v3.0.0. Because v3.0.0 is an official release, you can get help by opening a support ticket, which gets your issue in front of the team that's responsible for fixing it. Only use the email alias for Preview versions of the module.

**Comment by rudesome** [comment]
@chrisda as mentioned by @fpsacha , V3 still has the same issue, i have mailed this issue when it was still in preview, they just ignored our messages and shipped an official release with known bugs.

**Comment by bluestarcs** [comment]
@chrisda @fpsacha 
@rudesome  I opened a case with Microsoft and at first the engineers thought this was a bug but then escalated the issue and said that this was actually functionality as designed. So, no fix is coming. Super bummer. I am sure Microsoft thinks this will motivate companies to upgrade to E5 to get this functionality via Graph however, having worked in legal technology for over a decade, that assumption, due to the licensing schema as it is today, is false in most cases. This just means that corporations get less value and more frustration. I have asked Microsoft to please update their documentation. @chrisda if you could help with that, at least other people won't wasted hours/days trying to implement app authentication with eDiscovery Powershell calls.

**Comment by chrisda** [comment]
@bluestarcs, so what exactly is the content fix? Is it just "New-ComplianceCase doesn't work in S&C PowerShell when using CBA/app-only auth"? Anything else?

**Comment by bluestarcs** [comment]
@chrisda I am able to connect to IPPSSession using app authentication but only the commands that lay outside of the eDiscovery center work. I.e. Get-ComplianceSearch. None of the commands to access or modify the eDiscovery center work with app authentication. I.e. New-ComplianCase, get-ComplianceCase etc....Those commands require delegated permissions.

**Comment by fpsacha** [comment]
Since it is not possible to do a new-compliancesearch and action with Exchange, is it possible to do it with MsGraph ?

**Comment by jbb4play** [comment]
> Since it is not possible to do a new-compliancesearch and action with Exchange, is it possible to do it with MsGraph ?

I have been able to do a compliance search
```
Connect-IPPSSession -ConnectionUri $ConnUri -CertificateFilePath $CertPath -CertificatePassword $pass -AppID $AppId -Organization $TenantId
```
I am just not able to start it

```
Start-ComplianceSearch gives me a object null reference error
```

**Comment by bluestarcs** [comment]
> > Since it is not possible to do a new-compliancesearch and action with Exchange, is it possible to do it with MsGraph ?
> 
> I have been able to do a compliance search
> 
> ```
> Connect-IPPSSession -ConnectionUri $ConnUri -CertificateFilePath $CertPath -CertificatePassword $pass -AppID $AppId -Organization $TenantId
> ```
> 
> I am just not able to start it
> 
> ```
> Start-ComplianceSearch gives me a object null reference error
> ```

@jbb4play Just make sure you are in an elevated PS session and you should be good to go. You can use Graph however all that  would require an E5 license or equivalent in most cases.

**Comment by sudkumar1** [comment]
I tried to find the equivalent graph API but unable to find find it, can you please help the graph API doc for  Compliance and security center ?

**Comment by rudesome** [comment]
> > > Since it is not possible to do a new-compliancesearch and action with Exchange, is it possible to do it with MsGraph ?
> > 
> > 
> > I have been able to do a compliance search
> > ```
> > Connect-IPPSSession -ConnectionUri $ConnUri -CertificateFilePath $CertPath -CertificatePassword $pass -AppID $AppId -Organization $TenantId
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am just not able to start it
> > ```
> > Start-ComplianceSearch gives me a object null reference error
> > ```
> 
> @jbb4play Just make sure you are in an elevated PS session and you should be good to go. You can use Graph however all that would require an E5 license or equivalent in most cases.

@bluestarcs 
this is definitely a bug in Powershell Core, as the same process/cmdlet is functioning just fine within Windows Powershell...
if Microsoft wants customers to buy E5 licenses they should remove the cmdlet completely from the EXO module and admin portal...

**Comment by truezjz** [comment]
does this issue fixed in V3.1?

**Comment by truezjz** [comment]
As I tested with latest version V3.1,  still the same error with app authentication, is it because the license?  we're on E3.
BTW, why this issue was closed?

**Comment by joseraeiro** [comment]
I have exactly the same issue. What can I do?

**Comment by chrisda** [comment]
I'm told the solution is to create service principals in Security & Compliance PowerShell, and then the whole process will work. The procedure of creating service principals is already in the article, but it's generic for both Exchange Online and Security & Compliance PowerShell, there's no specific call-outs about eDiscovery cases.

I also see the need for some related updates to the article, because v3.2.0-Preview4 or later now supports REST API mode in S&C PowerShell, and REST API mode is a requirement to create the service principal and add it as a member to the custom role group.

[Assign custom Exchange Online role groups to the application using service principals](https://learn.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#assign-custom-exchange-online-role-groups-to-the-application-using-service-principals)

Please confirm or deny if those procedures help.

**Comment by chrisda** [comment]
I did the updates per the associated pull request. The section link is now:

[Assign custom role groups to the application using service principals](https://learn.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#assign-custom-role-groups-to-the-application-using-service-principals)

Same request as before: reply here if this information fixes the problem.

**Comment by joseraeiro** [comment]
> I did the updates per the associated pull request. The section link is now:
> 
> [Assign custom role groups to the application using service principals](https://learn.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#assign-custom-role-groups-to-the-application-using-service-principals)
> 
> Same request as before: reply here if this information fixes the problem.

And where do I insert these commands suggested in the Assign custom role groups to the application using service principals section? In PowerShell Exchange Online?

**Comment by joseraeiro** [comment]
And what permissions should I assign in order to be able to run Start-ComplianceSearch?

Here's what Get-RoleGroup | Format-Table Name gives:

AttackSimAdministrators
AttackSimPayloadAuthors
OrganizationManagement
SecurityAdministrator
BillingAdministrator
eDiscoveryManager
ComplianceAdministrator
InsiderRiskManagement
InsiderRiskManagementAdmins
InsiderRiskManagementAnalysts
InsiderRiskManagementInvestigators
CommunicationComplianceInvestigators
CommunicationCompliance
PrivacyManagement
PrivacyManagementAdministrators
PrivacyManagementAnalysts
PrivacyManagementInvestigators
SubjectRightsRequestAdministrators
DataInvestigator
CommunicationComplianceAdministrators
CommunicationComplianceAnalysts
CommunicationComplianceViewers
ComplianceDataAdministrator
ComplianceManagerAdministrators
ComplianceManagerAssessors
ComplianceManagerContributors
SecurityReader
GlobalReader
ComplianceManagerReaders
PrivacyManagementViewers
PrivacyManagementContributors
SubjectRightsRequestApprovers
SecurityOperator
ContentExplorerContentViewer
InformationProtection
InformationProtectionInvestigators
DataEstateInsightsReaders
ContentExplorerListViewer
InformationProtectionAnalysts
DataCatalogCurators
RecordsManagement
InformationProtectionAdmins
InformationProtectionReaders
InsiderRiskManagementApprovers
InsiderRiskManagementAuditors
IRMContributors
InsiderRiskManagementSessionApprovers
KnowledgeAdministrators
QuarantineAdministrator
Reviewer
ServiceAssuranceUser
SupervisoryReview
MailFlowAdministrator
DefaultRoleAssignmentPolicy

**Comment by fpsacha** [comment]
> And what permissions should I assign in order to be able to run Start-ComplianceSearch?
I had to give myself the eDiscoveryManager for it to work. But i mean work on my account. I still did not tried with an azure apps. Back then it did not work. Hope it does now.

**Comment by joseraeiro** [comment]
@chrisda I've created a new role group and assigned to it all the roles output by Get-ManagementRole. Is this dangerous somehow?

And it's working now! Thank you for all your kind help!

**Comment by chrisda** [comment]
@joseraeiro, assigning all roles to the role group is a bit overkill. You've effectively made the service principal a global admin, which will certainly work, but is likely way more permissions than it needs (like running attack simulation training, creating anti-spam policies, anti-malware policies, etc.). The concept of 'least privilege' is always a good idea.

I would say make your custom role group have the same roles assigned as the eDiscovery Manager role group as described [here](https://learn.microsoft.com/microsoft-365/security/office-365-security/mdo-portal-permissions#modify-email--collaboration-role-group-role-assignments-in-the-microsoft-365-defender-portal).

Last time I checked, eDiscovery Manager contained the following roles:

- Case Management
- Communication
- Compliance Search
- Custodian
- Export
- Hold
- Manage Review Set Tags
- Preview
- Review
- RMS Decrypt
- Scope Manager

**Comment by joseraeiro** [comment]
@chrisda I'm now trying to perform a Compliance Search Action to Hard Delete all the emails found in a previous Compliance Search. I'm using the following command:

New-ComplianceSearchAction -SearchName "[name of the compliance search]" -Purge -PurgeType HardDelete -Confirm:$false

And, although I'm not getting any errors the emails don't get deleted as performing another compliance search with the same parameters eventually reveals.

I had assigned all roles to the role group, so I'm guessing it's not permissions.

Thank you in advance.

**Comment by chrisda** [comment]
@joseraeiro, you should open a support ticket.

**Comment by joseraeiro** [comment]
@chrisda With Microsoft Support?

I have 3 tickets open and no one was able to help me so far.

**Comment by samrajcse** [comment]
@chrisda - With CBA I can able to create and start case with E5 license, but cant able to get results for Get-ComplianceSearch. It throws 400 bad request.

**Comment by couradeus** [comment]
@joseraeiro , maybe you have m365 retention policy that is stopping you from deleting the emails from the mailbox. from user perspective, the emails would have been deleted because they cannot access them. but from administrator perspective you can still retrieve them. you'll need to add those users in exception from the M365 retention policy first before running the purge.

**Comment by samrajcse** [comment]
@chrisda I have msot recent version also I tried latest beta version too. Can you please help me in creating support ticket? I tried multiple channel and the response is not positive?

**Comment by chrisda** [comment]
@samrajcse, in the Microsoft 365 admin center at <https://admin.microsoft.com>, select **Help & support**.
 
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/33166947/ac214eb1-2649-4dc2-9a85-a2db1c6cbc63)

Be sure you're using the latest GA version of the module (v3.2.0). Support can't/won't help you if you're using a Preview version of the module.
