### ISSUE TITLE
Teams 4.5.0 InterpretedUserType behaviour

### ISSUE THREAD

**Issue by paulsysadmin** [MicrosoftDocs/office-docs-powershell#9636]
Why does InterpretedUserType change if I use Resultsize ?

![Teams_Powershell](https://user-images.githubusercontent.com/105910643/177705714-3a22d5c1-af30-4349-8c10-676d295091ec.png)

**Comment by shivtorov** [comment]
@paulsysadmin , see #9453

**Comment by paulsysadmin** [comment]
> @paulsysadmin , see #9453

That's a different issue. I'm using Module 4.50 here. Why would using a ResultSize parameter change the User Type ?

**Comment by shivtorov** [comment]
InterpretedUserType is broken since v.3.x.x
The last version that reliably returned InterpretedUserType values was 2.6.0, but it is no longer allowed.

Resultsize paramater is irrelevant for this issue.
Get-CsOnlineUser correctly reports InterpretedUserType only in one case - if you use `-Identity` parameter. 
In all other cases InterpretedUserType value is wrong.

**Comment by paulsysadmin** [comment]
> InterpretedUserType is broken since v.3.x.x The last version that reliably returned InterpretedUserType values was 2.6.0, but it is no longer allowed.
> 
> Resultsize paramater is irrelevant for this issue. Get-CsOnlineUser correctly reports InterpretedUserType only in one case - if you use `-Identity` parameter. In all other cases InterpretedUserType value is wrong.

Thank you that makes sense. I'll use a Foreach loop to query for the time being.

**Comment by isrumnon** [comment]
Hi @shivtorov @paulsysadmin can you please share your tenant IDs with me here - isrumnon@microsoft.com
We'll check if we need to make any service side changes for your tenants.
p.s. I'm deleting this post for privacy reasons
