### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by walidelmorsy** [MicrosoftDocs/office-docs-powershell#9646]
1- for the parameter "**-ExchangeSenderMemberOf**", it sounds like the value "All" is not accepted. with "**-ExchangeLocation**" is not recommended according to the article, admins will be left with no options (unless I got the syntax wrong):

![image](https://user-images.githubusercontent.com/55671976/177945881-e49c0019-d7a1-4381-9307-fc2e434ed8ca.png)

2- In section (-ExchangeSenderMemberOfException), the paragraph text is the same as the previous section (just above it).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64d46b9d-594b-e24e-4964-71dab360cd28
* Version Independent ID: a6b0658b-cbda-6d29-59f1-d1189208c72a
* Content: [New-DlpCompliancePolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-dlpcompliancepolicy?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@walidelmorsy, fortunately for all of us, I spent time yesterday dealing with a similar issue in New/Set-AutoSensitivityLablel based on a support case, so I was able to basically copy those efforts into New/Set-DlpCompliancePolicy. I'll try to summarize:

- In New-, _ExchangeLocation_ only takes the value All. `-ExchangeLocation All` means: "the policy includes email messages (messages sent by all internal senders)". In Set-, `-AddExchangeLocation All` means: "add email messages to the policy", while `-RemoveExchangeLocation All` means: "remove email messages from the policy".

  _ExchangeLocation_ is available in plenty of other cmdlets, but it sure doesn't act that way! The parameter Type is MultiValuedProperty which implies multiple values, yet it only takes the value All. And, there are plenty of other _\*Location_ parameters in New/Set/DlpCompliancePolicy and other cmdlets that don't act that way!

- You can use _ExchamgeMemberOf_ to restrict the policy to look at email **only** from specific users (members of the specified groups). Likewise, you can use _ExchangeMemberOfException_ to look at email from all users **except** from specific users (members of the specified groups).

Either way, in New- you must use `-ExchangeLocation All` in the same command with _ExchamgeMemberOf_ or _ExchamgeMemberOfException_. In Set-, ExchangeLocation must already be set to All in the policy; otherwise, you must also use `-AddExchangeLocation All` in the same command with _ExchamgeMemberOf_ or _ExchamgeMemberOfException_.

**Comment by yogkumgit** [comment]
@walidelmorsy Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
