### ISSUE TITLE
Set-CsTenantDialplan with pre created Regular Expressions for New normaliazion rules fails 

### ISSUE THREAD

**Issue by ThomHauff** [MicrosoftDocs/office-docs-powershell#9652]
Hi there,

hopefully someone can shed some light into this. We are using a Script to prepare a new Teams Phone system location. All of this script has been working prior the Teams Powershell module update to version 4.0.0 and later. Before the update, we were using version 2.0.0. Currently we`re using the latest 4.5.0 version. After spending hours of investigation so far, I was able to narrow it down to the regular expressions which are created before we use them in the New-CsVoiceNormalizationRule CMDlet, but was not able to solve the issue.

Here are the lines that have been working before the update of the Teams PS module:

- $Dialplan="DE-Test-621789"
- $DialplanSimpleName="DE-Test"
- $regexInternational = New-CsVoiceRegex -StartsWith '00' -AtLeastLength 6 -DigitsToStrip 2 -DigitsToPrepend '+'
- $NR2=New-CsVoiceNormalizationRule -Parent $Dialplan -Name "$DialplanSimpleName-International" -Pattern $regexInternational.Pattern -Translation $regexInternational.Translation -InMemory
- Set-CsTenantDialPlan -Identity $Dialplan -NormalizationRules @{Add=$NR2}

There is no error when creating the RegEx or the Voice Normalization Rule. Even when reviewing the content of the variables $regexInternational and $NR2, it looks good.

The error which is given is this:

_Set-CsTenantDialPlan : NormalizationRules has data of type Microsoft.Rtc.Management.WritableConfig.Policy.Voice.NormalizationRule that is not supported
Parameter name: NormalizationRules_

On the other side, if I replace the Pattern and the Translation variables in the New-CsVoiceNormalizationRule command with the actual values which are configured in the New-CsVoiceRegex, it`s working.

The syntax of the above mentioned commands is in accordance to https://docs.microsoft.com/en-us/powershell/module/skype/new-csvoiceregex?view=skype-ps and https://docs.microsoft.com/en-us/powershell/module/skype/new-csvoicenormalizationrule?view=skype-ps

Any help is highly appreciated.
Thanks and regards
Thomas

**Comment by shivtorov** [comment]
I never used `New-CsVoiceRegex`. 
It looks like `New-CsVoiceRegex` is from on-premises SkypeForBusiness powershell module, and it is not present in MicrosoftTeams powershell module. On the other hand, `New-CsVoiceNormalizationRule` is present in both modules.
I guess when you try using these commands together in a single session, it is using the wrong version of the commandlet.

Due to such issues caused by overlapping commands, for Teams configuration purposes I prefer to use a separate PC where only Teams module is installed. That's the most straightforward and guaranteed way not to get confused.

In your case, you should be able to fix the issue by explicitly specify the module, e.g.:
`$NR2=MicrosoftTeams\New-CsVoiceNormalizationRule -Parent $Dialplan -Name "$DialplanSimpleName-International" -Pattern $regexInternational.Pattern -Translation $regexInternational.Translation -InMemory` (notice `MicrosoftTeams\` prefix).

Alternatively, you can try to explicitly convert params to text in a hope that it will help:
`$NR2=New-CsVoiceNormalizationRule -Parent $Dialplan -Name "$DialplanSimpleName-International" -Pattern $regexInternational.Pattern.ToString() -Translation $regexInternational.Translation.ToString() -InMemory`

**Comment by ThomHauff** [comment]
Thanks for your answer @shivtorov
Adding "MicrosoftTeams" in front of the New-CsVoiceNormalizationRule doesn`t work, as the CMDlet itself is already for Teams/SfBO, because you can "tab" the command which will bring up a "SkypeForBusiness\New-CsVoiceNormalizationRule".
As in my posted link to the NewCsVoiceRegex CMDlet was also the category "Skype for Business Online" I was quite sure, that this also is valid for Teams Powershell. And as mentioned, the whole script has been working with Teams Powershell module v.2.0.0 and has stopped working with v. 4.0.0 and above.

BUT...you maybe brought me into the right direction. After doing a little more research, I saw, that there is a CMDlet "New-CsTeamsTranslationRule" https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamstranslationrule?view=skype-ps which basically does the same as the New-CsVoiceRegEx. You have to provide the already created Regular Expression to this command instead of providing information like "-StartsWith" or "-AtLeastLength"with the New-CsVoiceRegex.

I will look deeper into this tomorrow.

Regards
Thomas

**Comment by JensTrier** [comment]
@ThomHauff New-CsTeamsTranslationRule is used for trunk normalization rules for SBC's (OnlinePstnGateway). My recommendation is that you use New-CsVoiceNormalizationRule. I normally use one of the RegEx tester sites on the Internet to generate & validate the RegEx.

**Comment by shivtorov** [comment]
@ThomHauff 
You are overcomplicating things by trying to use a helper function `New-CsVoiceRegex` from `SkypeForBusiness` module in your script written for `MicrosoftTeams` module. Thus, you hit this compatibility issue.

Run the following to see same-name cmdlets that are likely the cause of the error you descripted:
```PowerShell
Import-Module -Name SkypeForBusiness,MicrosoftTeams
Get-Command -Name New-CsVoiceRegex,New-CsVoiceNormalizationRule,New-CsTenantDialPlan -Module SkypeForBusiness,MicrosoftTeams | sort Source,Name
```

![image](https://user-images.githubusercontent.com/31003608/178426033-b9df04bc-b719-49aa-b851-c1e564e1deef.png)

So, when you use `New-CsVoiceRegex` it implicitly imports `SkypeForBusiness` module.
But if drop this cmdlet from your script, then it will not load `SkypeForBusiness` module, thus only use `MicrosoftTeams` module.
You already have a fix for the issue - you described it in the initial post.

Are you simply interested in why your script was working with `MicrosoftTeams` module v.2.x.x, but fails with `MicrosoftTeams` module v.4.x.x? Well, when a module changes its major version, it is likely due to breaking changes in its implementation. It is expected that some scripts might be broken after such module upgrade.

**Comment by ThomHauff** [comment]
@JensTrier Thanks for your answer.
We already use the New-CsVoiceNormalizationRule. But as you say, you`re using a Regex tester to generate and test your rules. Our script is designed to automate the creation process of a new voice location and to automatically generate all the RegEx expressions based on the provided input information at the beginning of the script from the user who executes it. For this purpose the New-CsRegEx was perfect for us and has been working until the Teams Powershell module was updated.
For each of our dialplans we use 5 different normalization rules, so generating the RegEx manually everytime with external tools is not an option for us.

I did a quick test with the New-CsTeamsTranslationRule and added it the same way to the New-CsVoiceNormalizationRule like I did in the past with the New-CsVoiceRegEx. That worked.

**Comment by ThomHauff** [comment]
@shivtorov 
I understand what you mean. The fix I mentioned in the initial post was only by adding the plain regular expression to the New-CsVoiceNormalizationRule command, but as stated in my comment to @JensTrier that is not an option.

I`m totally aware that commands may change with major upgrades of the Teams module. I`m reviewing the changes to the module on a regular basis in this article https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes?WT.mc_id=M365-MVP-9501

Now that I know, that the New-CsRegEx is explicitly for SfB, the simple question is if I can replace the New-CsRegEx with New-CsTeamsTranslationRule in our script, as it`s working with this :)

**Comment by JensTrier** [comment]
@ThomHauff My strong recommendation is not to mix these two cmdlets. VoiceNormalizationRule is intended to be used with TenantDialPlan.

**Comment by ThomHauff** [comment]
@JensTrier which 2 CMDlet would you not mix? 
I also have opened a ticket with MS and will get a call back at 10AM. Will provide feedback afterwards.

**Comment by JensTrier** [comment]
@ThomHauff What I mean was only use VoiceNormalizationRule with TenantDialPlan and use TeamsTranslationRule with OnlinePstnGateway. I'll update the docs to make this clear.

**Comment by ThomHauff** [comment]
@JensTrier I just had the call with the MS engineer and she doublechecked with her technical team lead and confirmed afterwards, that the New-CsTeamsTranslationRule can be used as the replacement for the New-CsVoiceRegEx.

**Comment by ThomHauff** [comment]
I modified the script now with using the -NewCsTeamsTranslationRule instead of New-CsVoiceRegEx, tested and everything is working again as expected.
Thanks everybody for answering and sharing thoughts
