### ISSUE TITLE
CBA not supported for eDiscovery-based cmdlets

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/office-docs-powershell#9759]
Currently, certain cmdlets such as "Get-ComplianceCase" and "Get-CaseHoldPolicy" do not work with Cert-Based Authentication for SCC. 

This is important to call out as a consideration, that not all cmdlets are supported by all authentication types into the shell sessions - as with the deprecation of Basic Authentication, many organizations will be switching to Cert-Based auth for automation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
I'm attempting to get a list of affected cmdlets. Once I have that, I'll update the topic.

**Comment by chrisda** [comment]
Per email thread those two cmdlets are the only Security & Compliance PowerShell cmdlets that don't work with CBA.

I updated the CBA topic and added a note in the SYNOPSIS section of the individual cmdlet topics.

Thanks for the feedback.

Closing.

**Comment by blueleader07** [comment]
Hello, can you tell me if Microsoft plans to add support for Get-ComplianceCase and Get-CaseHoldPolicy?  Just switched from basic auth to cert-based auth ... and now I'm realizing I can't even search for a case or policy.  These are basic commands that allow us to navigate from Case to Policy to Rule.  Is there an alternative?  I'm not sure what the point of switching is if we can't use the same commands?

Get-ComplianceCase -Identity "Case 1234"
Get-ComplianceCase: Unable to execute the task. Reason: You don't have access to "Case 1234" because you're not a member of this compliance case.
