### ISSUE TITLE
Valid user access to run Test-CsLisCivicAddress

### ISSUE THREAD

**Issue by jinbchoi** [MicrosoftDocs/office-docs-powershell#9797]
[Enter feedback here]
The part not mentioned on the document is that the fact I observed, and the reference article below which the certificate(.pfx) will be stored in the Personal Certificate Store instead of Local Machine in course of the Set-CsLisServiceProvider process, which is related to the step when it comes to the PScmdlet Test-CsLisCivicAddress.
In the case for a large org which happens to have multiple admins for their SfB and the admin who didn't originally configure the  LIS provider with the Set-CsLisServiceProvider on the machine, the specific admin wouldn't be able to leverage the certificate for him/her personal certificate store and could end up with the error "Could not create SSL/TLS secure channel"

It would be helpful for the customers get the detail information and background included in the document.
Thanks.

Reference document
https://ucworkerbee.com/2019/08/02/fix-skype-for-business-server-cannot-access-master-street-address-guide-msag/
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e505d937-c075-bab3-0103-ac5f93df9372
* Version Independent ID: 98b66f30-07a8-37b9-e82d-6cda847cd25c
* Content: [Set-CsLisServiceProvider (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cslisserviceprovider?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsLisServiceProvider.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsLisServiceProvider.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by get-itips** [comment]
Hello @jinbchoi 
I am looking into this, thanks for your feedback.

**Comment by yogkumgit** [comment]
@get-itips Any update

**Comment by get-itips** [comment]
Hello @jinbchoi 
Sharing with you the answer from product team

The cmdlet Set-CsLisServiceProvider, that takes a .pfx certificate file will **not** copy the certificate in the Personal Store (of the running admin) of the SfB Server where it's run.
 
From what we understand the issue is :

1. When using the Test-CsLisCivicAddress cmdlet it returns an error

2. The error being : The request was aborted: Could not create SSL/TLS secure channel.

 
This happens because you need to set before you do any other actions.
 

When we use the Set-CsLisServiceProvider cmdlet, it takes the name of the provider, a URL for the web service that the organization will use to send the locations and a certificate &  password for the secure web service.

 
example :

Set-CsLisServiceProvider -ServiceProviderName E911Provider -ValidationServiceUrl https://www.911contoso.com/validation/ -CertFileName C:\MS-Contoso-Cert.pfx -Password $p

 
Then , a sproc is run which stores this authentication information in DB of that machine -and not in personal store.

Then when a Test-CsLisCivicAddress cmdlet is run, it uses that stored information.

**But if we run the test command directly, it doesn’t have that certificate info in DB. So, it throws an error.**

Hope this information helps you, other than that, I don't see an edit to the article required.

**Comment by jinbchoi** [comment]
Hi Andres,

Thanks a lot for the review and providing the update. I guess my(cx's) main question was "why Test-CsLisCivicAddress command fails on the person who wasn't the user who set up the E911 provider using Set-CsLisServiceProvider?"
Here is the challenge customer has;

  1.  The provider has set early on from a person(say, John) in the past and E911 had worked fine ever since
  2.  They have a routine check for the E911 using Test-CsLisCivicAddress, but they don't know who would be the user performing the test since there are multiple admins
  3.  They have noticed that there wouldn't be an issue when John performs the test. But, all other people than him gets failure
You probably elaborated in the explanation, but cx would like to get the consistent result no matter who execute the tests expecting Set-CsLisServiceProvider would be one time thing unless there is any changes with the provider/cert/etc.

Hope this clarify the challenge with the design and current public documentation.
Please feel free to contact me if you have any questions.
Thanks again!

Jin

**Comment by get-itips** [comment]
@jinbchoi I can understand, I'll share the feedback.
