### ISSUE TITLE
MessageCopyForSMTPClientSubmissionEnabled on Set-Mailbox is empty

### ISSUE THREAD

**Issue by dr-raypc** [MicrosoftDocs/office-docs-powershell#9953]
The -MessageCopyForSMTPClientSubmissionEnabled description is not filled out. Can someone fill out this description so we know what that command will do?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7f835af-5905-368a-df68-6646782ad807
* Version Independent ID: 153ce2d2-dab5-9c8f-c511-ee3bc8ee2dbc
* Content: [Set-Mailbox (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dr-raypc, availability of a parameter vs. functionality of a parameter are two different things. For a complete explanation, see [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).

So, are you trying to use that parameter, in particular from directions in other articles or blog posts? Or are you just curious why it's empty?

**Comment by DMoenks** [comment]
I recently had to use the parameter when working on an SMTP use case and it pretty much does what its name implies, in accordance with the **MessageCopyForSendOnBehalfEnabled** and **MessageCopyForSentAsEnabled** parameters/settings: When a message is submitted via SMTP, it controls whether a copy of the message is stored in the mailbox or not. If not, there's no indication of a message having been sent when looking at the mailbox's content.

**Comment by dr-raypc** [comment]
Both. I am investigating an Outlook bug with the current version installed and while comparing permissions and documentation I am curious to why it’s empty. I would feel even outside my issue that these Microsoft docs should be complete to both what the parameter is and what is the object of the parameter. Any outsider looking at the Set-Mailbox MS documentation would not know what the ‘-MessageCopyForSMTPClientSubmissionEnabled’ parameter entails.

**Comment by chrisda** [comment]
@DMoenks, thanks for the explanation.

@dr-raypc, as I mentioned, the explanation as to why there are parameters with blank descriptions is [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486). No one is implying that you're supposed to figure out what parameters with empty descriptions are for. As of today, there are 1397 Exchange cmdlet reference topics with 14,313 parameters, so there are bound to be some empties (270 in 94 cmdlets). I determined some time ago that it was better to add known, available parameters with empty descriptions in order to spark the kinds of conversations we're having now. Nature abhors a vacuum, water runs downhill, etc., so parameters that should be available and are functional will get noticed and (eventually) documented.

Topic updated in the reference pull request.

Thanks for the feedback.

Closing
